### PR TITLE
Conformance results for v1.8/kube-up-gce

### PR DESCRIPTION
**Pull request by mml**
Everything is correct here except documentation_url, which I hope to fill in tomorrow.

### CODE REVIEW

**Comment by luxas** [comment]
This should read GKE/v1.8, right?

**Comment by mml** [comment]
@luxas the intent here is to submit results for `kube-up.sh` when it starts a cluster on GCE.  I clarified the names, hope this helps.  @WilliamDenniss can you double check my work here?

**Comment by luxas** [comment]
@mml Ok, great to have that clarification.
Oh, now I see https://github.com/cncf/k8s-conformance/pull/5 which seems to be the commercial product :+1:

**Comment by WilliamDenniss** [comment]
LGTM

**Comment by kbarnard10** [comment]
+1

**Pull request merged**
