### PR TITLE
Add SamsungSDS-Kubernetes-Service conformance result for v1.17

### PR DESCRIPTION
**Pull request by thdrnsdk**
### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [x] If this is a new entry, have you submitted a signed [participation form](https://github.com/cncf/k8s-conformance/tree/master/participation-form)?
* [x] Did you include the product/project logo in SVG, EPS or AI format?  
* [x] Does your logo clearly state the name of the product/project and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [x] If your product/project is open source, did you include the `repo_url`?
* [x] Did you copy and paste the [installation and configuration instructions](https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions) into the README.md file in addition to linking to them?

Add SamsungSDS-Kubernetes-Service conformance result for v1.17

### CODE REVIEW

**Comment by taylorwaggoner** [comment]
@thdrnsdk - thanks for submitting! In your README, are there installation instructions you can copy and paste into the file? Thanks!

**Comment by thdrnsdk** [comment]
Sorry, there is a separate script to install our product, and the installation method and installation guide are not publicly available.

**Comment by dankohn** [comment]
Could you please paste in at least a summary of the installation steps? In particular, is there any special configuration necessary to get the tests to pass? We're trying to provide guidance so that your customers can later validate your conformance if they wish to.

**Comment by thdrnsdk** [comment]
Ok update READM.md
and we don't have any special configuration for conformance test.
The configuration file we use for installation only contains the number of workers, masters, etcd nodes, and information about services, pod cidr, and so on.

**Comment by dankohn** [comment]
That's fine but could you please then include the config.yaml in your submission so there's no mystery for your users on how to recreate your test results?

**Comment by thdrnsdk** [comment]
@dankohn Detaild config file has been added. Thanks for reviewing. And let me know if there is anything missing

**Comment by taylorwaggoner** [comment]
You are now Certified Kubernetes

**Pull request merged**
