### PR TITLE
Add v1.14/koris

### PR DESCRIPTION
**Pull request by oz123**

### CODE REVIEW

**Comment by taylorwaggoner** [comment]
You are now Certified Kubernetes
https://landscape.cncf.io/format=card-mode&organization=noris-network&selected=koris

**Comment by oz123** [comment]
@taylorwaggoner the card says that the license isn't open source. However, all source code is available online. Did I miss something in the PR?

**Comment by dankohn** [comment]
Yes. It's fine to host your software on GitLab but we need you to create a mirror on GitHub. We fetch a lot of information from the GitHub API. When you've done so, please let us know the URL and we'll add it to the landscape and it will show as open source.

Here are directions: https://docs.gitlab.com/ee/user/project/repository/repository_mirroring.html

**Comment by oz123** [comment]
@dankohn thanks for the quick answer,
Here is the repository:
https://github.com/noris-network/koris.
It's not really a mirror though. Just a reference and a place where you can download the binary distribution and the source code.

**Comment by dankohn** [comment]
To count the project as open source, we actually need the code hosted (or mirrored) on GitHub. We then use GitHub to tell us the license, first and last commit, activity, etc.

Click through the 44 open source Certified Kubernetes implementations and you can see: https://landscape.cncf.io/category=certified-kubernetes-distribution,certified-kubernetes-hosted,certified-kubernetes-installer&format=card-mode&grouping=category&license=open-source

**Comment by oz123** [comment]
@dankohn mirror is setup! https://github.com/noris-network/koris
You can get all the metadata, is there something specific that needs to be done?

**Comment by dankohn** [comment]
You should now be all set: https://landscape.cncf.io/selected=koris

**Comment by oz123** [comment]
How often does this update? Github wasn't detecting the license properly. ...

**Comment by dankohn** [comment]
Nightly. It will pick it up Thursday night.

**Pull request merged**
