### PR TITLE
Rename for v1.21/DAP Kubernetes Service Hatoba

### PR DESCRIPTION
**Pull request by syyama-net**
### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [x] If this is a new entry, have you submitted a signed [participation form](https://github.com/cncf/k8s-conformance/tree/master/participation-form)?
* [x] Did you include the product/project logo in SVG, EPS or AI format?  
* [x] Does your logo clearly state the name of the product/project and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [ ] If your product/project is open source, did you include the `repo_url`?
* [x] Did you copy and paste the [installation and configuration instructions](https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions) into the README.md file in addition to linking to them?

### CODE REVIEW

**Comment by syyama-net** [comment]
I closed #1744 by mistake, but it is the same content.

**Comment by taylorwaggoner** [comment]
@syyama-net please also make sure to update the product details in the PRODUCT and README files - you'll want to update the product name and description and any changes to the product website, etc. Thanks!

**Comment by syyama-net** [comment]
@taylorwaggoner Sorry, I forgot to push. Thanks.

**Comment by taylorwaggoner** [comment]
Thanks! I'll get this updated in the landscape and will merge when complete, thanks

**Comment by taylorwaggoner** [comment]
Product has been [updated](https://landscape.cncf.io/card-mode?category=certified-kubernetes-distribution,certified-kubernetes-hosted,certified-kubernetes-installer,special&grouping=category&organization=fujitsu&selected=fujitsu-hybrid-it-service-digital-application-platform-kubernetes-service-hatoba), thanks!

**Pull request merged**
