### PR TITLE
Conformance results for v1.24/aks

### PR DESCRIPTION
**Pull request by lachie83**
Signed-off-by: Lachlan Evenson <lachlan.evenson@microsoft.com>

### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [x] If this is a new entry, have you submitted a signed [participation form](https://github.com/cncf/k8s-conformance/tree/master/participation-form)?
* [x] Did you include the product/project logo in SVG, EPS or AI format?  
* [x] Does your logo clearly state the name of the product/project and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [x] If your product/project is open source, did you include the `repo_url`?
* [x] Did you copy and paste the [installation and configuration instructions](https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions) into the README.md file in addition to linking to them?

### CODE REVIEW

**Comment by hh** [comment]
@BobyMCbobs this looks good

**Comment by Riaankl** [comment]
@lachie83 we have just rolled out an additional requirement for the PRODUCT.yaml to include a contact email address. 
You PR was the only one open at the time. That is why you had `All requirements (15) have passed for the submission!` turning in to `14 of 15 requirements have passed` 
Apology for any inconvenience caused.

**Comment by lachie83** [comment]
@Riaankl I just pushed a commit to add `contact_email_adress` to PRODUCT.yaml

**Comment by Riaankl** [comment]
Thanks for that @lachie83 
Bot automatically detected the updated the labels accordingly as expected.
I will call that a success!

**Comment by taylorwaggoner** [comment]
You are now Certified Kubernetes

**Pull request merged**
