### PR TITLE
Conformance results for v1.7/ebaocloud

### PR DESCRIPTION
**Pull request by cdyue**
vendor: eBaoTech
name: eBaoCloud Platform
version: v1.0.0
website_url: https://sg.ebaocloud.com/
documentation_url: https://sg.ebaocloud.com/
product_logo_url: https://enablement.ebaocloud.com/staticfile/img/logo.png

### CODE REVIEW

**Comment by taylorwaggoner** [comment]
Hi @cdyue - In order to be certified, you'll need to either become a member of CNCF or pay a certification fee equal to the cost of membership.  Please reach out to memberships@cncf.io to become a member.  

You'll also need to send in a signed Participation Form: https://github.com/cncf/k8s-conformance/blob/master/participation-form/Certified_Kubernetes_Form.pdf.  

Please also resubmit results with a "Type" in the product.yaml file as requested here: https://github.com/cncf/k8s-conformance/blob/master/instructions.md#productyaml

Please let me know if you have any questions. Thanks!

**Comment by taylorwaggoner** [comment]
Also please note that we are only certifying for v1.9 and v1.10.  More details can be found in the Conformance FAQ - https://github.com/cncf/k8s-conformance/blob/master/faq.md#what-versions-of-kubernetes-can-be-certified

**Comment by cdyue** [comment]
@taylorwaggoner Thanks for the reply.Is the charge by annually?

**Comment by dankohn** [comment]
Yes, membership in CNCF is an annual charge as shown here:
https://www.cncf.io/about/join/

We'd be happy to discuss membership with you. Would you rather do it in
Chinese with our representatives in Hong Kong or in English?

--
Dan Kohn <dan@linuxfoundation.org>
Executive Director, Cloud Native Computing Foundation https://www.cncf.io
+1-415-233-1000 https://www.dankohn.com

**Comment by cdyue** [comment]
My company has proceeded the membership of  CNCF. In the other hand, I have installed kubernetes 1.10.2 and E2E test got 1 Failed. Where can I get help passing the test?

```
[Fail] [sig-network] DNS [It] should provide DNS for services  [Conformance]
```

**Comment by dankohn** [comment]
Thanks for becoming a member. Could you please try installing "vanilla" Kubernetes from kubeadm and see if that passes the tests. If it does, the issue is presumably in the diff between vanilla and your distro.

If it doesn't perhaps you're running into DNS errors due to the Great Firewall. If you want to publish more details on the test that is failing, we can hopefully help or refer you to someone who can.

**Comment by cdyue** [comment]
@dankohn Thanks. 

 I used kubeadm to install kubernetes cluster, installed flannel, no others add-ons or apps, still got fail.Please help!

[e2e.log](https://github.com/cncf/k8s-conformance/files/1990963/e2e.log)

**Comment by cdyue** [comment]
@dankohn Thanks.

**Comment by luxas** [comment]
@cdyue Please talk to us in the #sig-cluster-lifecycle channel in the Kubernetes Slack. I think I know what might be the problem for you in your env. Anyway, as @dankohn said, you need to upgrade your Kubernetes version first.

**Pull request closed without merging**
