### PR TITLE
Conformance results for v1.10/dcos-kubernetes

### PR DESCRIPTION
**Pull request by pires**
vendor: Mesosphere
name: Kubernetes on DC/OS
version: 1.1.0-1.10.3
website_url: https://mesosphere.com/kubernetes/
documentation_url: https://docs.mesosphere.com/services/kubernetes/1.1.0-1.10.3/
product_logo_url: https://mesosphere.com/wp-content/uploads/2017/11/MESO_dcos_Horz_RGB-SJxDvlwp3-.png
type: installer
description: 'DC/OS Kubernetes package makes it easy to deploy and manage Kubernetes on DC/OS.'

### CODE REVIEW

**Comment by taylorwaggoner** [comment]
Hi @pires - Thanks for submitting!  Before I can certify this, can you please update the Client Version in the version.txt file so that it is equal to the Conformance Version 1.10?  More info here: https://github.com/cncf/k8s-conformance/blob/master/reviewing.md#technical-requirements.  Thanks!

**Comment by pires** [comment]
@taylorwaggoner sure thing!

**Comment by pires** [comment]
@taylorwaggoner done!

**Comment by taylorwaggoner** [comment]
Thanks!  You are now Certified Kubernetes

**Comment by pires** [comment]
Thank you, @taylorwaggoner :bowing_man:

**Pull request merged**
