### PR TITLE
Conformance Results for v1.22/rafay

### PR DESCRIPTION
**Pull request by akshar-rafay**
### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [ ] If this is a new entry, have you submitted a signed [participation form](https://github.com/cncf/k8s-conformance/tree/master/participation-form)?
* [x] Did you include the product/project logo in SVG, EPS or AI format?  
* [x] Does your logo clearly state the name of the product/project and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [ ] If your product/project is open source, did you include the `repo_url`?
* [x] Did you copy and paste the [installation and configuration instructions](https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions) into the README.md file in addition to linking to them?

### CODE REVIEW

**Comment by akshar-rafay** [comment]
@taylorwaggoner PTAL

**Comment by taylorwaggoner** [comment]
@akshar-rafay is this a different product than previously certified, or just that you renamed the product? You have "Rafay Kubernetes Operations Platform" here but previously it was just "Rafay".  If the product was renamed, please submit a new [participation form](https://github.com/cncf/k8s-conformance/tree/master/participation-form).

Do you also want us to rename the product here? https://landscape.cncf.io/card-mode?organization=rafay-systems&selected=rafay

 Thanks!

**Comment by taylorwaggoner** [comment]
Please also update your README to show more detailed steps to recreate your conformance results, as you had in previous pull requests: https://github.com/cncf/k8s-conformance/blob/master/v1.21/rafay/README.md
Thanks!

**Comment by akshar-rafay** [comment]
@taylorwaggoner I have updated the README to include a more detailed description on how to reproduce the test. With respect to your first question, the product is the same and I have reverted the name as well to 'Rafay', sorry for the confusion. 
Please let me know if any other changes required

**Comment by taylorwaggoner** [comment]
Thanks! You are now Certified Kubernetes

**Pull request merged**
