### PR TITLE
Conformance of MicroK8s on v1.13

### PR DESCRIPTION
**Pull request by ktsakalozos**
This PR contains the conformance tests for MicroK8s on v1.13.

There are two changes that I hope will not cause any problems:
 - The name f the product has slightly changed to "MicroK8s" (vs "microk8s")
 - There is a new logo

Thank you

### CODE REVIEW

**Comment by dankohn** [comment]
We'll review the submission shortly. Regarding the new logo, we have a policy at https://github.com/cncf/k8s-conformance/blob/master/instructions.md#productyaml which links to https://github.com/cncf/landscape#logos which is that we don't allow reversed logos.

We converted your logo to be non-reversed (zipped and attached) and will use it unless you want to submit a different one.

[microk8s.svg.zip](https://github.com/cncf/k8s-conformance/files/2741511/microk8s.svg.zip)

**Comment by taylorwaggoner** [comment]
@ktsakalozos Results look great!  Please let us know if you'd like to use the logo Dan provided above.  Thanks!

**Comment by ktsakalozos** [comment]
@tvansteenburgh, any objections on the logo?

**Comment by tvansteenburgh** [comment]
@sfabel, you good with this?

**Comment by sfabel** [comment]
@tvansteenburgh +1 thanks

**Comment by ktsakalozos** [comment]
Thank you @sfabel , @tvansteenburgh .

@taylorwaggoner the logo looks fine. Thank you.

**Comment by taylorwaggoner** [comment]
Thank you!  You are now Certified Kubernetes.
Changes submitted here: https://github.com/cncf/landscape/pull/1074

**Pull request merged**
