### PR TITLE
Conformance results for v1.11/platform9

### PR DESCRIPTION
**Pull request by pshanbhag**
vendor: Platform9 Systems, Inc.
name: Platform9 Managed Kubernetes
version: v3.9
website_url: https://platform9.com/managed-kubernetes/
documentation_url: https://platform9.com/support/
product_logo_url: https://platform9.com/wp-content/uploads/2018/04/Platform9-Managed-Kubernetes.svg
type: distribution
description: Platform9 Managed Kubernetes is SaaS-managed, infrastructure-agnostic, and works across public clouds and on-premises server infrastructure.

### CODE REVIEW

**Comment by taylorwaggoner** [comment]
@pshanbhag thank you for submitting these results.  Unfortunately, Kubernetes v1.13 was released yesterday, so we're no longer able to certify for v1.11 based on these guidelines: https://github.com/cncf/k8s-conformance/blob/master/faq.md#what-versions-of-kubernetes-can-be-certified

We are currently certifying for v1.12 and v1.13, so I'll hope you'll submit results for those!  Thank you!

**Comment by dankohn** [comment]
@pshanbhag You can reopen this pull request and it will now be approved after the policy change we just made: https://github.com/cncf/k8s-conformance/commit/4894e1cbad2c6b508a73f88ec2e393162863336a

**Comment by pshanbhag** [comment]
Thanks. I will submit a new PR. I cleaned out my previous PR branch.

**Comment by pshanbhag** [comment]
Submitted https://github.com/cncf/k8s-conformance/pull/420.

**Pull request closed without merging**
