### PR TITLE
Conformance results for v1.8/AppsCode

### PR DESCRIPTION
**Pull request by sanjid133**
vendor: Appscode
name: Pharmer by Appscode
version: TBD
website_url: https://appscode.com/products/pharmer
documentation_url: https://appscode.com/products/pharmer/docs
product_logo_url: https://appscode.com/images/logo-color.svg

### CODE REVIEW

**Comment by dankohn** [comment]
@sanjid133 You closed this pull request. Was that intentional or did you want to submit it? Reopening for now.

**Comment by dankohn** [comment]
Also, you need to become a member of CNCF in order to certify. Please email memberships@cncf.io for more info or see the information at https://www.cncf.io/about/join/.

**Comment by tamalsaha** [comment]
Hi Dan, please send the info membership signup.

Regarding the participation form, I am confused about the field "Participant Kubernetes Combinations". What information should put there?

Regarding the website and docs URLs - these URLs are correct but are not up yet. Is that an issue? In the meantime, our github URL is useful - https://github.com/appscode/pharmer

Regarding product version - the version will be released before kubecon. We have put TBD in there for now.

**Comment by dankohn** [comment]
Please update the website and docs URLs to point to working links, as we're
going to link to them when we make the announcement on 11/13. You can do a
pull request later when there are better links.

Participant Kubernetes Combination is if you want to call your product
Pharmer Kubernetes or similar. If not, you don't need to put anything
there.

I sent you membership info offline.

--
Dan Kohn <dan@linuxfoundation.org>
Executive Director, Cloud Native Computing Foundation https://www.cncf.io
+1-415-233-1000 https://www.dankohn.com

**Comment by tamalsaha** [comment]
I have signed participation form.

**Comment by kbarnard10** [comment]
@tamalsaha - Will wait for membership confirmation and working URLs before completing technical review.

**Comment by tamalsaha** [comment]
@kbarnard10, membership application is signed.

**Comment by tamalsaha** [comment]
Website and docs links are now working.

**Pull request merged**
