### PR TITLE
Conformance results for v1.19/k0s

### PR DESCRIPTION
**Pull request by trawler**
### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [x] If this is a new entry, have you submitted a signed [participation form](https://github.com/cncf/k8s-conformance/tree/master/participation-form)?

Yes, submitted for https://github.com/cncf/k8s-conformance/tree/master/v1.18/mirantis-docker-enterprise

* [x] Did you include the product/project logo in SVG, EPS or AI format?  
* [x] Does your logo clearly state the name of the product/project and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [x] If your product/project is open source, did you include the `repo_url`?
* [x] Did you copy and paste the [installation and configuration instructions](https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions) into the README.md file in addition to linking to them?

### CODE REVIEW

**Comment by taylorwaggoner** [comment]
@trawler everything looks great!  All we need is a new participation form for this product.  Thanks!

**Comment by trawler** [comment]
Thanks @taylorwaggoner. It's in the works and should be submitted shortly 👍

**Comment by jnummelin** [comment]
@taylorwaggoner Participation form has been signed and submitted.

**Comment by jnummelin** [comment]
@taylorwaggoner Is there anything still missing, can we do anything to speed up the merging of this?

**Comment by taylorwaggoner** [comment]
@jnummelin sorry for the delay here - the PR merged to add to the landscape, so you are now Certified Kubernetes
https://landscape.cncf.io/format=card-mode&selected=k0s

thanks!

**Comment by jnummelin** [comment]
@taylorwaggoner Thank you! 🎉

**Pull request merged**
