### PR TITLE
Add conformance docs for v1.10, v1.12

### PR DESCRIPTION
**Pull request by spiffxp**
Following instructions from https://github.com/cncf/k8s-conformance/issues/273#issuecomment-408572816

Manually generated via:
```
cd ~/w/k8s.io/kubernetes
for v in 1.10.9 1.12.2; do
  git checkout v$v
  go run test/conformance/walk.go \
    --conformance \
    --url https://github.com/kubernetes/kubernetes/tree/v$v/ \
    test \
    | sed -e "s/ - v1.9/ - v$v/" \
    > ~/w/cncf/k8s-conformance/docs/KubeConformance-$v.md
done
```

FYI @brahmaroutu

### CODE REVIEW

**Comment by brahmaroutu** [comment]
https://github.com/kubernetes/kubernetes/pull/70626
@spiffxp The release information is not printed properly in the 1.12 document, please see the above PR to fix this issue. I prefer using minor release tags when documenting so that conformance document is only expected on minor release.

**Comment by brahmaroutu** [comment]
Yes, @spiffxp I addresses the PR comments. I can generate the docs and push a PR to cncf repo as soon as the release build is available for 1.13.
 
----- Original message -----From: Aaron Crickenberger <notifications@github.com>To: cncf/k8s-conformance <k8s-conformance@noreply.github.com>Cc: Srini Brahmaroutu <srbrahma@us.ibm.com>, Mention <mention@noreply.github.com>Subject: Re: [cncf/k8s-conformance] Add conformance docs for v1.10, v1.12 (#366)Date: Fri, Nov 30, 2018 4:24 PM 
kubernetes/kubernetes#70626 needs to be fixed and cherry-picked back to the appropriate branches, will you have time to take care of that next week @brahmaroutu? would like to get out the docs for 1.13 prior to kubecon

**Comment by spiffxp** [comment]
Still awaiting an /approve on https://github.com/kubernetes/kubernetes/pull/70626

**Comment by dankohn** [comment]
It seems that we didn't get consensus on this pull request. I will close in 7 days unless there's activity.

**Pull request closed without merging**
