### PR TITLE
Conformance results for v1.20/cke

### PR DESCRIPTION
**Pull request by ysksuzuki**
### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [x] If this is a new entry, have you submitted a signed [participation form](https://github.com/cncf/k8s-conformance/tree/master/participation-form)?
* [x] Did you include the product/project logo in SVG, EPS or AI format?  
* [x] Does your logo clearly state the name of the product/project and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [x] If your product/project is open source, did you include the `repo_url`?
* [x] Did you copy and paste the [installation and configuration instructions](https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions) into the README.md file in addition to linking to them?

### CODE REVIEW

**Comment by ysksuzuki** [comment]
> This conformance request has the correct list of tests present in the junit file but at least one of the tests in e2e.log failed

As far as I look into the e2e.log, none of the tests have failed.

```
Ran 311 of 5668 Specs in 5121.344 seconds
SUCCESS! -- 311 Passed | 0 Failed | 0 Pending | 5357 Skipped
PASS

Ginkgo ran 1 suite in 1h25m22.316417034s
Test Suite Passed
```

**Comment by amye** [comment]
@hh: any idea what this might be picking up?

**Comment by bernokl** [comment]
I am unable to reproduce the error in my testing repo. I think it might have been a flake.
Please re-submit the pr, or could we please remove the labels @amye ?

**Comment by ErinThacker** [comment]
You are certified Kubernetes.

**Pull request merged**
