### PR TITLE
Conformance results for v1.22/k3s

### PR DESCRIPTION
**Pull request by rancher-max**
### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [x] If this is a new entry, have you submitted a signed [participation form](https://github.com/cncf/k8s-conformance/tree/master/participation-form)?
* [x] Did you include the product/project logo in SVG, EPS or AI format?  
* [x] Does your logo clearly state the name of the product/project and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [x] If your product/project is open source, did you include the `repo_url`?
* [x] Did you copy and paste the [installation and configuration instructions](https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions) into the README.md file in addition to linking to them?

### CODE REVIEW

**Comment by taylorwaggoner** [comment]
@rancher-max thanks for submitting.  Everything looks great but I had one quick comment.  Since becoming a sandbox project at CNCF, this product is listed under CNCF as the organization [in the landscape](https://landscape.cncf.io/card-mode?selected=k3s).  I just wanted to make sure that was known.  Sound good?

**Comment by cjellick** [comment]
@taylorwaggoner - I work with @rancher-max.

That's known. We aren't quite sure about why you brought that up though. Does something seem off or not right in this area to you?

**Comment by cjellick** [comment]
Oh! I think the vendor should be CNCF, right?

**Comment by taylorwaggoner** [comment]
@cjellick exactly!  Sorry I wasn't clear before, thank you!

**Comment by rancher-max** [comment]
@taylorwaggoner I went ahead and made the change to vendor and then squashed my commits so history would look clean. Should be good to rereview!

**Comment by taylorwaggoner** [comment]
Thanks! This is now Certified Kubernetes

**Pull request merged**
