### PR TITLE
Diamanti DCX 1.16.8

### PR DESCRIPTION
**Pull request by AlexDiamanti**
### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [ ] If this is a new entry, have you submitted a signed [participation form](https://github.com/cncf/k8s-conformance/tree/master/participation-form)?
* [ ] Did you include the product/project logo in SVG, EPS or AI format?  
* [x] Does your logo clearly state the name of the product/project and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [ ] If your product/project is open source, did you include the `repo_url`?
* [x] Did you copy and paste the [installation and configuration instructions](https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions) into the README.md file in addition to linking to them?

### CODE REVIEW

**Comment by taylorwaggoner** [comment]
@AlexDiamanti thanks for submitting.  I wanted to check in with you regarding the naming of this product.  We currently have your product named "Diamanti-DXX" [on the landscape](https://landscape.cncf.io/format=card-mode&selected=diamanti-dxx). Your participation agreement is for D20.  Is this the same product/code?  Has it been renamed?  Thanks

**Comment by AlexDiamanti** [comment]
Hi,

Brian is our VP of Product.  

Brian, can you answer that?  

Thanks, 
Alex Bahel


> On Jun 5, 2020, at 3:04 PM, Taylor Waggoner <notifications@github.com> wrote:
> 
> 
> @AlexDiamanti <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_AlexDiamanti&d=DwMCaQ&c=euGZstcaTDllvimEN8b7jXrwqOf-v5A_CdpgnVfiiMM&r=cMdCQBus12cbDoqUVPY7wgVlNerotS4XoMKCxdag4_Y&m=ailslmsCKQwSucn9kBSykGZHSJuIusuzg_exxmW4Bi4&s=5lmw9VU2qGlaOPlN1pMqDAUif5ero02Akhnt-wJutLU&e=> thanks for submitting. I wanted to check in with you regarding the naming of this product. We currently have your product named "Diamanti-DXX" on the landscape <https://urldefense.proofpoint.com/v2/url?u=https-3A__landscape.cncf.io_format-3Dcard-2Dmode-26selected-3Ddiamanti-2Ddxx&d=DwMCaQ&c=euGZstcaTDllvimEN8b7jXrwqOf-v5A_CdpgnVfiiMM&r=cMdCQBus12cbDoqUVPY7wgVlNerotS4XoMKCxdag4_Y&m=ailslmsCKQwSucn9kBSykGZHSJuIusuzg_exxmW4Bi4&s=BgZAsHLy3NMiNWDuYcxazbdZvxVOqwrHyU9G7Nna_6Y&e=>. Your participation agreement is for D20. Is this the same product/code? Has it been renamed? Thanks
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_cncf_k8s-2Dconformance_pull_985-23issuecomment-2D639851423&d=DwMCaQ&c=euGZstcaTDllvimEN8b7jXrwqOf-v5A_CdpgnVfiiMM&r=cMdCQBus12cbDoqUVPY7wgVlNerotS4XoMKCxdag4_Y&m=ailslmsCKQwSucn9kBSykGZHSJuIusuzg_exxmW4Bi4&s=PenRnxe0GmvE76yFp-iqc3VilIKXfo7NDwXRjNz_irU&e=>, or unsubscribe <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AJ2CMUQISTNM52EQTQ7BDMTRVFTV5ANCNFSM4NQELPTQ&d=DwMCaQ&c=euGZstcaTDllvimEN8b7jXrwqOf-v5A_CdpgnVfiiMM&r=cMdCQBus12cbDoqUVPY7wgVlNerotS4XoMKCxdag4_Y&m=ailslmsCKQwSucn9kBSykGZHSJuIusuzg_exxmW4Bi4&s=yW2CPExOxSc2Lld54xxe2gon0UWZYIxC1iHD7WofiDc&e=>.
> 
>  
> This email has been scanned for spam and viruses by Proofpoint Essentials. Click here <https://us5.proofpointessentials.com/index01.php?mod_id=11&mod_option=logitem&mail_id=1591394655-R09aP84Dum7M&r_address=alex%40diamanti.com&report=1> to report this email as spam.
> 


-- 
Diamanti Email Disclaimer: This email and any files transmitted with it are 
confidential and intended solely for the use of the individual or entity to 
whom they are addressed. If you have received this email in error, please 
delete it immediately.

**Comment by taylorwaggoner** [comment]
@AlexDiamanti - are we replacing the Diamanti-DCX files with the Diamanti Spektra files?  Or are the Spektra files in addition to to Diamanti-DCX?  In other words, are you only trying to certify Spektra going forward? Thanks!

**Comment by AlexDiamanti** [comment]
I’m going to replace the folder Diamanti-DCX to Diamanti-Spektra and in PRODUCT.yaml name to Diamanti-Spektra.

> On Jun 9, 2020, at 1:57 PM, Taylor Waggoner <notifications@github.com> wrote:
> 
> 
> @AlexDiamanti <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_AlexDiamanti&d=DwMCaQ&c=euGZstcaTDllvimEN8b7jXrwqOf-v5A_CdpgnVfiiMM&r=cMdCQBus12cbDoqUVPY7wgVlNerotS4XoMKCxdag4_Y&m=Q_BP-pK40h2w5gIKvhRi5CbN-EXr7xFOkisCVqtFNX0&s=Vxq73-7SXoHNwxcjZszfhGVI7km2wpHD9FI2_qkVWko&e=> - are we replacing the Diamanti-DCX files with the Diamanti Spektra files? Or are the Spektra files in addition to to Diamanti-DCX? In other words, are you only trying to certify Spektra going forward? Thanks!
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_cncf_k8s-2Dconformance_pull_985-23issuecomment-2D641565456&d=DwMCaQ&c=euGZstcaTDllvimEN8b7jXrwqOf-v5A_CdpgnVfiiMM&r=cMdCQBus12cbDoqUVPY7wgVlNerotS4XoMKCxdag4_Y&m=Q_BP-pK40h2w5gIKvhRi5CbN-EXr7xFOkisCVqtFNX0&s=L-vLbJBwad-6RNBepvQ0L6MCUe4akUH-D47DGruzGAU&e=>, or unsubscribe <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AJ2CMUUIIRO6JSFHU3FYFBTRV2O23ANCNFSM4NQELPTQ&d=DwMCaQ&c=euGZstcaTDllvimEN8b7jXrwqOf-v5A_CdpgnVfiiMM&r=cMdCQBus12cbDoqUVPY7wgVlNerotS4XoMKCxdag4_Y&m=Q_BP-pK40h2w5gIKvhRi5CbN-EXr7xFOkisCVqtFNX0&s=bKKs2TWhaQ75HUUUrwvUO4U8Q8LZ2OlGHjWxGQLgTcU&e=>.
> 
>  
> This email has been scanned for spam and viruses by Proofpoint Essentials. Click here <https://us5.proofpointessentials.com/index01.php?mod_id=11&mod_option=logitem&mail_id=1591736238-MmjnIPHw7G_g&r_address=alex%40diamanti.com&report=1> to report this email as spam.
> 


-- 
Diamanti Email Disclaimer: This email and any files transmitted with it are 
confidential and intended solely for the use of the individual or entity to 
whom they are addressed. If you have received this email in error, please 
delete it immediately.

**Comment by AlexDiamanti** [comment]
I moved files from Diamanti-DCX to Diamanti-Spektra folder and updated name in PRODUCT.yaml to Diamanti-Spektra.

**Comment by taylorwaggoner** [comment]
Great thanks!  Do you want to add an updated product description to add[ to the landscape entry ](https://landscape.cncf.io/format=card-mode&selected=diamanti-dxx)for Spektra?  I will be renaming it in the landscape once I hear back from you.

**Comment by taylorwaggoner** [comment]
You are now Certified Kubernetes.  I have updated the name and description here: https://landscape.cncf.io/format=card-mode&organization=diamanti&selected=diamanti-spektra
Thanks!

**Pull request merged**
