### PR TITLE
Conformance results for v1.7/caasp (SUSE)

### PR DESCRIPTION
**Pull request by mjura**
vendor: SUSE
name: SUSE CaaS (Container as a Service) Platform
version: v2.0
website_url: https://www.suse.com/products/caas-platform/
documentation_url: https://www.suse.com/betaprogram/caasp-beta/doc-quickstart/
product_logo_url: https://www.suse.com/brandcentral/img/suse/logo-primary.png

### CODE REVIEW

**Comment by mjura** [comment]
I used this PR for testing https://github.com/cncf/k8s-conformance/pull/24

**Comment by kbarnard10** [comment]
@mjura Could you double-check your version.txt file. It should look like this: https://github.com/mml/k8s-conformance/blob/744639d2527eebddba13b0ec87047a5ec00f1b76/v1.8/gke/version.txt

**Comment by mjura** [comment]
@kbarnard10: thank you for pointing this, I updated `version.txt` file

**Comment by kbarnard10** [comment]
Perfect, thank you! +1

**Comment by mjura** [comment]
We have updated link to our logo in `PRODUCT.yaml` file
product_logo_url: https://www.suse.com/brandcentral/img/suse/logo-primary.png

**Comment by ajaeger** [comment]
Thanks, @mjura . LGTM.

**Pull request merged**
