### PR TITLE
Conformance results for v1.9/rackspace-openstack

### PR DESCRIPTION
**Pull request by jnoller**
vendor: Rackspace
name: Rackspace Kubernetes-as-a-Service
version: 1.1.0
website_url: https://www.rackspace.com/managed-kubernetes
documentation_url: https://developer.rackspace.com/docs/rkaas/1.0.x/
product_logo_url: http://caa48e96f11ddd896e56-cbd62a0ad7e2d388825529106f960d1e.r78.cf2.rackcdn.com/RackspaceLogoManagedCloud.eps

### CODE REVIEW

**Comment by kbarnard10** [comment]
@jnoller Can you check the version.txt file, looks like major and minor of the server version are missing.

**Comment by dankohn** [comment]
And please provide an SVG logo.

**Comment by jnoller** [comment]
@kbarnard10 We have a 1.9.6 build with some cherry picked backports for the subPath CVE and another patch that resolves slow volume disconnect/reconnect on failover. It seems when we built the hyperkube image we missed an environment variable. Is that 100% required for this?

**Comment by jnoller** [comment]
@dankohn Sorry - I missed that in the instructions. They note that .eps logos are OK so I have changed the URL to the .eps version of the logo

**Comment by dankohn** [comment]
Yes, we're using the instructions from https://github.com/cncf/k8s-conformance/blob/master/reviewing.md to review. So, please fix the version.txt file.

**Comment by jnoller** [comment]
@dankohn @kbarnard10 The logo and the Major/Minor version issues have been fixed. Please take a look

**Comment by taylorwaggoner** [comment]
You are now Certified Kubernetes
https://github.com/cncf/landscape/pull/711

**Comment by jnoller** [comment]
WOOOOOOOO 🎉

**Pull request merged**
