### PR TITLE
Conformance results for v1.13/puppetlabs-kubernetes

### PR DESCRIPTION
**Pull request by davejrt**

### CODE REVIEW

**Comment by taylorwaggoner** [comment]
@davejrt thank you for submitting!  There are a couple of things that need to happen before we can certify you.  
- Please send in a signed [participation form](https://github.com/cncf/k8s-conformance/tree/master/participation-form) 
- Your e2e.log results are showing failed - please review and update PR with results that pass the tests
- Small thing, but your vendor name in the PRODUCT file has an extra "p".  (Pupppet)
- I also wanted to check with you regarding your description.  This is a description that will show on your product's entry in the [Cloud Native Landscape](https://landscape.cncf.io/category=certified-kubernetes-distribution,certified-kubernetes-hosted,certified-kubernetes-installer,special&format=card-mode&grouping=category), so feel free to add more detail if you'd like

Let me know if you have any questions!  Thanks!

**Comment by davinhanlon** [comment]
Hi @taylorwaggoner . I submitted the participation form via DocuSign. Let me know if any further clarification is needed. Thanks!

**Comment by davejrt** [comment]
Hi @taylorwaggoner all of your initial feedback has been addressed by myself and @davinhanlon

**Comment by taylorwaggoner** [comment]
You are now Certified Kubernetes
https://landscape.cncf.io/format=card-mode&selected=puppetlabs-kubernetes

**Comment by davinhanlon** [comment]
Thanks @taylorwaggoner - appreciate the assistance on this! Minor point: Puppet is open source and the Kubernetes module which has been certified as part of this process is also open source. Therefore, can we be updated to be open source, so that the card is not greyed out? Let me know if you've any questions on this. Thanks!

**Comment by dankohn** [comment]
Updated to show as open source, thanks: https://landscape.cncf.io/format=card-mode&grouping=organization&organization=puppet&selected=puppetlabs-kubernetes

**Comment by davinhanlon** [comment]
Thanks @dankohn, appreciated !

**Pull request merged**
