### PR TITLE
Conformance results for v1.17/cke

### PR DESCRIPTION
**Pull request by yokaze**
Signed-off-by: Daichi Sakaue <daichi-sakaue@cybozu.co.jp>

### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [x] If this is a new entry, have you submitted a signed [participation form](https://github.com/cncf/k8s-conformance/tree/master/participation-form)?
* [x] Did you include the product/project logo in SVG, EPS or AI format?  
* [x] Does your logo clearly state the name of the product/project and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [x] If your product/project is open source, did you include the `repo_url`?
* [x] Did you copy and paste the [installation and configuration instructions](https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions) into the README.md file in addition to linking to them?

### CODE REVIEW

**Comment by taylorwaggoner** [comment]
@yokaze thanks for submitting. The results look great!  We've recently been tightening our [requirements for the README file](https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions).  Could you please make sure that all relevant installation, provisioning, or configuration instructions are pasted into the README? We're trying to provide step by step guidance so that your customers can later validate your conformance if they wish to. Thanks!

**Comment by yokaze** [comment]
Hi @taylorwaggoner, thanks for the information!

I understand your policy, however we could not find which link you are concerning.
Our README only includes links to instructions for Sonobuoy, Docker CE, and Go.
Do you mean we need to remove these links?

We also checked other recent PRs and found that Docker and Go are assumed to be installed implicitly.
Can we omit these steps from the README?

**Comment by taylorwaggoner** [comment]
@yokaze it's fine to keep those links in the PR.  I included that README link in order to convey that we are looking for detailed, step by step instructions, so that customers can easily replicate your conformance results if they want to. Are there any additional instructions you can paste into the README for installing your product or how to provision a cluster? Thanks!

**Comment by yokaze** [comment]
@taylorwaggoner thanks to the comment.
I have slightly changed the documentation to improve clarity. 
Customers can easily replicate the conformance result, if docker and Go are installed in their environments.

**Comment by taylorwaggoner** [comment]
You are now Certified Kubernetes

**Pull request merged**
