### PR TITLE
Conformance results for v1.17/agorakube

### PR DESCRIPTION
**Pull request by pierreilki**
Conformance results for v1.17/agorakube

### CODE REVIEW

**Comment by taylorwaggoner** [comment]
@pierreilki, thanks for submitting! Before I can certify, please copy and paste the instructions to install into the README, rather than linking to a URL. Thanks!

**Comment by pierreilki** [comment]
Hi @taylorwaggoner,
Thanks for your review ! We added the instructions to install Agorakube into the README file.

**Comment by taylorwaggoner** [comment]
You are now Certified Kubernetes

**Comment by pierreilki** [comment]
Hi @taylorwaggoner 
Thank you !

**Pull request merged**
