### PR TITLE
Conformance results for v1.16/roost

### PR DESCRIPTION
**Pull request by sudhirjangir**
### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [x] If this is a new entry, have you submitted a signed [participation form](https://github.com/cncf/k8s-conformance/tree/master/participation-form)?
* [x] Did you include the product/project logo in SVG, EPS or AI format?  
* [x] Does your logo clearly state the name of the product/project and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [ ] If your product/project is open source, did you include the `repo_url`?
* [x] Did you copy and paste the [installation and configuration instructions](https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions) into the README.md file in addition to linking to them?

### CODE REVIEW

**Comment by taylorwaggoner** [comment]
@sudhirjangir can you please provide a bit more detail about creating/configuring a cluster?  We want to make sure that someone can easily re-create your test results if they wanted to.  More info here: https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions
Thanks!

**Comment by sudhirjangir** [comment]
I can see those details:
https://github.com/cncf/k8s-conformance/pull/1076/commits/4dbbbc7a949da4462fd37787b9e815258f86c857#diff-71823485f5904cbf76e5ed3487116a2cR7-R14

**Comment by taylorwaggoner** [comment]
> Once ZKE cluster is up and running

Are there any steps that you can add to show how to get the cluster up and running?  Any configuration needed? Thanks!

**Comment by mgdevstack** [comment]
Thanks for reviewing @taylorwaggoner. 

README.md for all three PRs https://github.com/cncf/k8s-conformance/pull/1076 , https://github.com/cncf/k8s-conformance/pull/1075, https://github.com/cncf/k8s-conformance/pull/1074 are updated with detailed information abut ZKE cluster configuration and its status.

**Comment by taylorwaggoner** [comment]
You are now Certified Kubernetes
https://landscape.cncf.io/format=card-mode&organization=zettabytes&selected=roost-desktop

**Pull request merged**
