### PR TITLE
Conformance results for kubernetes v1.22/swisscom-kubernetes-service

### PR DESCRIPTION
**Pull request by adamisworking**
### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [ ] If this is a new entry, have you submitted a signed [participation form](https://github.com/cncf/k8s-conformance/tree/master/participation-form)?
* [ ] Did you include the product/project logo in SVG, EPS or AI format?  
* [ ] Does your logo clearly state the name of the product/project and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)? "Feel free to use the Swisscom logo from the landscape"
* [ ] If your product/project is open source, did you include the `repo_url`?
* [x] Did you copy and paste the [installation and configuration instructions](https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions) into the README.md file in addition to linking to them?

### CODE REVIEW

**Comment by Riaankl** [comment]
@adamisworking we are helping with the automation of the K8-conformance check, noticed your PR fail because of the title.
Re-titled to the correct form. Hope that is helpful for you.
You would have to rebase and squash with git rebase -i HEAD (https://git-scm.com/docs/git-rebase) though

**Comment by adamisworking** [comment]
@Riaankl Thanks i'll try to rebase it now. However i don't understand the bot's errors , the first 2 actually :/

**Comment by Riaankl** [comment]
Let me explain and if the user experience need to be updated let me know:

`the Kubernetes release version in the title () and folder structure (v1.22) don't match`
Your files are in folder v1.22, but your PR title state 1.22.15 - miss matched.

`title must be formatted like 'Conformance results for [KubernetesReleaseVersion]/[ProductName]' (e.g: Conformance results for v1.23/CoolKubernetes)`
The PR title need to be `KubernetesReleaseVersion]/[ProductName` there for `v1.22/swisscom-kubernetes-service` and not  `kubernetes 1.22.15`

Sorry, I missed the at first glance: 
`unable to use version 'v1.22' because it is older than the last currently supported release (v1.23)` 
The policy only allow for current release minus 2 releases for conformance. You can submit for v1.23, v1.24, & v1.25. And when the release is cut in two days v1.23 would not be supported either.

And then the rebase issue, but that should be clear.

**Comment by adamisworking** [comment]
@Riaankl I tried to rebase using (git rebase -i HEAD~1). But it's not removing the error message. Is there something i'm doing wrong ?

**Comment by adamisworking** [comment]
@Riaankl Thanks for the explanations. I think it was just delayed, i was waiting for the bot to re-check. Yeah i know that the version is not supported by the checks but since it's my first time doing this , i wanted to train before publishing the results of v1.23 :)
But the rebase, it still complains about the number of commits :/

**Comment by Riaankl** [comment]
The rebase is not spesial in this repo.  Just normal git process.

**Comment by taylorwaggoner** [comment]
@adamisworking we're not accepting 1.22 submissions anymore. When you're ready, please submit for a more current version. thanks!

**Pull request closed without merging**
