### PR TITLE
Conformance results for v1.18/LIMA version 0.4.0 beta

### PR DESCRIPTION
**Pull request by Rania-Bojar**
### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [ ] If this is a new entry, have you submitted a signed [participation form](https://github.com/cncf/k8s-conformance/tree/master/participation-form)?
* [x] Did you include the product/project logo in SVG, EPS or AI format?  
* [x] Does your logo clearly state the name of the product/project and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [ ] If your product/project is open source, did you include the `repo_url`?
* [x] Did you copy and paste the [installation and configuration instructions](https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions) into the README.md file in addition to linking to them?

### CODE REVIEW

**Comment by Rania-Bojar** [comment]
Hello everybody,   
this Pull request was made on behalf of Kubernative GmbH. 
You are welcome to contact us for any inquieries.
Thank you

**Comment by amye** [comment]
Resolves https://github.com/cncf/k8s-conformance/pull/1383

**Comment by Rania-Bojar** [comment]
@idvoretskyi can you please tell me what is needed to be done to merge this request? Thank you in advance

**Comment by Rania-Bojar** [comment]
Hallo @amye, Hallo @idvoretskyi, can you please tell me what is yet requiered to get this request merged to the master Branch? I would be very grateful for your help and guidance.

best regards,
Rania.B

**Comment by idvoretskyi** [comment]
@Rania-Bojar I'll check this out, thanks for the ping.

**Comment by ErinThacker** [comment]
@idvoretskyi - has this been resolved?

**Comment by Rania-Bojar** [comment]
@ErinThacker is there anything i can do to move this request forward?

**Comment by idvoretskyi** [comment]
@ErinThacker yes, all good.

**Review by idvoretskyi — APPROVED** [review]

**Comment by Rania-Bojar** [comment]
@idvoretskyi Thank you for your contribution.

Hallo everyone, 
can you please assist us in moving on with this request to merge it? 
if there is anything Kubernative GmbH or i can do, please let me know.

thank you in advance
Rania.B

**Pull request merged**
