### PR TITLE
Add OSD v4.9 (1.22) conformance

### PR DESCRIPTION
**Pull request by jeefy**
### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [x] If this is a new entry, have you submitted a signed [participation form](https://github.com/cncf/k8s-conformance/tree/master/participation-form)?
* [x] Did you include the product/project logo in SVG, EPS or AI format?  
* [x] Does your logo clearly state the name of the product/project and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [x] If your product/project is open source, did you include the `repo_url`?
* [x] Did you copy and paste the [installation and configuration instructions](https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions) into the README.md file in addition to linking to them?

### CODE REVIEW

**Comment by taylorwaggoner** [comment]
You are now Certified Kubernetes

**Comment by taylorwaggoner** [comment]
This one shouldn't have been merged just yet @caniszczyk 

@jeefy we'll have to resolve the not-verifiable tag

Apologies for getting a bit ahead of myself here!

**Comment by jeefy** [comment]
All good!

**Comment by Riaankl** [comment]
@jeefy I reverted the PR.
The reason for the `not-verifiable` tag is the the CNCFCI bot could not I dentivy the K8s version. 
Van you please resubmit the PR with `Add OSD 4.9 v1.22 conformance` as the title. (Else it is looking for K8s version 4.9)
Thanks!

**Pull request merged**
