### PR TITLE
Conformance results for v1.17/mirantis-docker-enterprise

### PR DESCRIPTION
**Pull request by jakolehm**
### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [x] If this is a new entry, have you submitted a signed [participation form](https://github.com/cncf/k8s-conformance/tree/master/participation-form)?
* [x] Did you include the product/project logo in SVG, EPS or AI format?  
* [x] Does your logo clearly state the name of the product/project and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [x] If your product/project is open source, did you include the `repo_url`?
* [x] Did you copy and paste the [installation and configuration instructions](https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions) into the README.md file in addition to linking to them?

### CODE REVIEW

**Comment by taylorwaggoner** [comment]
@jakolehm thanks for submitting.  The test results look great!  One quick thing - we're trying to ensure that the README files provide a detailed step by step process so that customers can replicate your conformance results if they wish.  Are there any additional instructions you could add to the README, perhaps the steps to deploy a cluster or installation directions from the link you included in step 4 (https://docs.docker.com/ee/ucp/admin/install/)?  More details about this are available here: https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions

Thanks!

**Comment by jakolehm** [comment]
@taylorwaggoner readme is now updated.

**Comment by taylorwaggoner** [comment]
The README looks great, thanks!  Last question for you - we need the product type (distribution, hosted platform, installer) as well as a product description.  We previously had this product listed as a distribution with this description:

> Included in Docker Enterprise, Docker Kubernetes Service (DKS) is a conformant Kubernetes distribution that is managed via CLI and the Docker Universal Control Plane.

If this will still work, please add them to the PRODUCT file. https://github.com/cncf/k8s-conformance/blob/master/instructions.md#productyaml

Thanks!

**Comment by jakolehm** [comment]
@taylorwaggoner Product.yaml now has type & description.

**Comment by taylorwaggoner** [comment]
You are now Certified Kubernetes
https://landscape.cncf.io/format=card-mode&organization=mirantis&selected=mirantis-docker-enterprise

**Pull request merged**
