### PR TITLE
Conformance results for v1.18/Diamanti-Spektra

### PR DESCRIPTION
**Pull request by AlexDiamanti**
### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [ ] If this is a new entry, have you submitted a signed [participation form](https://github.com/cncf/k8s-conformance/tree/master/participation-form)?
* [x] Did you include the product/project logo in SVG, EPS or AI format?  
* [x] Does your logo clearly state the name of the product/project and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [ ] If your product/project is open source, did you include the `repo_url`?
* [x] Did you copy and paste the [installation and configuration instructions](https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions) into the README.md file in addition to linking to them?

### CODE REVIEW

**Comment by AlexDiamanti** [comment]
Please, re-check everything. I updated check list and corrected name of the patch.  Product name should be fine (we recently did it for 1.16).

**Comment by AlexDiamanti** [comment]
Hi,

Please, re-check everything. I updated check list and corrected name of the patch. Product file should be fine (we recently did it for 1.16 for our version 3.0).

Thanks,
Alex

**Comment by taylorwaggoner** [comment]
@AlexDiamanti thanks for submitting.   A couple things here - please make sure that your product, junit, and e2elog files all go under your 1.18 directory for the product.  Also, if there are any more details you can provide about configuring a cluster (what to select, etc), please add them to the README.   Thanks!

**Comment by taylorwaggoner** [comment]
Thanks! You are now Certified Kubernetes

**Pull request merged**
