### PR TITLE
Conformance results for v1.16/wangsucloud

### PR DESCRIPTION
**Pull request by lij3**
### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [x] If this is a new entry, have you submitted a signed [participation form](https://github.com/cncf/k8s-conformance/tree/master/participation-form)?
* [x] Did you include the product/project logo in SVG, EPS or AI format?  
* [x] Does your logo clearly state the name of the product/project and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [x] If your product/project is open source, did you include the `repo_url`?
* [x] Did you copy and paste the [installation and configuration instructions](https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions) into the README.md file in addition to linking to them?

### CODE REVIEW

**Comment by lij3** [comment]
I have closed #1003, please help me check #1005.

**Comment by taylorwaggoner** [comment]
@lij3 the conformance test results look great. Before we can move forward with certification, please review your README file and if possible, add more instructions about how to create a cluster.  In your PR you say the following: 

> Log in to the WANGSU CLOUD dashboard to create a Kubernetes cluster.

Are there any specific steps one would need to take here?  Or any configuration needed?

Thanks!

**Comment by lij3** [comment]
@taylorwaggoner I have update README file, and add detailed instructions about how to create a cluster, also upload the reference picture.
Pls check.

**Comment by lij3** [comment]
@taylorwaggoner 
Hi, taylorwaggoner, our time is limited, we have to get the certification as soon as possibe, 
so, if you read this message, please reply me, thank you very much.

**Comment by lij3** [comment]
@taylorwaggoner Please see if any further information is needed. Thx

**Comment by taylorwaggoner** [comment]
You are now Certified Kubernetes

**Pull request merged**
