### PR TITLE
Conformance Results for v1.22/iks

### PR DESCRIPTION
**Pull request by Hansol-Jin**
### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [x] If this is a new entry, have you submitted a signed [participation form](https://github.com/cncf/k8s-conformance/tree/master/participation-form)?
* [x] Did you include the product/project logo in SVG, EPS or AI format?  
* [x] Does your logo clearly state the name of the product/project and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [ ] If your product/project is open source, did you include the `repo_url`?
* [x] Did you copy and paste the [installation and configuration instructions](https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions) into the README.md file in addition to linking to them?

### CODE REVIEW

**Comment by taylorwaggoner** [comment]
@Hansol-Jin thanks for submitting.  Have you sent in a [participation form](https://github.com/cncf/k8s-conformance/tree/master/participation-form) yet for this product?

Also, your product logo [cannot use the Kubernetes wheel](https://github.com/cncf/k8s-conformance/blob/master/faq.md#are-there-any-limitations-regarding-the-logo) - can you please provide a different logo and do not use that logo publicly going forward?  Alternatively, we can use [this logo](https://landscape.cncf.io/card-mode?organization=kinx&grouping=category&selected=kinx-member) and call your product KINX IXcloud Kubernetes Service.

Last, please add more details to your README about how on how to install and configure your Kubernetes implementation. The reason is that we need your users to be able to replicate the installation so that they can re-run the tests in the same environment and confirm that they get the same conformance results. 

Thanks!

**Comment by Hansol-Jin** [comment]
@taylorwaggoner Thank you for your feedback.
I will submit the participation form soon.
We changed the image of the logo from the existing URL.
And I added a manual link and detailed node spec for Kubernetes implementation to README.

**Comment by taylorwaggoner** [comment]
@Hansol-Jin thanks so much!  One last thing - the new logo you provided embeds a text element.  I was able to update it, but the font changed slightly.  Can you please let me know if this will work?  otherwise you will need to send me a new logo and make sure it doesn't have any errors here: https://autocrop.cncf.io/
ixcloud_kuber_logo (1)

**Comment by Hansol-Jin** [comment]
@taylorwaggoner,
We changed the image of the logo from the existing URL.
Please check it.

**Comment by Hansol-Jin** [comment]
@taylorwaggoner, I changed the README.

**Comment by taylorwaggoner** [comment]
You are now Certified Kubernetes
https://landscape.cncf.io/card-mode?organization=kinx&selected=i-xcloud-kubernetes-service

**Pull request merged**
