### PR TITLE
Conformance results for OpenShift v3.7 (Kube v1.7)

### PR DESCRIPTION
**Pull request by smarterclayton**
Code delivered to both OpenShift Online and OpenShift Container Platform
customers, as well as available to users via OpenShift Origin.

Note that my questions about version.txt in #6 are relevant here.

### CODE REVIEW

**Comment by kbarnard10** [comment]
Looks great, except as noted in #6, the minor client (8+) and server (7) versions don’t match. I will wait for a WG resolution of #6 to then +1 this pull request.

**Comment by kbarnard10** [comment]
@smarterclayton Based on the resolution to #6, and the new [review guidelines](https://github.com/cncf/k8s-conformance/blob/master/reviewing.md), can you update so that client version matches the conformance version?

**Comment by smarterclayton** [comment]
Updated

**Comment by kbarnard10** [comment]
+1

**Comment by WilliamDenniss** [comment]
@smarterclayton, a reminder that to make the first wave of certifications next week you need to have your company's participation form submitted and verified ASAP.

**Comment by kbarnard10** [comment]
Updated label to confirm we have the signed participation form.

**Pull request merged**
