### PR TITLE
Conformance results for v1.20/inspur-iop-arm64

### PR DESCRIPTION
**Pull request by jwz-ecust**
### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [ ] If this is a new entry, have you submitted a signed [participation form](https://github.com/cncf/k8s-conformance/tree/master/participation-form)?
* [ ] Did you include the product/project logo in SVG, EPS or AI format?  
* [ ] Does your logo clearly state the name of the product/project and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [ ] If your product/project is open source, did you include the `repo_url`?
* [ ] Did you copy and paste the [installation and configuration instructions](https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions) into the README.md file in addition to linking to them?

### CODE REVIEW

**Comment by jwz-ecust** [comment]
Hi! 
 @cncf-ci indicates that the pr missed the test ([sig-api-machinery] Secrets should patch a secret [Conformance]). However, I carefully examine the e2e.log and junit_01.xml and compare with other merged conformance tests. I found the missing test actually exists in my pr. 
Another situation is that I don't find any suitable conformance image for arm64 and k8s 1.20. Therefore, the image for arm64 was built according to the [guidance](https://github.com/jwz-ecust/kubernetes/tree/master/cluster/images/conformance). I compare the official conformance image and built image, there are some differences. Some tests in official conformance images are not included in built image. Also, some tests in built image are not existing in official image. I think this may be a possible reason of making pr unpassed.

@ErinThacker @hh  Could you check out this and give some advices? Thanks！

**Comment by jwz-ecust** [comment]
Hi! 
 @cncf-ci indicates that the pr missed the test ([sig-api-machinery] Secrets should patch a secret [Conformance]). However, I carefully examine the e2e.log and junit_01.xml and compare with other merged conformance tests. I found the missing test actually exists in my pr. 
Another situation is that I don't find any suitable conformance image for arm64 and k8s 1.20. Therefore, the image for arm64 was built according to the [guidance](https://github.com/jwz-ecust/kubernetes/tree/master/cluster/images/conformance). I compare the official conformance image and built image, there are some differences. Some tests in official conformance images are not included in built image. Also, some tests in built image are not existing in official image. I think this may be a possible reason of making pr unpassed.

@ErinThacker @hh  Could you check out this and give some advices?

**Comment by bernokl** [comment]
I am concerned with the differences in the tests and numbers. 
We would need the same suite of conformance tests to run on arm for this to pass.

I do see k8s.gcr.io/conformance-arm64:v1.20.0

**Comment by bernokl** [comment]
Thats not great. 
I see k8s.gcr.io/conformance-arm64:v1.21.0 is ARM, so intent is to have an ARM based version of 1.20 I am sure.
I do not know anything about these images, but we can look into the build process to see why they produced an AMD version.

**Comment by bernokl** [comment]
There appears to be a known issue with the 1.19 and 1.20 images. https://github.com/kubernetes/kubernetes/issues/102315 
I have raised it in the [sig-release](https://kubernetes.slack.com/archives/C2C40FMNF) slack channel.

If you have suggestions on resolution or would like to be part of the conversation please join in.

**Comment by taylorwaggoner** [comment]
@jwz-ecust @bernokl updates here?

**Comment by bernokl** [comment]
I see [kubernetes/kubernetes#102315 ](https://github.com/kubernetes/kubernetes/issues/102315) has been closed.
in #sig-release 
@BenTheElder suggested:
[you can also just do make WHAT='cmd/kubectl test/e2e/e2e.test vendor/github.com/onsi/ginkgo/ginkgo' and run the test binary yourself w/o sonobuoy](https://kubernetes.slack.com/archives/C2C40FMNF/p1625117370416400?thread_ts=1625090675.413800&cid=C2C40FMNF )
I think that sounds like a reasonable next step

**Comment by taylorwaggoner** [comment]
We are not certifying for 1.20 anymore, so please re-submit for 1.21 or higher when ready. thanks!

**Pull request closed without merging**
