### PR TITLE
Conformance results for v1.10/Cloud66 Maestro

### PR DESCRIPTION
**Pull request by khash**

### CODE REVIEW

**Comment by dankohn** [comment]
Fantastic, thanks. (@taylorwaggoner will review soon.)

**Comment by taylorwaggoner** [comment]
@khash thanks for submitting!  There are a few things that need resolved before we can certify.  First, please make sure to send in a signed participation form - https://github.com/cncf/k8s-conformance/tree/master/participation-form

In the PRODUCT.yaml file, please indicate which type of product you are certifying (distribution, hosted, installer), as well as provide a link to your logo that also includes your product or company name.  https://github.com/cncf/k8s-conformance/blob/master/instructions.md#productyaml

Lastly, we don't require a version.txt file anymore, so please feel free to delete.

Thanks!

**Comment by khash** [comment]
Thank you @taylorwaggoner 

Made the required changed.

**Comment by khash** [comment]
Thank you @taylorwaggoner 

I've sent the signed agreement to @dankohn

**Comment by taylorwaggoner** [comment]
You are now Certified Kubernetes.  We've classified Maestro as a distribution, but if you are confident that it should be under hosted, please email us at conformance@cncf.io.  
https://github.com/cncf/landscape/pull/852

**Comment by khash** [comment]
Thank you @taylorwaggoner for your help on this. I think you made the right call on distrubutiuon.

When will we see it appear here as certified? https://landscape.cncf.io/grouping=landscape&landscape=certified-kubernetes-distribution,special

**Comment by taylorwaggoner** [comment]
You'll see it on the landscape once this PR gets merged, probably later today or early tomorrow: https://github.com/cncf/landscape/pull/852

**Pull request merged**
