### PR TITLE
Conformance results for v1.24/qbo

### PR DESCRIPTION
**Pull request by alexeadem**
### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [x] If this is a new entry, have you submitted a signed [participation form](https://github.com/cncf/k8s-conformance/tree/master/participation-form)?
* [x] Did you include the product/project logo in SVG, EPS or AI format?  
* [x] Does your logo clearly state the name of the product/project and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [x] If your product/project is open source, did you include the `repo_url`?
* [x] Did you copy and paste the [installation and configuration instructions](https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions) into the README.md file in addition to linking to them?

### CODE REVIEW

**Comment by taylorwaggoner** [comment]
@alexeadem thanks for submitting!  Could you tell me a bit more about this?  Is this a distribution you created as an individual?

**Comment by alexeadem** [comment]
Hi @taylorwaggoner yes QBO home edition is created as individual under my github repo alexeadem and it is free to use.

**Comment by alexeadem** [comment]
Hi Is there anything else you need to get qbo certified? Thanks.

**Comment by Riaankl** [comment]
> 14 of 15 requirements have passed. Please review the following:
> 
> * [FAIL] it appears that there is not exactly one commit. Please rebase and squash with `git rebase -i HEAD` (https://git-scm.com/docs/git-rebase)
>   
>   * more than one commit was found, only one commit is allowed.
> 
> for a full list of requirements, please refer to these sections of the docs: [_content of the PR_](https://github.com/cncf/k8s-conformance/blob/master/instructions.md#contents-of-the-pr), and [_requirements_](https://github.com/cncf/k8s-conformance/blob/master/instructions.md#requirements).





To clear the last error and remove the `not-verifiable` label you could rebase and squash with `git rebase -i HEAD` (https://git-scm.com/docs/git-rebase)

**Pull request closed without merging**
