### PR TITLE
Conformance results for v1.16/baiducloud

### PR DESCRIPTION
**Pull request by tizhou86**
vendor: Baidu Cloud
name: Baidu Cloud Container Engine
version: v1.16.3
website_url: https://cloud.baidu.com/product/cce.html
documentation_url: https://cloud.baidu.com/doc/CCE/index.html
product_logo_url: https://agroup-bos.cdn.bcebos.com/b13cca62ab2549a75217d17c44fd0f22670f7edc

### CODE REVIEW

**Comment by taylorwaggoner** [comment]
@tizhou86, results look great!  Before I can certify, please copy and paste the instructions into your README.md rather than link to the URLs that include the instructions.  Thanks!

**Comment by tizhou86** [comment]
@taylorwaggoner We are currently working on the English version of those instructions, it might take a while to finish, and I don't think it's proper to paste the instructions in Chinese into README file, so can you merge this pr and I'll make it happen in our next conformance result?

**Comment by dankohn** [comment]
Please paste them into the Readme in Chinese.

**Comment by taylorwaggoner** [comment]
@tizhou86 wanted to check in on this - can you paste the instructions in Chinese?

Thanks!

**Comment by taylorwaggoner** [comment]
@tizhou86 , just checking in!  Let us know if you have any questions!

**Comment by taylorwaggoner** [comment]
@tizhou86 , checking in again!  Please let us know if we should close out this PR or if you plan to update. Thanks!

**Comment by tizhou86** [comment]
@taylorwaggoner Hi Taylor, we've recently updated our instructions in English, I'll paste the instructions in PR today, thanks!

**Comment by tizhou86** [comment]
@taylorwaggoner Hi Taylor, I've just added the instructions into the README file, thanks!

**Comment by taylorwaggoner** [comment]
Thanks!  You are now Certified Kubernetes

**Pull request merged**
