### PR TITLE
Rafay v1.19 and V1.20 

### PR DESCRIPTION
**Pull request by vishalk-rafay**
### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [ ] If this is a new entry, have you submitted a signed [participation form](https://github.com/cncf/k8s-conformance/tree/master/participation-form)?
* [x] Did you include the product/project logo in SVG, EPS or AI format?  
* [x] Does your logo clearly state the name of the product/project and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [ ] If your product/project is open source, did you include the `repo_url`?
* [x] Did you copy and paste the [installation and configuration instructions](https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions) into the README.md file in addition to linking to them?

### CODE REVIEW

**Comment by vishalk-rafay** [comment]
> This request is not yet verifiable, please confirm that your supporting files are in the correct folder.

The supporting files are part of the each release folder.

**Comment by vishalk-rafay** [comment]
> This request is not yet verifiable, please confirm that your e2e logs reference the release you are submitting for

yes the e2e log references each release for which I have submitted the results

**Comment by Riaankl** [comment]
@vishalk-rafay only one release can be done per PR. Hope that help.

**Comment by vishalk-rafay** [comment]
> @vishalk-rafay only one release can be done per PR. Hope that help.

Thanks, @Riaankl will raise different PR's individually.

**Pull request closed without merging**
