### PR TITLE
Conformance results from v1.9/neuvector

### PR DESCRIPTION
**Pull request by andsont**

### CODE REVIEW

**Comment by taylorwaggoner** [comment]
Membership in CNCF needed.  Please reach out to memberships@cncf.io

**Comment by philips** [comment]
Briefly reading through the neuvector website is this similar to the situation in https://github.com/cncf/k8s-conformance/pull/117 @dankohn ?

**Comment by dankohn** [comment]
Thanks for the heads up @philips .

@andsont the CNCF Certified Kubernetes process is designed for distributions and platforms of Kubernetes (as defined in  https://github.com/cncf/k8s-conformance/blob/master/faq.md). We will soon be discussing a possible certification process for security and other third-party add-ons, but the existing conformance suite is not designed for them.

Could you please confirm that I can close this PR, and please join the mailing list where we'll be discussing new conformance programs.

**Comment by andsont** [comment]
Hi Dan,

Please go ahead to close this PR.
Thanks for the information.

Andson

**Comment by dankohn** [comment]
Great, please look for my email on the mailing list next week.

**Comment by andsont** [comment]
cool. Looking forward for the mailing list next week.

Andson

**Pull request closed without merging**
