### PR TITLE
Add conformance results for v1.15/fury-distribution

### PR DESCRIPTION
**Pull request by angelbarrera92**
### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [X] If this is a new entry, have you submitted a signed [participation form](https://github.com/cncf/k8s-conformance/tree/master/participation-form)?
* [X] Did you include the product/project logo in SVG, EPS or AI format?  
* [X] Does your logo clearly state the name of the product/project and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [X] If your product/project is open source, did you include the `repo_url`?
* [X] Did you copy and paste the [installation and configuration instructions](https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions) into the README.md file in addition to linking to them?

### CODE REVIEW

**Comment by taylorwaggoner** [comment]
Great thanks!  Can you confirm that there is a different code for the distribution than for the installer?  

Also, could we possibly name them Fury Distribution and Fury Installer, or something else to differentiate them?  We can't use the same name in the Cloud Native landscape.

Thanks!

**Comment by angelbarrera92** [comment]
> Great thanks! Can you confirm that there is a different code for the distribution than for the installer?

Hi @taylorwaggoner 
Yes I can confirm we have different code for installer and distribution :)

> Also, could we possibly name them Fury Distribution and Fury Installer, or something else to differentiate them? We can't use the same name in the Cloud Native landscape.
> 
> Thanks!

I force pushed a new change to rename fury -> **Fury Distribution**. Our installers will be named **Fury Installers**. 

Thanks for the feedback!

I will do the same with the 1.16 results ;)

**Comment by taylorwaggoner** [comment]
Great thanks!  In addition to linking to the cluster deployment instructions, can you please copy/paste them into the readme as well?  We're trying to ensure that all instructions to reproduce the results are included in the readme file.  Thanks!

**Comment by angelbarrera92** [comment]
> Great thanks! In addition to linking to the cluster deployment instructions, can you please copy/paste them into the readme as well? We're trying to ensure that all instructions to reproduce the results are included in the readme file. Thanks!

Hi @taylorwaggoner!

I've updated the documentation adding more details about how to reproduce the cluster. 
I think it should be enough but let me know if there is anything else we should include.

Added to both PR (1.15 and 1.16)

**Comment by jnardiello** [comment]
@taylorwaggoner Is Angel change enough? Can you be a bit more specific on what is missing (if anything) and how we can fix the PR?

Thanks a lot

**Comment by jnardiello** [comment]
Thanks @angelbarrera92 , @taylorwaggoner can you have a look now? We have updated the documentation according to your feedback. Thanks

**Comment by taylorwaggoner** [comment]
@angelbarrera92 @jnardiello , thank you!!  You are now Certified Kubernetes.
https://landscape.cncf.io/format=card-mode&organization=sighup

**Pull request merged**
