### PR TITLE
Conformance results for v1.7/tencentcloud

### PR DESCRIPTION
**Pull request by bonowang**
vendor: Tencent Cloud
name: Tencent Cloud Container Service
version: v1.7.8
website_url: https://cloud.tencent.com/product/ccs?lang=en
documentation_url: https://cloud.tencent.com/document/product/457?lang=en
product_logo_url: https://www.cncf.io/wp-content/uploads/2017/05/logo_tencent-300x184.png

### CODE REVIEW

**Comment by kbarnard10** [comment]
+1

**Comment by bonowang** [comment]
hi @kbarnard10， the participation-form i already send to conformance and William on Tuesday,do you want  me to cc the email to you?

**Comment by kbarnard10** [comment]
@bonowang If you could, that would be great. I'm keeping track of them all in one place.

**Comment by bonowang** [comment]
@kbarnard10 ok，can you tell me the your email?

**Comment by kbarnard10** [comment]
You can send to conformance@cncf.io

**Comment by dankohn** [comment]
Hi, @bonowang. Please email conformance@cncf.io as mentioned at https://github.com/cncf/k8s-conformance/blob/master/participation-form/Certified_Kubernetes_Form.md

**Comment by bonowang** [comment]
ok, i will resend the email again

**Comment by YuxiJin-tobeyjin** [comment]
I've tried on ccs,conformance result is ok. Very lgtm.

**Pull request merged**
