### PR TITLE
Conformance results for v1.23/nirmata

### PR DESCRIPTION
**Pull request by sidjain87**
### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [x] If this is a new entry, have you submitted a signed [participation form](https://github.com/cncf/k8s-conformance/tree/master/participation-form)?
* [x] Did you include the product/project logo in SVG, EPS or AI format?  
* [x] Does your logo clearly state the name of the product/project and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [x] If your product/project is open source, did you include the `repo_url`?
* [x] Did you copy and paste the [installation and configuration instructions](https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions) into the README.md file in addition to linking to them?

### CODE REVIEW

**Comment by sidjain87** [comment]
@taylorwaggoner Hi,  I don't see this merged yet. I closed the pull request with  the conformance tests results last week.  It it possible for you to check why its not merged yet ?

**Comment by taylorwaggoner** [comment]
@sidjain87 it looks like you closed this PR five days ago.  Please reopen if you wish for us to review. thanks!

**Comment by sidjain87** [comment]
@taylorwaggoner  Thanks! Reopening the pull request.

**Comment by taylorwaggoner** [comment]
You are now Certified Kubernetes

**Pull request merged**
