### PR TITLE
Conformance results for v1.7/nirmata

### PR DESCRIPTION
**Pull request by patelrit**
vendor: Nirmata, Inc.
name: Nirmata Managed Kubernetes
version: v1.7.9
website_url: https://www.nirmata.com/
documentation_url: https://docs.nirmata.io/en/latest/Clusters.html#create-a-new-kubernetes-cluster
product_logo_url: http://www.nirmata.com/wp-content/uploads/2017/05/logo-white.png

### CODE REVIEW

**Comment by kbarnard10** [comment]
Could you please add a subdirectory to your PR that reflects the version on Kubernetes for which conformance is being tested? 

Signed participation form needed. Please follow the instructions here to submit it: either via [PDF](https://github.com/cncf/k8s-conformance/blob/master/participation-form/Certified_Kubernetes_Form.pdf) or [DocuSign](https://na3.docusign.net/Member/PowerFormSigning.aspx?PowerFormId=ba08f93a-65ca-4c5d-8210-d5c858bb9208)

**Comment by patelrit** [comment]
The version of Kubernetes is in the version.txt file. 
Does it need to be in a subdirectory?

**Comment by dankohn** [comment]
Yes, that allows us to easily track which is certified for what version.

**Comment by patelrit** [comment]
Moved the files to the appropriate subdir.

**Pull request merged**
