### PR TITLE
CNCF-Inspur

### PR DESCRIPTION
**Pull request by graceinspur**

### CODE REVIEW

**Comment by taylorwaggoner** [comment]
@graceinspur thank you for submitting!  Before I can certify, please add a README.md file to the PR, per the required contents here:  https://github.com/cncf/k8s-conformance/blob/master/instructions.md#contents-of-the-pr

Also, please include a link to your company or product logo in the PRODUCT.yaml file, in either SVG, EPS or AI format, per the instructions here: https://github.com/cncf/k8s-conformance/blob/master/instructions.md#productyaml

Thank you!

**Comment by graceinspur** [comment]
About logo，Can we use my compony’s logo？

 

发件人: Taylor Waggoner [mailto:notifications@github.com] 
发送时间: 2018年9月18日 1:55
收件人: cncf/k8s-conformance <k8s-conformance@noreply.github.com>
抄送: Grace Jiang(姜亚楠) <jiangyanan@inspur.com>; Mention <mention@noreply.github.com>
主题: Re: [cncf/k8s-conformance] CNCF-Inspur (#327)

 

@graceinspur <https://github.com/graceinspur>  thank you for submitting! Before I can certify, please add a README.md file to the PR, per the required contents here: https://github.com/cncf/k8s-conformance/blob/master/instructions.md#contents-of-the-pr

Also, please include a link to your company or product logo in the PRODUCT.yaml file, in either SVG, EPS or AI format, per the instructions here: https://github.com/cncf/k8s-conformance/blob/master/instructions.md#productyaml

Thank you!

**Comment by dankohn** [comment]
You can definitely use your company logo, but we need you to send it as an
SVG, AI, or EPS file.
--
Dan Kohn <dan@linuxfoundation.org>
Executive Director, Cloud Native Computing Foundation https://www.cncf.io
+1-415-233-1000 https://www.dankohn.com

**Comment by graceinspur** [comment]
Ok，Thanks。

I have add readme and update product.yaml。

        Please review it thanks。

 

发件人: Dan Kohn [mailto:notifications@github.com] 
发送时间: 2018年9月18日 13:12
收件人: cncf/k8s-conformance <k8s-conformance@noreply.github.com>
抄送: Grace Jiang(姜亚楠) <jiangyanan@inspur.com>; Mention <mention@noreply.github.com>
主题: Re: [cncf/k8s-conformance] CNCF-Inspur (#327)

 

You can definitely use your company logo, but we need you to send it as an
SVG, AI, or EPS file.
--
Dan Kohn <dan@linuxfoundation.org <mailto:dan@linuxfoundation.org> >
Executive Director, Cloud Native Computing Foundation https://www.cncf.io
+1-415-233-1000 https://www.dankohn.com

**Comment by dankohn** [comment]
That logo unfortunately still isn't quite correct. Logo guidelines are at https://github.com/cncf/landscape/#logos

Can we use this logo, please?

**Comment by graceinspur** [comment]
[logo.zip](https://github.com/cncf/k8s-conformance/files/2391612/logo.zip)

**Comment by graceinspur** [comment]
This logo is OK？

http://www.inspur.com/eportal/fileDir/defaultCurSite/resource/cms/2018/09/2018091815294922673.svg

 

发件人: Dan Kohn [mailto:notifications@github.com] 
发送时间: 2018年9月18日 14:58
收件人: cncf/k8s-conformance <k8s-conformance@noreply.github.com>
抄送: Grace Jiang(姜亚楠) <jiangyanan@inspur.com>; Mention <mention@noreply.github.com>
主题: Re: [cncf/k8s-conformance] CNCF-Inspur (#327)

 

That logo unfortunately still isn't quite correct. Logo guidelines are at https://github.com/cncf/landscape/#logos

Can we use this logo, please?

**Comment by taylorwaggoner** [comment]
You are now Certified Kubernetes.
https://github.com/cncf/landscape/pull/841

**Pull request merged**
