### PR TITLE
Conformance results for v1.25/alvistack-ansible-collection-kubernetes

### PR DESCRIPTION
**Pull request by hswong3i**
The environment:
* Debian 11
* Kubernetes v1.25.0-rc.0
  * https://github.com/kubernetes/kubernetes/releases/tag/v1.25.0-rc.0
  * https://build.opensuse.org/package/show/home:alvistack/kubernetes-kubernetes-1.25.0-rc0
* CRI-O branch release-1.25
  * https://github.com/cri-o/cri-o/commit/1be8912631f446d3bfa75a034749de21c1cb5af8
  * https://build.opensuse.org/package/show/home:alvistack/cri-o-cri-o-1.25.0-rc0
* Cilium v1.12.0

Currently it is failed for 1 test case `[sig-network] HostPort validates that there is no conflict between pods with same hostPort but different hostIP and protocol [LinuxOnly] [Conformance]`. Maybe due to using Debian 11 as base OS (where I usually use Ubuntu 22.04 for testing). Error log also attached.

P.S. corresponding setup could work perfectly with Kubernetes v1.24.3, see https://github.com/cncf/k8s-conformance/commit/2a737c5c7d205982a8e710b1dd1b39ace4c47e6c

Signed-off-by: Wong Hoi Sing Edison <hswong3i@pantarei-design.com>

### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [X] If this is a new entry, have you submitted a signed [participation form](https://github.com/cncf/k8s-conformance/tree/master/participation-form)?
* [X] Did you include the product/project logo in SVG, EPS or AI format?  
* [X] Does your logo clearly state the name of the product/project and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [X] If your product/project is open source, did you include the `repo_url`?
* [X] Did you copy and paste the [installation and configuration instructions](https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions) into the README.md file in addition to linking to them?

### CODE REVIEW

**Comment by taylorwaggoner** [comment]
@hswong3i could you please close this until 1.25 is released later this month? thanks!

**Comment by hswong3i** [comment]
@taylorwaggoner my initial though was trigger the CI bot before v1.25.0 stable release, so we could prepare for changes if required. During v1.24.0 with https://github.com/cncf/k8s-conformance/pull/1958, we also face a bug for cncf-infra which need update according https://github.com/cncf-infra/prow-config/pull/77, so could this PR trigger something similar in advance?

BTW, it is now actually triggering an unexpected fail in conformance, which looks like related with https://github.com/kubernetes/kubernetes/pull/110640

Re-test with Ubuntu 22.04 but still failed: https://github.com/cncf/k8s-conformance/pull/2093/commits/9e75f135a8863dc527225bba976fbe0a0a3c15c5

**Comment by hswong3i** [comment]
Replace Cilium v1.12.0 with Flannel v0.19.1 then all conformance tests passed. I will report case with Cilium accordingly ;-)

**Comment by hswong3i** [comment]
@taylorwaggoner test result updated with Kubernetes 1.25.0 + Flannel + Sonobouy 0.56.10, from console output it show all passed.

@BobyMCbobs Do we also need to update the bot, as like as https://github.com/cncf/k8s-conformance/pull/1958 and https://github.com/cncf-infra/prow-config/pull/77?

**Comment by BobyMCbobs** [comment]
@hswong3i, https://github.com/cncf-infra/prow-config/pull/77 is regarding the output HTML interpolation of an error regarding junit_01.xml content parsing. That said, there appears to be an issue with v1.25. I'm currently investigating what's happening.

**Comment by hswong3i** [comment]
> @hswong3i, [cncf-infra/prow-config#77](https://github.com/cncf-infra/prow-config/pull/77) is regarding the output HTML interpolation of an error regarding junit_01.xml content parsing. That said, there appears to be an issue with v1.25. I'm currently investigating what's happening.

@BobyMCbobs thank you very much for your prompt reply, this was also why I start this PR 2 weeks ago since 1.25.0-rc.0, as per https://github.com/cncf/k8s-conformance/pull/2093#issuecomment-1213903229 which I had also faced similar experience during 1.24.0 initial release ;-)

**Comment by hswong3i** [comment]
@taylorwaggoner shall we also merge this PR, or any else missing?

**Comment by taylorwaggoner** [comment]
You are now Certified Kubernetes

**Pull request merged**
