### PR TITLE
Conformance results for v1.17/cloudboostr

### PR DESCRIPTION
**Pull request by miro-grapeup**
### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [ ] If this is a new entry, have you submitted a signed [participation form](https://github.com/cncf/k8s-conformance/tree/master/participation-form)?
* [X] Did you include the product/project logo in SVG, EPS or AI format?  
* [X] Does your logo clearly state the name of the product/project and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [ ] If your product/project is open source, did you include the `repo_url`?
* [X] Did you copy and paste the [installation and configuration instructions](https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions) into the README.md file in addition to linking to them?

### CODE REVIEW

**Comment by taylorwaggoner** [comment]
@miro-grapeup can you please look into the error message about missing tests?  Thanks!

**Comment by taylorwaggoner** [comment]
@miro-grapeup checking in on my last question thanks

**Comment by miro-grapeup** [comment]
@taylorwaggoner I have checked the error message.  I have rerun the tests with latest sonobuoy (v0.19.0). Hopefully it will help, but I can see the same final results as previously (with sonobuoy:v0.18.5):
```
SUCCESS! -- 278 Passed | 0 Failed | 0 Pending | 4565 Skipped
```

**Comment by miro-grapeup** [comment]
@taylorwaggoner hey, I have fixed the problem of missing additional flag that should be passed to the sonobouy.

**Comment by taylorwaggoner** [comment]
You are now Certified Kubernetes

**Pull request merged**
