### PR TITLE
Conformance results for v1.22/alvistack-vagrant-kubernetes

### PR DESCRIPTION
**Pull request by hswong3i**
### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [x] If this is a new entry, have you submitted a signed [participation form](https://github.com/cncf/k8s-conformance/tree/master/participation-form)?
* [x] Did you include the product/project logo in SVG, EPS or AI format?  
* [x] Does your logo clearly state the name of the product/project and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [x] If your product/project is open source, did you include the `repo_url`?
* [x] Did you copy and paste the [installation and configuration instructions](https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions) into the README.md file in addition to linking to them?

Fixes #1622

### CODE REVIEW

**Comment by taylorwaggoner** [comment]
@hswong3i we received your participation form for AlviStack Ansible Collection - Is this Vagrant product separate from that? If so we'll need a separate [participation form](https://github.com/cncf/k8s-conformance/tree/master/participation-form) sent in. Thanks!

**Comment by hswong3i** [comment]
> @hswong3i we received your participation form for AlviStack Ansible Collection - Is this Vagrant product separate from that? If so we'll need a separate [participation form](https://github.com/cncf/k8s-conformance/tree/master/participation-form) sent in. Thanks!

Dear @taylorwaggoner, thank you for clarify and signed version for this Vagrant Box Packaging send to [conformance@cncf.io](mailto:conformance@cncf.io).

**Comment by taylorwaggoner** [comment]
@hswong3i thanks!  Our [definition](https://github.com/cncf/k8s-conformance/blob/master/faq.md#what-is-a-distribution-hosted-platform-and-an-installer) of "installer" is:

> An installer downloads and then installs vanilla upstream Kubernetes.

Can you confirm that your product falls under this category based on this definition?

Thanks!

**Comment by hswong3i** [comment]
> A distribution is software based on Kubernetes that can be installed by an end user on to a public cloud or bare metal and includes patches to the upstream codebase.

AlviStack should be more suitable as distribution.

1. We package upstream Kubernetes as deb/rpm with additional patches, eg https://github.com/alvistack/kubernetes-kubernetes/commit/9691cada4d9658d3027ead2256a5edddeea88ab3
2. Then we build it with OBS for different supported OS, eg https://build.opensuse.org/package/show/home:alvistack/kubernetes-kubernetes-1.24.2
3. These deb/rpm could now install to a public cloud or bare metal, by OS native package manager, or by our Ansible Collection, eg https://github.com/alvistack/ansible-collection-kubernetes
4. With our Ansible Collection as Kubernetes distribution, beside Kubernetes we also manage the installation for CRI/CNI/CSI/Ingress/etc daily used components

From above design logic point of views, most likely we shouldn’t claim our production as a “vanilla upstream Kubernetes installer”?

**Comment by taylorwaggoner** [comment]
@hswong3i ok great!  Could you please change to distribution in your product.yaml file? Thanks!

**Comment by hswong3i** [comment]
@taylorwaggoner oh I guess you are asking about overall design logic but here we are talking about this vagrant box packaging product.yaml…

May I also have some more suggestion from community?
1. For AlviStack as Ansible Collection (our another serials), we are providing flexible installation and customization, for any bare metal or public cloud, so we classify it as distribution. Our reference target should be ‘kubespray’.
2. For AlviStack as Vagrant box packaging (here), we are providing a default out-of-the-box zero configuration self provisioning minimal Kubernetes in Vagrant box style, mainly target as CI foundation for testing other else Kubernetes addon DevOps development, so we classify it as installer. Our reference target should be ‘kind’.

It’s my pleasure if this Vagrant box packaging could also promote as distribution from community point of views, and it does provide some way out for override its default self provisioning behavior (e.g. as README.md here we could simply convert it from default single all-in-one instance into multiple master-node instances); but from end user point of view it looks like an installer for vanilla Kubernetes setup, rather than a distribution for daily usage in production?

**Comment by taylorwaggoner** [comment]
@hswong3i i discussed your products with our team and we've determined that both are installers. Does that work for you?

**Comment by hswong3i** [comment]
@taylorwaggoner I would like to looking for "distribution" for our "AlviStack as Ansible Collection", but keep "AlviStack as Vagrant box packaging" with "installer".

Although its original design reference was  kubespray (installer), but now a day it provide OS deb/rpm packaging as kubic (distribution), overall deployment management as microk8s (distribution) or k3s (distribution), and going to provide logging/monitoring/alert as OpenShift (distribution).

> A distribution is software based on Kubernetes that can be installed by an end user on to a public cloud or bare metal and includes patches to the upstream codebase.

Moreover, "AlviStack as Ansible Collection":
1. Design for end user self provisioning on their own public cloud or bare metal, for daily production
2. Provide additional patch release for Kubernetes/CRI/CNI/CSI if required, besides waiting for upstream official new release
3. Provide extra software and kubernetes addon management, e.g crun/conmon/skypeo/buildah/podman/etc

This make me feel more close to be "distribution" but not "installer"?

**Comment by hswong3i** [comment]
@taylorwaggoner seems membership fee well received, please kindly advice about next step?

> Maggie Cheung <mcheung@apac.linux.com>於2022年7月6日 19:53寫道：
>
﻿> Hi Francis,
>
> This is to confirm that payment is well-received from our end. 
>
> Thanks,
> Maggie

**Comment by taylorwaggoner** [comment]
You are now Certified Kubernetes

**Pull request merged**
