### PR TITLE
Conformance results for v1.11/aks-engine-azurestack, v1.12/aks-engine-azurestack, v1.13/aks-engine-azurestack and v1.14/aks-engine-azurestack

### PR DESCRIPTION
**Pull request by rjaini**
Conformance results on Azure Stack for 1.11, 1.12, 1.13 and 1.14 version

The changes includes:
1. Brand name change from ACS-engine to AKS-Engine
2. Certification for 1.11, 1.12, 1.13 and 1.14 K8s version.

### CODE REVIEW

**Comment by taylorwaggoner** [comment]
@rjaini, thanks for submitting.  A couple questions before we can certify.  We'll need to use a logo that has the company or product name on it.  Okay to use [this Azure logo](https://landscape.cncf.io/format=card-mode&selected=azure-aks-engine) that we used for AKS Engine?  Also, Azure Stack ACS Engine [is already certified for v1.11](https://docs.google.com/spreadsheets/d/1LxSqBzjOxfGx3cmtZ4EbB_BGCxT_wlxW_xgHVVa23es/edit#gid=0), so the results here are not needed.  Okay to delete?  Once you approve, I can go ahead and update the product name in the landscape and certify. Thanks!

**Comment by rjaini** [comment]
@taylorwaggoner : Yes you can use AKS Engine logo mentioned above. We know that v1.11 already certified. We submitted it again because we rename brand to Azure Stack AKS Engine (PR has changes with updated folder). I would like to have updated folder so that it becomes consistent. But I will leave that call to you folks if leaving old folder is OK then I don't mind getting it removed.

Just for FYI as per guidelines we have submitted new participation form as well for brand name change.

**Comment by dankohn** [comment]
Hi, you can't do a new certification for 1.11 because we only do certifications for the most recent 3 versions. However, you're welcome to do a PR that just edits the `PRODUCT.yaml` file of your existing submission to update the name and moves the directory where the files are located. See https://github.com/cncf/k8s-conformance/blob/master/faq.md#do-i-need-to-re-submit-results-if-we-rebrand-our-product

You can do that in the same PR where you're certifying more recent versions, or a different PR. 

While you're at it, could you please change the logo URL to https://landscape.cncf.io/logos/azure-aks-engine.svg as you're currently linking to a PNG of an obsolete version of the logo.

Thanks.

**Comment by rjaini** [comment]
Updated PR to address @dankohn comments.

**Comment by taylorwaggoner** [comment]
@rjaini thank you for making the updates.  One more item to address.  We need to update the repo for your product, but AKS Engine already uses https://github.com/Azure/aks-engine.  Unfortunately, the Landscape requires only one product can use a repo, not two.  Can you provide a new repo for AKS Engine for Azure Stack? Thanks!

**Comment by rjaini** [comment]
@taylorwaggoner : Updated website and doc URL.

**Comment by taylorwaggoner** [comment]
Thanks, @rjaini!  I've updated your listing in the [Cloud Native Landscape](https://landscape.cncf.io/format=card-mode&selected=aks-engine-for-azure-stack).

You are now Certified Kubernetes

**Pull request merged**
