### PR TITLE
Conformance Results for v1.18/Jdcloud

### PR DESCRIPTION
**Pull request by MaDongdong99**
### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [ ] If this is a new entry, have you submitted a signed [participation form](https://github.com/cncf/k8s-conformance/tree/master/participation-form)?
* [x] Did you include the product/project logo in SVG, EPS or AI format?  
* [x] Does your logo clearly state the name of the product/project and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [ ] If your product/project is open source, did you include the `repo_url`?
* [x] Did you copy and paste the [installation and configuration instructions](https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions) into the README.md file in addition to linking to them?

### CODE REVIEW

**Comment by taylorwaggoner** [comment]
@MaDongdong99 thanks for submitting.  Please remove the four 1.16 files from this PR so that it contains only the 1.18 results.  Also, please confirm that you have pasted in all cluster creation and configuration instructions, in addition to linking to the documentation.  More details available here https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions

Thanks!

**Comment by MaDongdong99** [comment]
hi @taylorwaggoner ,  thanks for reply.  1.16 files have been removed. And all the details of creating a kubernetes cluster on jdcloud are described on our website (https://docs.jdcloud.com/cn/jcs-for-kubernetes/create-to-cluster) which is mentioned in README. 
> @MaDongdong99 thanks for submitting. Please remove the four 1.16 files from this PR so that it contains only the 1.18 results. Also, please confirm that you have pasted in all cluster creation and configuration instructions, in addition to linking to the documentation. More details available here https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions
> 
> Thanks!

**Comment by taylorwaggoner** [comment]
@MaDongdong99 thank you for removing the 1.16 files.  For the cluster instructions, we require that you paste them into the README, as sometimes website links change.  Please see the link I sent in my last comment for why we require this.  Thanks!

**Comment by MaDongdong99** [comment]
hi @taylorwaggoner ,  I have added the detail steps for creating & connecting to a kubernets cluster on jdcloud into README. thanks

**Comment by taylorwaggoner** [comment]
Thank you!  You are now Certified Kubernetes

**Pull request merged**
