### PR TITLE
Conformance results for v1.24/KubeGien

### PR DESCRIPTION
**Pull request by KevinLiangX**
Signed-off-by: KevinLiangX <kevin.x.liang@foxmail.com>

vendor: GienTech
name: GienTech Kubernetes Platform (KubeGien)
version: v1.0
website_url: https://www.gientech.com
documentation_url: https://www.gientech.com/product/Basic-Runtime-Platform.html
product_logo_url: https://raw.githubusercontent.com/KevinLiangX/KubeGeinLogo/master/YQ-logo.svg
type: distribution
description: 'GienTech Kubernetes Platform (KubeGien) provides financial level, high availability, 
and high security container service platform. KubeGien fully follows the conformance with Kubernetes and is flexible to extend more other services with GienTech PAAS products.'

### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [ X] If this is a new entry, have you submitted a signed [participation form](https://github.com/cncf/k8s-conformance/tree/master/participation-form)?
* [ ✓] Did you include the product/project logo in SVG, EPS or AI format?  
* [ ✓] Does your logo clearly state the name of the product/project and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [ X] If your product/project is open source, did you include the `repo_url`?
* [ ✓] Did you copy and paste the [installation and configuration instructions](https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions) into the README.md file in addition to linking to them?

### CODE REVIEW

**Comment by taylorwaggoner** [comment]
@KevinLiangX thanks for submitting. Please make sure to submit a [signed participation form](https://github.com/cncf/k8s-conformance/tree/master/participation-form).  Additionally, we ask that the logo include the company or product name in English as well as any other language. More logo guidelines are available here: https://github.com/cncf/landscape#logos

Thanks!

**Comment by KevinLiangX** [comment]
@taylorwaggoner  thanks for your reply, we have discussed our platform logo issue. however, we got the message from company   of legal department that we just have the formal logo with chinese not english language. is it possible to submit with chinese logo this time .Waiting for the formal trademark registration successfully, we will update it.

**Comment by KevinLiangX** [comment]
@taylorwaggoner  Hi ,taylorwaggoner,How's it going for this.  is there any other issue need to check ?  i sent the form by email .

**Comment by taylorwaggoner** [comment]
You are now Certified Kubernetes 
We will use your company logo on the landscape until you have a logo with the product name in English. Thanks!

**Pull request merged**
