### PR TITLE
Conformance results for v1.19/cke

### PR DESCRIPTION
**Pull request by ymmt2005**
### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [x] If this is a new entry, have you submitted a signed [participation form](https://github.com/cncf/k8s-conformance/tree/master/participation-form)?
* [x] Did you include the product/project logo in SVG, EPS or AI format?  
* [x] Does your logo clearly state the name of the product/project and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [x] If your product/project is open source, did you include the `repo_url`?
* [x] Did you copy and paste the [installation and configuration instructions](https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions) into the README.md file in addition to linking to them?

### CODE REVIEW

**Comment by ymmt2005** [comment]
@taylorwaggoner
Hi.  cncf-ci bot added `evidence-missing` label which I don't understand.
Could you tell me what it is and what I should do?

Thank you!

**Comment by ymmt2005** [comment]
I think I find the problem.  I'd re-submit this after the problem is resolved.

**Comment by Riaankl** [comment]
> This conformance request has the correct list of tests present in the junit file but at least one of the tests in e2e.log failed

@taylorwaggoner  @ymmt2005 
When the CNCF-CI bot gives attach an 'evidence-missing' label is should also give a comment on the nature of the failure like in this example.
Please let me know if you need more information.

**Comment by ymmt2005** [comment]
@Riaankl @taylorwaggoner 
I identified that the problem was e2e flakiness fixed in https://github.com/kubernetes/kubernetes/pull/94968 .
CKE runs kube-proxy always in IPVS mode and hits this bug.

The bug has resolved for Kubernetes 1.20, but I want to get CKE certified for Kubernetes 1.19.
I'm now implementing an option to CKE to run kube-proxy in iptables mode...

**Pull request closed without merging**
