### PR TITLE
conformance results for v1.13/kind

### PR DESCRIPTION
**Pull request by BenTheElder**
https://github.com/kubernetes-sigs/kind

### CODE REVIEW

**Comment by taylorwaggoner** [comment]
@BenTheElder thanks for submitting! The results look great!  Could you please submit a signed participation form so that we have contact info on file?  You can mark Nonprofit on the form, as there won't be a fee involved.  https://github.com/cncf/k8s-conformance/tree/master/participation-form

Thanks!

**Comment by BenTheElder** [comment]
Absolutely, taking a look now, thank you!

**Comment by dankohn** [comment]
I've confirmed with LF legal that we don't need a signed participation agreement since kind is part of Kubernetes. Sorry for extra delay. We'll approve shortly.

Cc @swinslow

**Comment by BenTheElder** [comment]
Thank you @dankohn :pray:  -- after some further discussion, I wasn't sure if I even needed to? But I'd been waiting for a response from someone with more authority than I :sweat_smile:

**Comment by taylorwaggoner** [comment]
You are now Certified Kubernetes
https://github.com/cncf/landscape/pull/1092

**Comment by BenTheElder** [comment]
Awesome!! Thank you all! 😄

**Comment by dankohn** [comment]
You categorized kind as a distribution, but I think we would classify it as an installer, since it is using vanilla, upstream Kubernetes. Agree?

https://github.com/cncf/k8s-conformance/blob/master/faq.md#what-is-a-distribution-hosted-platform-and-an-installer

**Pull request merged**
