### PR TITLE
Added an issue tracking doc.

### PR DESCRIPTION
**Pull request by WilliamDenniss**

### CODE REVIEW

**Comment by dankohn** [comment]
Made minor edits, now LGTM

**Comment by dankohn** [comment]
But we should also link here from https://github.com/cncf/k8s-conformance/blob/master/instructions.md

**Comment by WilliamDenniss** [comment]
Added the link you requested, revised formatting (now bullet point list) & squished the commits – PTAL.

**Comment by dankohn** [comment]
LGTM

**Pull request merged**
