### PR TITLE
Conformance results for v1.15/board

### PR DESCRIPTION
**Pull request by fanzhihai0215**

### CODE REVIEW

**Comment by taylorwaggoner** [comment]
@fanzhihai0215, thank you for submitting.  There are a few things we need to address before I can certify.  First, please send in a [signed participation form](https://github.com/cncf/k8s-conformance/tree/master/participation-form) for this product.  

Second, please provide the logo in SVG, EPS, or AI format.  If you don't have ones of those file types available, our artist can create the logo for you in SVG or we can use the Inspur logo.  

Lastly, please copy and paste the instructions to deploy a cluster into your README.md rather than link to the instructions.

Thanks!

**Comment by taylorwaggoner** [comment]
@fanzhihai0215, wanted to check in with you.  Can you please send in a [signed participation form](https://github.com/cncf/k8s-conformance/tree/master/participation-form) for this product when you get a chance?  Thanks!

**Comment by taylorwaggoner** [comment]
@fanzhihai0215 checking in again on the participation form. thanks!

**Comment by fanzhihai0215** [comment]
@taylorwaggoner Ok, i will send the participation form soon. thanks.

**Comment by taylorwaggoner** [comment]
@fanzhihai0215 - checking in!  Have you sent in the participation form yet?  Thanks!

**Comment by fanzhihai0215** [comment]
@taylorwaggoner I have sent in the participation form. Sorry for delay. Please check.

**Comment by taylorwaggoner** [comment]
@fanzhihai0215 thanks, we received it!  A couple more things here - we still need your Board logo in SVG, EPS, or AI format.  Also, the vendor name in your product.yaml should be Inspur not Board.  Thanks!

**Comment by fanzhihai0215** [comment]
@taylorwaggoner I Modified Board logo url and the vendor name in PRODUCT.yaml. Please check. Thx.

**Comment by taylorwaggoner** [comment]
@fanzhihai0215 thank you for updating.  Do you have that logo in any other formats? The one you included isn't a pure SVG file, it embeds a png.  If you don't, I can ask our artist to recreate your logo.  Thanks!

**Comment by fanzhihai0215** [comment]
@taylorwaggoner I updated the SVG file on product_logo_url. If it does not meet the requirements, please help me to recreate the logo. Thx!

**Comment by taylorwaggoner** [comment]
You are now Certified Kubernetes
https://landscape.cncf.io/format=card-mode&grouping=organization&organization=inspur-group&selected=board

**Pull request merged**
