### PR TITLE
Conformance results for v1.22/desktop-kubernetes

### PR DESCRIPTION
**Pull request by aceeric**
### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [X] If this is a new entry, have you submitted a signed [participation form](https://github.com/cncf/k8s-conformance/tree/master/participation-form)?
* [X] Did you include the product/project logo in SVG, EPS or AI format?  
* [X] Does your logo clearly state the name of the product/project and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [X] If your product/project is open source, did you include the `repo_url`?
* [X] Did you copy and paste the [installation and configuration instructions](https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions) into the README.md file in addition to linking to them?

### CODE REVIEW

**Comment by Riaankl** [comment]
@aceeric the [Instructions](https://github.com/cncf/k8s-conformance/blob/master/instructions.md#uploading) for uploading results requier the PR description to be `Conformance results for vX.Y/$dir` where vX.Y rever to the K8s release version ie. v.122 and not the product version.
Hope that help.

**Comment by aceeric** [comment]
They do. Is there a specific way I need to do that? Thanks,

- Eric

Sent with [ProtonMail](https://protonmail.com/) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by aceeric** [comment]
@Riaankl I modified the PR description to be correct. Thanks.

**Comment by Riaankl** [comment]
> The first test found to be mssing was [sig-node] NoExecuteTaintManager Single Pod [Serial] removing taint cancels eviction [Disruptive] [Conformance]

@aceeric there was a bug in Sonobuoy that casued this failure the the comments in the [PR](https://github.com/cncf/k8s-conformance/pull/1566#issuecomment-899856429) for more clarity.
Sonobuoy and released a fixed version here: https://github.com/vmware-tanzu/sonobuoy/releases/tag/v0.53.2

**Comment by taylorwaggoner** [comment]
Hi @aceeric - do you have a logo available that includes "Desktop Kubernetes" in text? We require text on all of the logos on the landscape. Thanks!

**Comment by taylorwaggoner** [comment]
Also, please note that we'll need to create a Crunchbase profile for your product, as it's a required field on the landscape. (Last bullet here: https://github.com/cncf/landscape#new-entries).  I can create this for you if you'd like? Thanks!

**Comment by aceeric** [comment]
@taylorwaggoner Thank you, I am working on an SVG with the text in it. Not my area of specialty but I think I am close. WRT Crunchbase - I just created a profile though - I have all of 5 minutes of experience with Crunchbase. If you are unable to find/see it please let me know what action I should take to make it visible. Thank you.

**Comment by aceeric** [comment]
@taylorwaggoner the logo svg with text is now there. Thank you.

**Comment by aceeric** [comment]
@taylorwaggoner hopefully this fits the bill: https://www.crunchbase.com/person/eric-ace-cd26 -- if I need to do something different in there please advise. I'm new with Crunchbase. Thanks.

**Comment by taylorwaggoner** [comment]
I've never used a "person" account, typically we use "company" accounts.  But I can give it a shot and let you know.  We may want to create one for your product under a company account.  Will keep ya posted

**Comment by Riaankl** [comment]
Hi @aceeric , thank you for you submission.
The K8s COnformance project is in 3 hours. I have put this on the agenda to discuss with the Conformance community.
Please join us if you can.
https://docs.google.com/document/d/1W31nXh9RYAb_VaYkwuPLd1hFxuRX3iU0DmaQ4lkCsX8/edit?pli=1#

**Comment by aceeric** [comment]
I'm sorry - I was unable to attend. Please let me know if you need anything additional from me. Thanks.

**Comment by taylorwaggoner** [comment]
@aceeric so sorry for the delay!  I added your product to the landscape but then didn't tell you that you were approved!  Here you go: https://landscape.cncf.io/card-mode?category=certified-kubernetes-distribution,certified-kubernetes-hosted,certified-kubernetes-installer,special&grouping=category&selected=desktop-kubernetes

You are now Certified Kubernetes, thanks!

**Pull request merged**
