### PR TITLE
Conformance results for v1.8/cdk

### PR DESCRIPTION
**Pull request by ktsakalozos**
Conformance results for Canonical Distribution of Kubernetes

### CODE REVIEW

**Comment by ktsakalozos** [comment]
Do I need to do anything else here?

**Comment by kbarnard10** [comment]
@ktsakalozos Could you double-check your version.txt file. It should look like this: https://github.com/mml/k8s-conformance/blob/744639d2527eebddba13b0ec87047a5ec00f1b76/v1.8/gke/version.txt

**Comment by ktsakalozos** [comment]
Thank you for the review @kbarnard10 just updated the PR with the tests against the latest CDK and of course the right version.txt

**Comment by kbarnard10** [comment]
@ktsakalozos Looks great now! +1

**Comment by luxas** [comment]
Squash commits?

**Comment by ktsakalozos** [comment]
Just did the squash. Thanks @luxas , @kbarnard10.

**Comment by ktsakalozos** [comment]
Hi @kbarnard10, I am not aware what does the "participation-form-signed-no" means. Is there anything I have to do about this? Thanks

**Comment by dankohn** [comment]
It means that we need you to complete this form please: https://github.com/cncf/k8s-conformance/blob/master/participation-form/Certified_Kubernetes_Form.md

**Comment by ktsakalozos** [comment]
All done @dankohn , thank you.

**Pull request merged**
