### PR TITLE
Conformance results for v1.13/portworx

### PR DESCRIPTION
**Pull request by rodrigc**
Signed-off-by: Craig Rodrigues <craig@portworx.com>

### CODE REVIEW

**Comment by rodrigc** [comment]
[DocuSign_Certified_Kubernetes_Formpd.pdf](https://github.com/cncf/k8s-conformance/files/3168621/DocuSign_Certified_Kubernetes_Formpd.pdf)

**Comment by dankohn** [comment]
Thanks for your submission, but it appears that you're trying to certify that adding Portworx does not interfere with a Certified Kubernetes cluster's conformance. That's not the purpose of the program.

Instead, Certified Kubernetes is demonstrating the conformance of the underlying cluster for organizations that provide one.

We could later add a conformance program for add-ons like Portworx or Twistlock, but we don't have such a program today. I'm going to close these PRs without merging.

If you'd like to discuss further, please do so on the working group mailing list or by emailing conformance@cncf.io.

**Comment by rodrigc** [comment]
@dankohn Certification for Portworx was already submitted for Kubernetes 1.11 here: https://github.com/cncf/k8s-conformance/pull/301

Portworx received an e-mail indicating that this certification would expire on *June 27, 2019*.
You were CC:'d on some e-mail discussion about this on May 10, *Subject: Re: Portworx - Your v1.11 Certified Kubernetes Expires June 27, 2019*.

Please provide guidance as to how to proceed.

**Comment by dankohn** [comment]
Thanks for your response. I may be confused now or we might have been confused then when we approved your certification.

Does Portworx offer a Kubernetes distribution that I can install on bare metal or a public cloud?

**Comment by rodrigc** [comment]
Portworx does not offer a Kubernetes distribution.  Portworx software is installed on existing Kubernetes distributions, and provides Cloud Native storage which can be accessed via Kubernetes Persistent Volume Claim (PVC).

In https://github.com/cncf/k8s-conformance/pull/301#issuecomment-415809881 , @taylorwaggoner advised to submit the k8s 1.11 certifcation as *Portworx on Kubernetes*

**Comment by dankohn** [comment]
Thanks, I see now. We're going to revoke the previous certification, which should not have been issued.

In the future, there may be a certification for storage providers, with which you would be welcome to participate. And, the Portworx product remains listed in the Landscape under Cloud-Native Storage: https://landscape.cncf.io/selected=portworx

But we will be removing the Certified Kubernetes listing.

**Pull request closed without merging**
