### PR TITLE
Conformance results for v1.17/kube-up-gce

### PR DESCRIPTION
**Pull request by spiffxp**

### CODE REVIEW

**Comment by dankohn** [comment]
@spiffxp Could you please help explain the repo choice here?

In the past, we've used https://github.com/kubernetes/kube-deploy as the repo but I see that it hasn't been updated in 18 months.

Note that there are currently 6 conformant installers in the Kubernetes project: https://landscape.cncf.io/category=certified-kubernetes-installer&format=card-mode&grouping=category&organization=cloud-native-computing-foundation-cncf,google so I'm hesitant on whether https://github.com/kubernetes/kubernetes is the best repo for describing kube-up.

**Comment by spiffxp** [comment]
@dankohn kube-up lives inside the kubernetes repo; https://github.com/kubernetes/kubernetes/blob/master/cluster/kube-up.sh

I could update to point to the specific subdir inside of that repo if you would prefer

**Comment by dankohn** [comment]
OK, the CNCF Landscape normally requires that a repo be listed (not a path) and that the repo only be listed once, but there's a hack we can use to allow https://github.com/kubernetes/kubernetes to be used for both the Kubernetes project and Kube-up

@taylorwaggoner Please approve.

**Comment by taylorwaggoner** [comment]
You are now Certified Kubernetes

**Pull request merged**
