### PR TITLE
Conformance results for v1.23/Hitachi Kubernetes Service

### PR DESCRIPTION
**Pull request by simonhitachi**
### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [x] If this is a new entry, have you submitted a signed [participation form](https://github.com/cncf/k8s-conformance/tree/master/participation-form)?
* [ ] Did you include the product/project logo in SVG, EPS or AI format?  
* [ ] Does your logo clearly state the name of the product/project and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [ ] If your product/project is open source, did you include the `repo_url`?
* [x] Did you copy and paste the [installation and configuration instructions](https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions) into the README.md file in addition to linking to them?

### CODE REVIEW

**Comment by taylorwaggoner** [comment]
@simonhitachi checking in!

**Comment by simonhitachi** [comment]
Hey Taylor,

I've been off for a few days - need to get round to updating the README....

Leave it with me and I'll be on it in the next couple of days.

Regards,

Simon.

**Comment by taylorwaggoner** [comment]
@simonhitachi checking in!

**Comment by taylorwaggoner** [comment]
@simonhitachi wanted to check back in with you about this PR, thanks

**Comment by taylorwaggoner** [comment]
@simonhitachi do you still want to submit this PR? Please see my previous notes. thanks!

**Comment by simonhitachi** [comment]
Hi Taylor,

Apologies for the delay in actioning this - if we can dismiss this currently please. There has been a change in direction for the product and currently it won't be offered as a direct option for customers, so we currently don't want to publicise it.

If you can dismiss it, or if easier I can delete the request if necessary.

Regards,

Simon.

**Comment by taylorwaggoner** [comment]
@simonhitachi thanks, I'll close the PR.

**Pull request closed without merging**
