### PR TITLE
Add conformance results for v1.15/elastx

### PR DESCRIPTION
**Pull request by bl0m1**

### CODE REVIEW

**Comment by taylorwaggoner** [comment]
@bl0m1, thanks for submitting! The results look great, but before we can merge, could you please update your README to include the detailed instructions to reproduce?  Thanks!

**Comment by bl0m1** [comment]
@taylorwaggoner Just wanted to check if there is anything specific steps you are missing in our README file?

Instead of writing a guide on how to run Sonobuoy we link to your steps. (https://github.com/cncf/k8s-conformance/blob/master/instructions.md#Running)

**Comment by dankohn** [comment]
Please look at any of the other Readme's filed here and you'll see they have more detailed instructions than "Download the kubeconfig as per instructions given and configure your kubectl to use it." That's what we're requesting.

**Comment by bl0m1** [comment]
We currently manually start the procedure meaning there is no "create cluster" button.
Where and how we store secret is something we have between us and our end customers.

We are providing a hosted solution meaning we handle all setup from our end. Afterwards we share download instructions with our end customer over their proffered communication method.

I could try adding a few words but does not want to share information on where exactly we store secretes etc publicly.

**Comment by dankohn** [comment]
We're definitely not interested in details on where you share secrets. But the point of the directions is so that a customer can re-run the tests on their own and confirm that your hosted platform still passes all the conformance tests. In that way, we crowdsource the verification of certification.

Please look at some other certifications in the same directory and emulate their level of detail in the directions.

**Comment by bl0m1** [comment]
Updated the readme file to have complete instructions :)

**Comment by taylorwaggoner** [comment]
Thanks! You are now Certified Kubernetes.

**Pull request merged**
