### PR TITLE
Added conformance results for 1.15 on EKS

### PR DESCRIPTION
**Pull request by jqmichael**

### CODE REVIEW

**Comment by jqmichael** [comment]
@taylorwaggoner

**Comment by taylorwaggoner** [comment]
@jqmichael thanks for submitting!  I'll update the product name [in the landscape](https://landscape.cncf.io/format=card-mode&selected=amazon-elastic-container-service-for-kubernetes-eks).

Before I can merge, there are a couple items to address.  First, please paste in the instructions to setup the cluster, in addition to linking the URL, per [these guidelines](https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions).

I also wanted to note that we require SVG, EPS, or AI for the logo and that it would need to contain the company or product name, based on the [logo requirements](https://github.com/cncf/landscape#logos).  We've been using the normal AWS, as shown in the first link above.  Will that still work?

Thanks!

**Comment by jqmichael** [comment]
Thanks @taylorwaggoner. I've updated the README to include sample command to set up cluster. Please take a look. 

I'll ping our PM regarding the logo change.

**Comment by dankohn** [comment]
FYI, we changed from the EKS to the AWS logo at the request of https://www.linkedin.com/in/brhall/ so we'd prefer if you could just update the PRODUCT.yaml logo URL to keep the AWS logo.

**Comment by jqmichael** [comment]
After talking to the team, I've updated the logo to the AWS one. 

Please take a look. Thanks.

@taylorwaggoner @dankohn

**Comment by jqmichael** [comment]
Gentle ping

@taylorwaggoner @dankohn

**Comment by taylorwaggoner** [comment]
Thanks! You are now Certified Kubernetes

**Comment by jqmichael** [comment]
Thanks for the help @taylorwaggoner !

**Pull request merged**
