### PR TITLE
Conformance results for v1.19/docker-desktop-mac

### PR DESCRIPTION
**Pull request by mat007**
### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [ ] If this is a new entry, have you submitted a signed [participation form](https://github.com/cncf/k8s-conformance/tree/master/participation-form)?
* [ ] Did you include the product/project logo in SVG, EPS or AI format?  
* [x] Does your logo clearly state the name of the product/project and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [ ] If your product/project is open source, did you include the `repo_url`?
* [x] Did you copy and paste the [installation and configuration instructions](https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions) into the README.md file in addition to linking to them?

Add conformance test results for v1.19/docker-desktop-for-mac

> This conformance request failed to include all of the required tests for v1.19

Docker Desktop is a single node Kubernetes cluster, therefore we need to skip the tests that require multiple nodes.
Due to a change in the test code we now need to skip more tests than before, see https://github.com/kubernetes/kubernetes/pull/91955/files#diff-48c3b5f1a5e8c2a2b246eb43a6efc90351ca6f15ebf948e930acd20d327df0f7R250

### CODE REVIEW

**Comment by mat007** [comment]
@taylorwaggoner I suspect it wasn’t intentional that the conformance test code change I linked above now prevents single node distributions from passing one of the required tests?

**Comment by hh** [comment]
I started a conversation on slack.k8s.io #k8s-conformance to get clarification. I know we have tests that require multiple nodes, but doesn't hurt to get current consensus and feedback:
https://kubernetes.slack.com/archives/C78F00H99/p1611962380006000

If we don't get consensus there, I may reach out to the mailing list.

**Comment by BenTheElder** [comment]
> @taylorwaggoner I suspect it wasn’t intentional that the conformance test code change I linked above now prevents single node distributions from passing one of the required tests?

rather, it was unintentional that the test previously `Skip`ed on single node clusters, skipping is not allowed.
https://github.com/kubernetes/kubernetes/issues/69601#issuecomment-449980503
https://groups.google.com/g/kubernetes-sig-architecture/c/s-SCpQQDOEo/m/FUGmTFKKAQAJ

This also changed way back in Kubernetes release 1.14.0 ... https://github.com/kubernetes/kubernetes/pull/72690/commits/8e9f8e264fd8fa970ef846daeb8d82f5d6d35c07

**Comment by mat007** [comment]
Thank you for the clarification. 2+ nodes is indeed a requirement for conformance.

**Pull request closed without merging**
