### PR TITLE
gardener supporting new k8s release

### PR DESCRIPTION
**Pull request by OlegLoewen**
Conformance test results for Kubernetes clusters deployed by
SAP Cloud Platform Gardener 0.17.3

v1.12/gardener-aws : cluster deployed on AWS
v1.12/gardener-azure : cluster deployed on AZURE
v1.12/gardener-openstack : cluster deployed on OPENSTACK
v1.12/gardener-gce : cluster deployed on GCE
v1.13/gardener-aws : cluster deployed on AWS
v1.13/gardener-azure : cluster deployed on AZURE
v1.13/gardener-openstack : cluster deployed on OPENSTACK
v1.13/gardener-gce : cluster deployed on GCE
v1.13/sap-cp-aws : cluster deployed on AWS
v1.13/sap-cp-azure : cluster deployed on AZURE
v1.13/sap-cp-openstack : cluster deployed on OPENSTACK
v1.13/sap-cp-gce : cluster deployed on GCE

### CODE REVIEW

**Comment by taylorwaggoner** [comment]
@OlegLoewen, thank you for submitting.  I noticed that there is a set of 4 files for v1.12/sap-cp-gce.  Were those added by accident?  You already have the 1.12 certification for GCP here: https://github.com/cncf/k8s-conformance/pull/378/files

**Comment by OlegLoewen** [comment]
> @OlegLoewen, thank you for submitting. I noticed that there is a set of 4 files for v1.12/sap-cp-gce. Were those added by accident? You already have the 1.12 certification for GCP here: https://github.com/cncf/k8s-conformance/pull/378/files

Hello @taylorwaggoner , indeed this was a mistake. I removed the corresponding files from the pull request. Thanks for the hint!

**Comment by OlegLoewen** [comment]
Hello @taylorwaggoner is the Pull Request now fine? Or is something missing/wrong?

**Comment by taylorwaggoner** [comment]
@OlegLoewen please take a look at all of your e2e.log files, specifically the ones below, and ensure that there are 0 flaked tests, as per these guidelines: https://github.com/cncf/k8s-conformance/blob/master/reviewing.md#technical-requirements
- https://github.com/cncf/k8s-conformance/blob/8975a870f544714008577448786cb2d5314d5654/v1.12/gardener-azure/e2e.log
- https://github.com/cncf/k8s-conformance/blob/8975a870f544714008577448786cb2d5314d5654/v1.13/gardener-azure/e2e.log
- https://github.com/cncf/k8s-conformance/blob/8975a870f544714008577448786cb2d5314d5654/v1.13/sap-cp-azure/e2e.log
Thanks!

**Comment by OlegLoewen** [comment]
Oh, too bad. You are right, there are some flaked ones. I will close this PR and create a new one, when all data fulfils the requirements.

**Pull request closed without merging**
