### PR TITLE
Conformance results for v1.15/triton-kubernetes

### PR DESCRIPTION
**Pull request by nimajalali**

### CODE REVIEW

**Comment by taylorwaggoner** [comment]
@nimajalali, thank you for submitting.  The results look great, but there are a couple of items we need to fix before moving forward.  

First, the Triton logo you included in the product file uses a wheel that is [too similar to the Kubernetes wheel](https://github.com/cncf/k8s-conformance/blob/master/faq.md#are-there-any-limitations-regarding-the-logo). We ask that you please stop using that logo for your product.  You also shouldn’t use the R registered trademark on it, please.  We can use the [current logo from the landscape](https://landscape.cncf.io/format=card-mode&selected=joyent-triton-for-kubernetes) instead unless you'd prefer a different Joyent logo.

Second, please copy and paste the instructions to install into the README, rather than linking to the URLs. Thanks!

**Comment by taylorwaggoner** [comment]
@nimajalali, wanted to check in!  
Please see [this entry in the Conformance FAQ](https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions) for more info about the README requirement I mentioned in my last comment.

Please advise about the logo as well.

Thanks!

**Comment by taylorwaggoner** [comment]
@nimajalali checking in!  Please let me know if you have any questions!

**Comment by nimajalali** [comment]
@taylorwaggoner Apologies for the delay. We've updated the logo and removed the previous logo from our marketing material.

I've also added the instructions to install directly into the README.

**Comment by taylorwaggoner** [comment]
You are now Certified Kubernetes

**Pull request merged**
