### PR TITLE
Conformance results for v1.22/vmware-tanzu-community-edition 

### PR DESCRIPTION
**Pull request by jpmcb**
### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [x] If this is a new entry, have you submitted a signed [participation form](https://github.com/cncf/k8s-conformance/tree/master/participation-form)?
  * N/a - already submitted previously in v1.21
* [x] Did you include the product/project logo in SVG, EPS or AI format?  
* [x] Does your logo clearly state the name of the product/project and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [x] If your product/project is open source, did you include the `repo_url`?
* [x] Did you copy and paste the [installation and configuration instructions](https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions) into the README.md file in addition to linking to them?

Closes: https://github.com/vmware-tanzu/community-edition/issues/4223

### CODE REVIEW

**Comment by jpmcb** [comment]
cc @joshrosso

**Comment by Riaankl** [comment]
> The file extension format for PRODUCT.yml should be .yaml (https://github.com/cncf/k8s-conformance/blob/master/instructions.md#productyaml)
> 
> Please update with a valid file extension.

@jpmcb can you please update the PRODUCT file extention form .yml to .yaml for the CNCF-CI bot to process your submission.
Thanks you!!

**Comment by jpmcb** [comment]
Whoops! Good to know - thank you so much!!

**Comment by taylorwaggoner** [comment]
You are now Certified Kubernetes

**Pull request merged**
