### PR TITLE
Conformance results of IBM Cloud Private for v1.16

### PR DESCRIPTION
**Pull request by liqlin2015**
### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [ ] If this is a new entry, have you submitted a signed [participation form](https://github.com/cncf/k8s-conformance/tree/master/participation-form)?
* [x] Did you include the product/project logo in SVG, EPS or AI format?  
* [x] Does your logo clearly state the name of the product/project and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [ ] If your product/project is open source, did you include the `repo_url`?
* [x] Did you copy and paste the [installation and configuration instructions](https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions) into the README.md file in addition to linking to them?

### CODE REVIEW

**Comment by taylorwaggoner** [comment]
@liqlin2015 thanks for submitting.  Before we can move forward with certification, there are a couple things to resolve.  First, we [no longer require the version.txt file](https://github.com/cncf/k8s-conformance/blob/master/instructions.md#contents-of-the-pr), so please remove. We also ask that you [paste all installation instructions into your README](https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions), in addition to linking to them.  We're trying to eliminate link rot and ensure that customers can duplicate your conformance test results if they choose to.  Let me know if you have any questions! Thanks!

**Comment by taylorwaggoner** [comment]
@liqlin2015 checking in!

**Comment by liqlin2015** [comment]
Sure. I will update the PR.

**Comment by liqlin2015** [comment]
@taylorwaggoner  Addressed your comments. Please help review again.

**Comment by taylorwaggoner** [comment]
Great thanks.  Could you please also add the product type and product description to your [PRODUCT file](https://github.com/cncf/k8s-conformance/blob/master/instructions.md#productyaml)? Thanks!

**Comment by liqlin2015** [comment]
@taylorwaggoner Addressed your comments. Please help merge the PR if there is no more comments.

**Comment by taylorwaggoner** [comment]
You are now Certified Kubernetes
https://landscape.cncf.io/format=card-mode&selected=ibm-cloud-private

**Pull request merged**
