### PR TITLE
Conformance results for v1.7/alauda-ee

### PR DESCRIPTION
**Pull request by fohnwind**
vendor: Alauda
name: Alauda EE
version: v1.7.0
website_url: http://www.alauda.cn/product/detail/id/68.html
documentation_url: http://developer.alauda.cn/usermanual/features/clusterkubernetes.html
product_logo_url: https://enterprise.alauda.cn/static/images/logo/logo-login-large.svg

### CODE REVIEW

**Comment by kbarnard10** [comment]
+1. Signed participation form needed. 

Please follow the instructions here to submit it: either via [PDF](https://github.com/cncf/k8s-conformance/blob/master/participation-form/Certified_Kubernetes_Form.pdf) or [DocuSign](https://na3.docusign.net/Member/PowerFormSigning.aspx?PowerFormId=ba08f93a-65ca-4c5d-8210-d5c858bb9208)

**Comment by cimomo** [comment]
@kbarnard10 I've signed the participation form on behalf of Alauda via DocuSign. Thanks!

**Comment by cimomo** [comment]
@kbarnard10 Thank you! Does this mean that we are certified or is there any other action we need to take at this time? Thanks again.

**Comment by kbarnard10** [comment]
Nothing else - you're certified. I will get your logo up on the CNCF and Kubernetes websites shortly.

**Pull request merged**
