### PR TITLE
Conformance results for v1.21/nks

### PR DESCRIPTION
**Pull request by gonais**
### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [x] If this is a new entry, have you submitted a signed [participation form](https://github.com/cncf/k8s-conformance/tree/master/participation-form)?
* [x] Did you include the product/project logo in SVG, EPS or AI format?  
* [x] Does your logo clearly state the name of the product/project and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [ ] If your product/project is open source, did you include the `repo_url`?
* [x] Did you copy and paste the [installation and configuration instructions](https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions) into the README.md file in addition to linking to them?

### CODE REVIEW

**Comment by taylorwaggoner** [comment]
@gonais thanks for submitting.  Have you submitted a [participation form](https://github.com/cncf/k8s-conformance/tree/master/participation-form) for this product yet?

Please also include more detailed information about creating a cluster in your README, per [these guidelines](https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions).

Thanks!

**Comment by gonais** [comment]
@taylorwaggoner  thanks for your guide.
We are preparing to submit the partition form. 
Please wait a couple of hours. :)

**Comment by gonais** [comment]
@taylorwaggoner 
We have just submitted the participation form.
Thank you!

**Comment by taylorwaggoner** [comment]
Thank you for submitting the form @gonais!

Please include more detailed information about creating a cluster in your README, per these [guidelines.
](https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions)
Also, the logo you indicated embeds text so we can't use it on the landscape. Please see [our logo guidelines](https://github.com/cncf/landscape#dont-use-svgs-with-embedded-text) to resolve

Thanks!

**Comment by gonais** [comment]
@taylorwaggoner 
We added more information in the README and got rid of the links.
And the logo file has been changed not to include text objects.
Please find the logo file. https://static.toastoven.net/toast/nks/logo_nks.svg

Thank you!

**Comment by taylorwaggoner** [comment]
You are now Certified Kubernetes

**Pull request merged**
