### PR TITLE
Conformance results for  China Mobile CMIT PaaS  on kubernetes v1.18

### PR DESCRIPTION
**Pull request by weibaohui**
### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [√] If this is a new entry, have you submitted a signed [participation form](https://github.com/cncf/k8s-conformance/tree/master/participation-form)?
* [√] Did you include the product/project logo in SVG, EPS or AI format?  
* [√] Does your logo clearly state the name of the product/project and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [ ] If your product/project is open source, did you include the `repo_url`?
* [√] Did you copy and paste the [installation and configuration instructions](https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions) into the README.md file in addition to linking to them?

### CODE REVIEW

**Comment by taylorwaggoner** [comment]
@weibaohui thank you for submitting.  A few things before we can move forward.  First, is there a different website available for this product?  The one you provided, http://www.10086.cn/, is showing this when I visit the site:
Screen Shot 2020-08-13 at 5 05 10 PM

Please also provide a new logo in SVG, EPS, or AI format - the one you linked to is not a pure SVG in that it embeds a PNG, so we are unable to use it.  

Please also take a look at your README.  It would be great if you could add a bit more detail about how to create a Kubernetes cluster.  Can you provide the steps one needs to take to create it in the UI?

> 3.Please use UI to create Kubernetes cluster.

Thanks!

**Comment by weibaohui** [comment]
@taylorwaggoner thanks for your checking.

- we have updated our README.Added some UI opreate details.
- we also provide a new logo in svg format.please re-check the [logo](https://github.com/ChinaMobileIT/paas/blob/master/cmit-paas-logo.svg).
- we changed the website_url in PRODUCT.yaml ,there will be company-related introductions. [https://www.chinamobileltd.com/en/global/home.php](https://www.chinamobileltd.com/en/global/home.php) 
because of our PaaS is an internal system that is not open to the outside, and is only available to internal users, so there is no detailed introduction of related products on the official website. 


Please help review again,thank you !

**Comment by taylorwaggoner** [comment]
Thanks, it looks great!  One last thing before we move forward.  If this is an internal product not available to outside users, I just wanted to confirm that you still want to go forward with certification.  Please see our comments about private products:https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-certify-my-private-cloud-that-will-not-be-available-outside-of-our-company

Thanks!

**Comment by weibaohui** [comment]
> Thanks, it looks great! One last thing before we move forward. If this is an internal product not available to outside users, I just wanted to confirm that you still want to go forward with certification. Please see our comments about private products:https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-certify-my-private-cloud-that-will-not-be-available-outside-of-our-company
> 
> Thanks!

@taylorwaggoner,Thanks for your reply  ~

Yes, I confirm. There are a lot of internal users in our group company, so we want to go forward whit the kubernetes conformance certification.

This is our company's CNCF Silver Member [link](https://landscape.cncf.io/format=card-mode&grouping=organization&organization=china-mobile&selected=china-mobile-member)

Please help us go ahead.

thanks~

**Comment by taylorwaggoner** [comment]
You are now Certified Kubernetes
https://landscape.cncf.io/format=card-mode&selected=china-mobile-cmit-paa-s

**Pull request merged**
