### PR TITLE
Conformance results for v1.26/starlingx

### PR DESCRIPTION
**Pull request by ildikov**
### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [ ] If this is a new entry, have you submitted a signed [participation form](https://github.com/cncf/k8s-conformance/tree/master/participation-form)?
* [x] Did you include the product/project logo in SVG, EPS or AI format?  
* [x] Does your logo clearly state the name of the product/project and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [x] If your product/project is open source, did you include the `repo_url`?
* [x] Did you copy and paste the [installation and configuration instructions](https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions) into the README.md file in addition to linking to them?

### CODE REVIEW

**Comment by taylorwaggoner** [comment]
@ildikov thanks for submitting. We don't have a recent participation form on file for you - please [fill one out](https://github.com/cncf/k8s-conformance/tree/master/participation-form) and submit to conformance@cncf.io, thanks!

**Comment by ildikov** [comment]
@taylorwaggoner Thank you for letting me know! I wasn't aware it expires/how frequently it has to be renewed. I'll fill it out in a bit.

**Comment by ildikov** [comment]
@taylorwaggoner I submitted the signed form a little while back. Is there any other steps that I still need to complete for this to go through?

**Comment by taylorwaggoner** [comment]
You are now Certified Kubernetes

**Comment by ildikov** [comment]
Thanks @taylorwaggoner !

**Pull request merged**
