### PR TITLE
Submitting CNCF Conformance (sonobuoy) results for Wind River Cloud P…

### PR DESCRIPTION
**Pull request by gwaines**
…latform.

( Note, if any issues with request email greg.waines@windriver.com )

### CODE REVIEW

**Comment by taylorwaggoner** [comment]
@gwaines, thank you for submitting. There are a few things we need to address before I can certify. First, please send in a [signed participation form](https://github.com/cncf/k8s-conformance/tree/master/participation-form) for this product.

Second, please provide the logo in SVG, EPS, or AI format per [these guidelines](https://github.com/cncf/k8s-conformance/blob/master/faq.md#are-there-any-limitations-regarding-the-logo).

If you'd like to have your product shown as open source, please provide a mirror of https://opendev.org/starlingx in GitHub.  

Lastly, make sure you include a README.md file instead of the build.info file, [per the instructions](https://github.com/cncf/k8s-conformance/blob/master/instructions.md#contents-of-the-pr).

Thanks!

**Comment by gwaines** [comment]
> @gwaines, thank you for submitting. There are a few things we need to address before I can certify. First, please send in a [signed participation form](https://github.com/cncf/k8s-conformance/tree/master/participation-form) for this product.
> 
> Second, please provide the logo in SVG, EPS, or AI format per [these guidelines](https://github.com/cncf/k8s-conformance/blob/master/faq.md#are-there-any-limitations-regarding-the-logo).
> 
> If you'd like to have your product shown as open source, please provide a mirror of https://opendev.org/starlingx in GitHub.
> 
> Lastly, make sure you include a README.md file instead of the build.info file, [per the instructions](https://github.com/cncf/k8s-conformance/blob/master/instructions.md#contents-of-the-pr).
> 
> Thanks!

Thanks for looking at this Taylor.

I added a v1.16/windrivercloud/Certified_Kubernetes_Form.md 
       (Is this enough or do you need a PDF with a 'real' signature ?)

I added a v1.16/windrivercloud/wind-river-cloud-platform-logo.svg

And I created a README.md file per instructions.

Let me know if there is anything else you need.

Greg.

**Comment by taylorwaggoner** [comment]
@gwaines, thanks, but we do need a real signed participation form. You can [access the form and sign in Docusign ](https://github.com/cncf/k8s-conformance/blob/master/participation-form/Certified_Kubernetes_Form.md).

Thank you for providing the logo, but the file you uploaded contains a PNG, so it's not a true SVG.  Do you have the same logo in EPS or AI format?  

Thanks!

**Comment by gwaines** [comment]
> @gwaines, thanks, but we do need a real signed participation form. You can [access the form and sign in Docusign ](https://github.com/cncf/k8s-conformance/blob/master/participation-form/Certified_Kubernetes_Form.md).
> 
> Thank you for providing the logo, but the file you uploaded contains a PNG, so it's not a true SVG. Do you have the same logo in EPS or AI format?
> 
> Thanks!

Ok ... sorry, first time doing this ...

I replaced the SVG logo with an EPS logo ... hoping that's actually a proper EPS.

And updated the form to be signed by Docusign.

Let me know if everything is good.

thanks again for looking at this quickly.
Greg.

**Comment by gwaines** [comment]
> @gwaines, thanks, but we do need a real signed participation form. You can [access the form and sign in Docusign ](https://github.com/cncf/k8s-conformance/blob/master/participation-form/Certified_Kubernetes_Form.md).
> 
> Thank you for providing the logo, but the file you uploaded contains a PNG, so it's not a true SVG. Do you have the same logo in EPS or AI format?
> 
> Thanks!

@taylorwaggoner ... just checking in to see if you've had a chance to look at this yet ?
let me know if I need to correct anything else,
Greg.

**Comment by taylorwaggoner** [comment]
You are now Certified Kubernetes
https://landscape.cncf.io/format=card-mode&organization=wind-river&selected=wind-river-cloud-platform

**Comment by gwaines** [comment]
WOOHOO !

Thanks for all your help Taylor.

Greg.

**Comment by gwaines** [comment]
> You are now Certified Kubernetes
> https://landscape.cncf.io/format=card-mode&organization=wind-river&selected=wind-river-cloud-platform

@taylorwaggoner some followup questions on this.

I am interested in getting our logo changed to indicate that we are open-source.
I know you'd previously mentioned that a mirror on GitHub.com is required for this.

Our product's source is in https://opendev.org/starlingx which is managed by the open-source OpenStack Foundation. 
I just wanted to double check that this is NOT acceptable ?
( and just curious why )

I wanted to confirm that opendev.org was not acceptable before working on the mirror to GitHub.com ... let me know,
thanks,
Greg.

**Pull request merged**
