### PR TITLE
Conformance results for 4.0.0/dce 

### PR DESCRIPTION
**Pull request by daocloudplf**
### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [ ] If this is a new entry, have you submitted a signed [participation form](https://github.com/cncf/k8s-conformance/tree/master/participation-form)?
* [x] Did you include the product/project logo in SVG, EPS or AI format?  
* [x] Does your logo clearly state the name of the product/project and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [ ] If your product/project is open source, did you include the `repo_url`?
* [x] Did you copy and paste the [installation and configuration instructions](https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions) into the README.md file in addition to linking to them?
[e2e.log](https://github.com/cncf/k8s-conformance/files/4714808/e2e.log)

### CODE REVIEW

**Comment by taylorwaggoner** [comment]
Thanks for submitting.  I noticed that you put these files in the v1.8 directory.  Could you please move to v1.18?
Thanks!

**Comment by daocloudplf** [comment]
/close
Moved to another PR: #992

**Comment by taylorwaggoner** [comment]
@daocloudplf do you want to close this now that #992 has been opened?

**Comment by daocloudplf** [comment]
Hi  ，

Taylor
Just closed this PR,thanks





Best Regards

Pan Li Feng 

Phone:13795218672

**Pull request closed without merging**
