### PR TITLE
Conformance results for v1.12/mcs

### PR DESCRIPTION
**Pull request by joker946**

### CODE REVIEW

**Comment by taylorwaggoner** [comment]
@joker946 thank you for submitting!  There are a few items to resolve before we can certify you.  First, please send us a [signed participation form](https://github.com/cncf/k8s-conformance/tree/master/participation-form).  

Please also remove the version.txt file from your PR, as we do not require it any longer based on [these guidelines](https://github.com/cncf/k8s-conformance/blob/master/instructions.md#contents-of-the-pr).  

Last, I noticed that we have a different logo for you on the [CNCF member page](https://github.com/cncf/k8s-conformance/blob/master/instructions.md#contents-of-the-pr).  We try to keep logos consistent across our websites, so please let us know which logo you'd prefer to use, the one in this PR or [this one](https://www.cncf.io/wp-content/uploads/2019/03/mail.ru-cloud-solutions-1.svg). Thanks!

**Comment by joker946** [comment]
Hi @taylorwaggoner ! Thanks for your review!
Our product manager will sign the requested form soon and we'll submit it ASAP.
We'd prefer to replace the current logo on CNCF member page with our new logo from PRODUCT.yaml.
File version.txt has been removed.

**Comment by taylorwaggoner** [comment]
Thanks, @joker946.  I'll keep a lookout for the signed participation form.  I've updated your logo on the CNCF website with the logo from your PRODUCT.yaml file.  Thanks for removing that version.txt file!

**Comment by joker946** [comment]
@taylorwaggoner I've sent a participation form to conformance@cncf.io from my icloud.com mail

**Comment by taylorwaggoner** [comment]
You are now Certifed Kubernetes.
https://landscape.cncf.io/format=card-mode&selected=mail-ru-cloud-containers

**Pull request merged**
