### PR TITLE
Conformance results for v1.23/aistation

### PR DESCRIPTION
**Pull request by Iamlovingit**
### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [x] If this is a new entry, have you submitted a signed [participation form](https://github.com/cncf/k8s-conformance/tree/master/participation-form)?
* [x] Did you include the product/project logo in SVG, EPS or AI format?  
* [x] Does your logo clearly state the name of the product/project and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [x] If your product/project is open source, did you include the `repo_url`?
* [x] Did you copy and paste the [installation and configuration instructions](https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions) into the README.md file in addition to linking to them?

### CODE REVIEW

**Comment by taylorwaggoner** [comment]
@Iamlovingit please resolve the issues above when you have a moment. thanks!

**Comment by Iamlovingit** [comment]
> 

OK, I am working on it.

**Comment by Iamlovingit** [comment]
@taylorwaggoner Issues are resloved, please have a look.

**Comment by taylorwaggoner** [comment]
@Iamlovingit is this a Kubernetes product?

**Comment by Iamlovingit** [comment]
> @Iamlovingit is this a Kubernetes product?

@taylorwaggoner Yes, this is a product which is based on the kubernetes, it helps people to manager theirs AI application.

**Comment by Iamlovingit** [comment]
@taylorwaggoner Hi taylorwaggoner, what is the status of this PR? Hope your reply.

**Comment by taylorwaggoner** [comment]
Hi , we would consider this a distribution rather than a hosted platform.
Could you please update that in your pull request? Thanks!

Taylor Waggoner
Program Manager - CNCF
Location & Time Zone: Portland, OR - PT

**Comment by Iamlovingit** [comment]
> Hi , we would consider this a distribution rather than a hosted platform. Could you please update that in your pull request? Thanks! Taylor Waggoner Program Manager - CNCF Location & Time Zone: Portland, OR - PT

@taylorwaggoner Thanks for your reply, I have changed the type of `PRODUCT.Type` to `distribution`, please have a look when you have a moment.

**Comment by taylorwaggoner** [comment]
You are now Certified Kubernetes

**Pull request merged**
