### PR TITLE
Conformance results for v1.24/d2iq

### PR DESCRIPTION
**Pull request by dkoshkin**
### Pre-submission checklist:

```
vendor: D2iQ
name: Konvoy
version: v2.4.0-alpha.2
website_url: https://d2iq.com/products/konvoy
documentation_url: https://d2iq.com/products/konvoy
product_logo_url: https://assets.d2iq.com/production/assets/D2iQ-logo.svg
type: distribution
description: 'Konvoy is a standalone distribution of Kubernetes that includes a native Kubernetes cluster pre-packaged for deployment with a complement of best-in-class add-on services enabled by default and ready for immediate use.'
```

*Please check each of these after submitting your pull request:*

* [ ] If this is a new entry, have you submitted a signed [participation form](https://github.com/cncf/k8s-conformance/tree/master/participation-form)?
* [ ] Did you include the product/project logo in SVG, EPS or AI format?  
* [ ] Does your logo clearly state the name of the product/project and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [ ] If your product/project is open source, did you include the `repo_url`?
* [x] Did you copy and paste the [installation and configuration instructions](https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions) into the README.md file in addition to linking to them?

### CODE REVIEW

**Comment by dkoshkin** [comment]
> 14 of 15 requirements have passed. Please review the following:
> 
> * [FAIL] it appears that URL(s) in the PRODUCT.yaml don't resolve to the correct data type
>   
>   * URL field 'website_url' in PRODUCT.yaml resolving content type 'text/plain; charset=UTF-8' must be (text/html)
>   * URL field 'documentation_url' in PRODUCT.yaml resolving content type 'text/plain; charset=UTF-8' must be (text/html)
> 
> for a full list of requirements, please refer to these sections of the docs: [_content of the PR_](https://github.com/cncf/k8s-conformance/blob/master/instructions.md#contents-of-the-pr), and [_requirements_](https://github.com/cncf/k8s-conformance/blob/master/instructions.md#requirements).

I've fixed the URL (and force pushed), but can't tell if this was rerun or not.

**Comment by taylorwaggoner** [comment]
@dkoshkin the results look great!  I had a quick question though - is this a rebranding of Konvoy? Or a different product?  Either way, could you please submit a new [participation form](https://github.com/cncf/k8s-conformance/tree/master/participation-form)?  Thanks!

**Comment by dkoshkin** [comment]
> @dkoshkin the results look great! I had a quick question though - is this a rebranding of Konvoy? Or a different product? Either way, could you please submit a new [participation form](https://github.com/cncf/k8s-conformance/tree/master/participation-form)? Thanks!

@taylorwaggoner sorry for the confusion. **Konvoy** is still the product name that is responsible for providing Kubernetes, **DKP** is the wider suite of tools. It makes more sense to keep the branding as **Konvoy** here as this is also what our customers know it by, I've reverted the naming back to "Konvoy".

**Comment by taylorwaggoner** [comment]
You are now Certified Kubernetes

**Pull request merged**
