### PR TITLE
Conformance result for MetalK8s-0.1.0

### PR DESCRIPTION
**Pull request by Zempashi**
vendor: Scality
name: MetalK8s
version: 0.1.0
website_url: https://github.com/scality/metal-k8s/
documentation_url: https://metal-k8s.readthedocs.io/
type: installer
description: "An opinionated Kubernetes distribution with a focus on long-term on-prem deployments"

### CODE REVIEW

**Comment by taylorwaggoner** [comment]
Hi @Zempashi - Thanks for submitting.  The results look great, but there are a couple things we need from you before we can certify.  

First is that you need to send in a signed participation form: https://github.com/cncf/k8s-conformance/blob/master/participation-form/Certified_Kubernetes_Form.pdf

Please also see the FAQ about the cost of certification for non-CNCF members: https://github.com/cncf/k8s-conformance/blob/master/faq.md#what-is-the-cost-of-certification

You'll also need to provide a logo in SVG, EPS or AI format based on these guidelines: https://github.com/cncf/k8s-conformance/blob/master/instructions.md#productyaml

Let me know if you have any questions!

**Comment by NicolasT** [comment]
@taylorwaggoner Glad the results are what's expected. We're currently in the process of becoming a CNCF member, so I guess this PR is on hold until that's finalized?

As for the logo, we'll work on a suitable version and amend the PR accordingly.

**Comment by taylorwaggoner** [comment]
Sounds great!  Thanks, @NicolasT!

**Comment by taylorwaggoner** [comment]
@Zempashi @NicolasT - Your CNCF membership has been processed, so we can move forward with certification soon!  All I need from you is the logo and participation form I mentioned in my previous comment.  Let me know if you have any questions!

**Comment by NicolasT** [comment]
@taylorwaggoner The logo is now in place. We'll take care of the participation form ASAP. Thanks!

**Comment by NicolasT** [comment]
@taylorwaggoner The participation form should have been signed and submitted as well. Anything else you need from us to proceed?

Thank you!

**Comment by taylorwaggoner** [comment]
@NicolasT - I haven't seen the participation form come through yet.  Could you please resend it to me directly at twaggoner@linuxfoundation.org?  Thanks!

**Comment by taylorwaggoner** [comment]
You are now Certified Kubernetes
https://github.com/cncf/landscape/pull/769

**Comment by NicolasT** [comment]
@taylorwaggoner Thanks for this! However, I noticed MetalK8s has a 'gray' background in the landscape which means it's not open-source. However, it most certainly is: https://github.com/Scality/metalk8s. Scality doesn't even have any internal, closed-source version: all development happens directly in the open.

/CC @smaffulli

**Comment by taylorwaggoner** [comment]
@NicolasT thanks for pointing that out!  I've updated your listing and now MetalK8s is showing as open source in the landscape.  https://landscape.cncf.io/organization=scality

**Comment by NicolasT** [comment]
Wonderful :man_dancing: Thanks a lot @taylorwaggoner for handling all of this!

**Pull request merged**
