### PR TITLE
Conformance results for v1.20/ecloud

### PR DESCRIPTION
**Pull request by wxqchimei**
add china mobile ecloud kcs with k8s v1.20.1

### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [x] If this is a new entry, have you submitted a signed [participation form](https://github.com/cncf/k8s-conformance/tree/master/participation-form)?
* [x] Did you include the product/project logo in SVG, EPS or AI format?  
* [x] Does your logo clearly state the name of the product/project and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [ ] If your product/project is open source, did you include the `repo_url`?
* [x] Did you copy and paste the [installation and configuration instructions](https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions) into the README.md file in addition to linking to them?

### CODE REVIEW

**Comment by taylorwaggoner** [comment]
@wxqchimei thanks for submitting.  This mostly looks good. Have you submitted a [participation form](https://github.com/cncf/k8s-conformance/tree/master/participation-form) for this product yet? Also, the description in your PRODUCT.yaml just has the product name - is there any other description you'd like to include? Thanks!

**Comment by wxqchimei** [comment]
@taylorwaggoner thanks for replying. I have already submitted a [participation form](https://github.com/cncf/k8s-conformance/tree/master/participation-form) for this product by DocuSign and added more description in PRODUCT.yaml,can you help getting this merged?

**Comment by taylorwaggoner** [comment]
@wxqchimei thank you for submitting the form, but would it be possible for you re-submit with the information in English as well?  The product.yaml looks great thanks!

**Comment by wxqchimei** [comment]
@taylorwaggoner thanks for replying. The participation from information has been  re-submitted by DocuSign in English.Thanks!

**Comment by taylorwaggoner** [comment]
Thanks @wxqchimei - I noticed that the product name on the participation form doesn't match the product name in your pull request.  Can you confirm which is correct and make sure they say the same name?  Thanks!

**Comment by wxqchimei** [comment]
@taylorwaggoner thank you for pointing out ,KCS is short for China Mobile Kubernetes Container Service,and now i have updated the product.yaml name to KCS,thanks

**Comment by johnSchnake** [comment]
An issue with that version of Sonobuoy caused the Disruptive test to be skipped. You can get a new version here: https://github.com/vmware-tanzu/sonobuoy/releases/tag/v0.53.2 and see more details here: https://sonobuoy.io/docs/v0.53.2/issue1388/

**Comment by wxqchimei** [comment]
@johnSchnake Thanks,I have tested it with Sonobuoy in version of v0.53.0 and v0.20.0, when test in v0.53.0 it reports thart 

> The first test found to be mssing was [k8s.io] [sig-node] NoExecuteTaintManager Multiple Pods [Serial] evicts pods with minTolerationSeconds [Disruptive] [Conformance]

when test in v0.20.0 it workd well.Do I need to retest it with Sobobuoy v0.53.2?

**Comment by taylorwaggoner** [comment]
@johnSchnake is anything else needed on this one? Thanks!

**Comment by taylorwaggoner** [comment]
You are now Certified Kubernetes

**Pull request merged**
