### PR TITLE
Conformance results for v1.18/harmonycloud-installer

### PR DESCRIPTION
**Pull request by WinterZhou**
### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [x] If this is a new entry, have you submitted a signed [participation form](https://github.com/cncf/k8s-conformance/tree/master/participation-form)?
* [x] Did you include the product/project logo in SVG, EPS or AI format?  
* [x] Does your logo clearly state the name of the product/project and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [ ] If your product/project is open source, did you include the `repo_url`?
* [x] Did you copy and paste the [installation and configuration instructions](https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions) into the README.md file in addition to linking to them?

### CODE REVIEW

**Comment by WinterZhou** [comment]
Hi, @taylorwaggoner  The type of product certification is installer, which is not the same product as the distribution certification submitted before.

**Comment by taylorwaggoner** [comment]
@WinterZhou ok great, thanks!  One last thing for this, I see that you included the conformance results and related files for the distribution product.  We already certified that product in #947 so I don't think you need the files here.  I wanted to check to see if you included them for a particular reason.  If not, we can delete.  thanks!

**Comment by WinterZhou** [comment]
@taylorwaggoner This files we want certified installer type production.

**Comment by WinterZhou** [comment]
@taylorwaggoner 
"if you included them for a particular reason. If not, we can delete. thanks!" 
------> you can delete it. thanks!

**Comment by taylorwaggoner** [comment]
You are now Certified Kubernetes
https://landscape.cncf.io/format=card-mode&organization=hangzhou-harmony-cloud-technology&selected=harmonycloud-paa-s-container-platform-install

**Pull request merged**
