### PR TITLE
Add URL format check to tests list

### PR DESCRIPTION
**Pull request by BobyMCbobs**
Updates the docs to note new test for validating URL formatting in the PRODUCT.yaml file found in each product submission.

### CODE REVIEW

**Comment by taylorwaggoner** [comment]
Is this ready to be merged?

**Comment by Riaankl** [comment]
yes, you can merge thank you.

**Comment by BobyMCbobs** [comment]
@taylorwaggoner, the update to the requirements is ready and the bot in production has 14 checks.
Looking for a merge. Thank you!

**Comment by BobyMCbobs** [comment]
Thank you @taylorwaggoner!

**Pull request merged**
