### PR TITLE
Conformance test results for v1.10/jdos (JD.COM TIG)

### PR DESCRIPTION
**Pull request by lovejoy**
vendor: JD.COM
name: Jingdong Datacenter OS
version: v1.10.2
website_url: http://tig.jd.com/en/products/jdos
type: distribution
documentation_url: http://tig.jd.com/docs/jdos
product_logo_url: http://storage.360buyimg.com/cncf/jdtig.ai  or http://storage.360buyimg.com/cncf/jdlogo.ai

### CODE REVIEW

**Comment by taylorwaggoner** [comment]
@lovejoy - Thanks for submitting! Everything in the PR looks good, but it appears we don't have a Participation Form on file for you. Can you please confirm that you have sent one? The form can be found here: https://github.com/cncf/k8s-conformance/tree/master/participation-form. Thanks!

**Comment by lovejoy** [comment]
@taylorwaggoner submitted on DocuSign

**Comment by bladehliu** [comment]
Thank you, Taylor.

**Comment by taylorwaggoner** [comment]
Hi lovejoy,
We try to use high resolution images for the Landscape.  Can you please provide
a different high-res version of your logo (SVG or AI format), or we could
possibly use this one if you prefer:
https://www.sandisk.com/content/dam/sandisk-main/en_us/assets/resources/case-studies/co-brand/jd/cs-jd-logo.svg

Thanks!
Taylor Waggoner
Sr. Operations Analyst  - Cloud Native Computing Foundation
Location & Time-zone: Portland, OR - PT
web:https://www.cncf.io/
email:twaggoner@linuxfoundation.org







On Thu, May 17, 2018 7:36 PM, lovejoy notifications@github.com  wrote:
@taylorwaggoner  submitted on DocuSign

**Comment by lovejoy** [comment]
@taylorwaggoner i will provide a new one tomorrow

**Comment by dankohn** [comment]
Great! @taylorwaggoner, here is the SVG version:

[jdtig-02.svg.zip](https://github.com/cncf/k8s-conformance/files/2027504/jdtig-02.svg.zip)

**Comment by taylorwaggoner** [comment]
You are now Certified Kubernetes

**Comment by lovejoy** [comment]
@taylorwaggoner 
Would you please add the github repo https://github.com/tiglabs to the Kubernetes Distributions & Platforms [spreadsheet](https://docs.google.com/spreadsheets/d/1LxSqBzjOxfGx3cmtZ4EbB_BGCxT_wlxW_xgHVVa23es/edit#gid=0)  and   add  our logo to https://www.cncf.io/certification/software-conformance/  
I have already provide some information you may need in upper commet,and you can contact me for anything you need further.

**Comment by dankohn** [comment]
We'll add you to the page today.

However, https://github.com/tiglabs is a GitHub organization. Is there a
specific repo that includes your Kubernetes distribution, the way that
these do:

https://landscape.cncf.io/grouping=landscape&landscape=certified-kubernetes-distribution,certified-kubernetes-hosted,certified-kubernetes-installer&license=open-source

--
Dan Kohn <dan@linuxfoundation.org>
Executive Director, Cloud Native Computing Foundation https://www.cncf.io
+1-415-233-1000 https://www.dankohn.com

**Comment by lovejoy** [comment]
the repo is https://github.com/tiglabs/jdos

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by dankohn** [comment]
That repo is empty. Once you push the code there we can add it.

--
Dan Kohn <dan@linuxfoundation.org>
Executive Director, Cloud Native Computing Foundation https://www.cncf.io
+1-415-233-1000 https://www.dankohn.com

**Comment by lovejoy** [comment]
all right ,tks a lot

**Comment by dankohn** [comment]
You're now live here: https://landscape.cncf.io/grouping=landscape&landscape=certified-kubernetes-distribution,certified-kubernetes-hosted,certified-kubernetes-installer&selected=jd-com-tig-jingdong-datacenter-os

**Pull request merged**
