### PR TITLE
Conformance results for v1.8/ket

### PR DESCRIPTION
**Pull request by ikester**
vendor: Apprenda
name: Kismatic Enterprise Toolkit (KET)
version: v1.6.0
website_url: https://apprenda.com/kismatic/
documentation_url: https://github.com/apprenda/kismatic/tree/v1.6.0/docs
product_logo_url: https://raw.githubusercontent.com/apprenda/kismatic/v1.6.0/docs/logo/KET_logo.png

### CODE REVIEW

**Comment by dankohn** [comment]
@ikester, thanks for making the submission. It looks OK to me, though I will mention that you are using a confusing versioning scheme where Kismatic Enterprise Toolkit 1.6.0 is based on Kubernetes 1.8.0. Is that what you intended?

**Comment by ikester** [comment]
@dankohn I can see how it can be confusing. We use semver and this is consistent with our previous releases. Furthermore, it is likely that in the near future you will be able to install different versions of Kubernetes with the same version of KET. So we intentionally keep the KET version decoupled from the K8s one.

**Comment by dankohn** [comment]
Ok, thanks for explaining.

**Comment by kbarnard10** [comment]
+1

**Comment by WilliamDenniss** [comment]
@ikester, a reminder that to make the first wave of certifications next week you need to have your company's participation form submitted and verified ASAP.

**Comment by ikester** [comment]
Thanks William. I see that the form has been received the the labels adjusted to reflect that.

**Pull request merged**
