### PR TITLE
Linaro Developer Cloud(Arm64) conformance with Kubernetes 1.17

### PR DESCRIPTION
**Pull request by kevin-zhaoshuai**
Signed-off-by: Kevin Zhao <kevin.zhao@linaro.org>

### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [x] If this is a new entry, have you submitted a signed [participation form](https://github.com/cncf/k8s-conformance/tree/master/participation-form)?
* [x] Did you include the product/project logo in SVG, EPS or AI format?  
* [x] Does your logo clearly state the name of the product/project and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [x] Did you copy and paste the [installation and configuration instructions](https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions) into the README.md file in addition to linking to them?

### CODE REVIEW

**Comment by taylorwaggoner** [comment]
@kevin-zhaoshuai thanks for posting! Could you please add the primary GitHub `repo_url` that contains the source to the PRODUCT file, per [these guidelines](https://github.com/cncf/k8s-conformance/blob/master/instructions.md#productyaml)? This will allow us to show your product as open source on the landscape.  Thanks!

**Comment by kevin-zhaoshuai** [comment]
@taylorwaggoner Hey, thanks for the review. I've added the repo_url as we are totally based on open source Openstack magnum service.

**Comment by taylorwaggoner** [comment]
@kevin-zhaoshuai we need the source to be hosted or mirrored to GitHub for the project to show as open source on the landscape. Directions to do so are here: https://help.github.com/en/github/getting-started-with-github/finding-ways-to-contribute-to-open-source-on-github#open-source-projects-with-mirrors-on-github

Let us know if you have any questions!

**Comment by kevin-zhaoshuai** [comment]
@taylorwaggoner Hi, I've added the mirror repo of magnum to https://github.com/Linaro/magnum, thanks for the guide.

**Comment by kevin-zhaoshuai** [comment]
@taylorwaggoner Ping， any progress for this? Thanks!

**Comment by taylorwaggoner** [comment]
You are now Certified Kubernetes. Sorry for the delay!
https://landscape.cncf.io/format=card-mode&selected=linaro-developer-cloud-kubernetes-service

**Comment by taylorwaggoner** [comment]
Also, I just realized I forgot to add the repo, so am adding that now so the product shows as OS.  Thanks!

**Comment by kevin-zhaoshuai** [comment]
Thanks a lot!

**Pull request merged**
