### PR TITLE
Conformance results for OpenShift 4.3 (v1.16 Kubernetes)

### PR DESCRIPTION
**Pull request by smarterclayton**

### CODE REVIEW

**Comment by taylorwaggoner** [comment]
@smarterclayton, thanks for submitting!  Your results look good, but I noticed that you have a broken link in your README -> https://docs.openshift.com/container-platform/latest/install_config/install/advanced_install.html.  Could you please paste the steps to reproduce into the README, rather than linking to your documentation? Thank you!

**Comment by smarterclayton** [comment]
I'm not sure what you mean, comparing to https://github.com/cncf/k8s-conformance/blob/master/v1.16/rancher/README.md which links to the doc?

**Comment by smarterclayton** [comment]
Updated the commit to include links to the docs (4.3 / 1.16 is verified on nightly builds, which I linked)

**Comment by smarterclayton** [comment]
PTAL

**Comment by smarterclayton** [comment]
@taylorwaggoner ping

**Comment by taylorwaggoner** [comment]
@smarterclayton, I apologize for the big delay here.  We are tightening the requirements for the README files and have added some [instructions to our FAQ ](https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions).

Could you please make sure that all of the README's in this PR have the instructions pasted into the file, in addition to providing the URL?  

Thank you!

**Comment by smarterclayton** [comment]
What specific instructions do you need?  Which platforms?  OpenShift installs on roughly 28 major configurations (cloud providers, security settings, configured modes) as well as via hosted services.  How much of the install documentation should we copy (such as instructions around how to configure your AWS account, etc)?  The download instructions may depend on whether you are a customer, an evaluation user, a hosted service user, etc.  I don't think the instructions in the FAQ provide enough detail for me to fill out the PR at this time, especially regarding the bar and expectations.

Also, I don't see any context around the change to the FAQ and policy (it was a push to master, no associated PR or issue that I can see?), and I'd like to understand the context a bit more.  How was this decision made?  Was this requested by the legal team, the Kubernetes community, the conformance WG?  What's the goal behind the change?

**Comment by smarterclayton** [comment]
@dankohn since I saw you were the one pushing the commit

**Comment by dankohn** [comment]
@smartclayton As you know, the goal has always been for users to be able to replicate the conformance test results. We have started asking for more documentation because of submissions that linked to non-existent pages and/or pages with very little content.

That's obviously not the case here. We'd request that you link to the documentation as the canonical, up-to-date source for all possible installations, and then paste in the install directions for *one* of the most common installs.

In particular, we're asking if there are any specific configuration directions as part of the install that are necessary to get the conformance tests to pass (e.g., disable RBAC, enable certain service accounts, etc.).

If you don't think this request is appropriate, we're happy to escalate to SIG Architecture and we can discuss changing the process.

**Comment by smarterclayton** [comment]
Ok - how detailed should be the pasted in install directions?  We have (I think) 182 individual things to check or know, even though only 3-10 of those are technically required (including pre check stuff about an account)?  Or are you ok with "Go to the place we tell you to get the installer, setup your account as directed, then run the installer and do X, Y, and Z"?   We document the series of steps required to pass conformance as part of the script which is referenced by the README, do you expect those steps to be copied into the readme as well?

**Comment by dankohn** [comment]
Please use your judgment. We're looking for enough info that a reasonably knowledgable user (for example, a Certified Kubernetes Administrator) could follow them and get the same results. But copying and pasting the detailed directions may be easiest, rather than you needing to do any new work.

**Comment by smarterclayton** [comment]
The detailed directions are at an evolving website which is updated frequently, so that would lead to an even more likely outcome of being out of date.

I understand the desire to ensure the README ensures the install succeeds for reproduction, and I agree totally on the individual "after install, do this to ensure tests run the way the test configures" steps being documented.  But what I'm struggling with is how linking to stable product documentation is worse than duplicating stable product documentation into the README.  I would expect almost everyone submitting conformance has official documentation of some sort.  If that doc is deficient, we can't fix that by duplicating it in the README.

**Comment by dankohn** [comment]
We’d really like both. Please put at the top that the link is the up to date documentation and then paste in the point in time documentation that is correct at the time of certification.

**Comment by smarterclayton** [comment]
Updated with links to the official installation site and docs, and then a brief set of steps for installing on AWS.  PTAL.

**Comment by dankohn** [comment]
LGTM

**Comment by taylorwaggoner** [comment]
Thank you, @smarterclayton !  You are now Certified Kubernetes

**Pull request merged**
