### PR TITLE
Conformance result for v1.14/inspur-incloud-arm64

### PR DESCRIPTION
**Pull request by packyzbq**

### CODE REVIEW

**Comment by LambertShi001** [comment]
There was inspur arm architecture k8s PR:
https://github.com/cncf/k8s-conformance/pull/636

There is no need for repeated authentication.

Thanks.

**Comment by packyzbq** [comment]
> There was inspur arm architecture k8s PR:
> #636
> 
> There is no need for repeated authentication.
> 
> Thanks.

Hi, I explained the reason in #659

**Comment by taylorwaggoner** [comment]
@packyzbq thank you for submitting.  Please send in a signed [participation form](https://github.com/cncf/k8s-conformance/tree/master/participation-form) for your product(s).  Thank you!

**Comment by packyzbq** [comment]
> @packyzbq thank you for submitting. Please send in a signed [participation form](https://github.com/cncf/k8s-conformance/tree/master/participation-form) for your product(s). Thank you!

Hi, we have sent the participation form, please check.

**Comment by crystal-qw** [comment]
@taylorwaggoner Inspur has completed cncf certification, all services are based on container development, no need to do this certification。

**Comment by crystal-qw** [comment]
@taylorwaggoner As far as I know, inspur cloud is the sponsor of CNCF, and Inspur Open Platform is the only product of inspur container cloud.

**Comment by donaldliu** [comment]
@crystal-qw I am Donald Liu, a CNCF staff.  Can you let me know which company you represent?

**Comment by Seagullfy** [comment]
@taylorwaggoner Hi，Inspur has only one container cloud and has been certified. The results of the certification are as follows，https://github.com/cncf/k8s-conformance/pull/635&https://github.com/cncf/k8s-conformance/pull/636

**Comment by dankohn** [comment]
I'm concerned to see multiple accounts arguing for things here without anyone clearly representing themselves as working for Inspur. @packyzbq @crystal-qw @Seagullfy please contact @donaldliu on WeChat at https://web.wechat.com/donaldliu1874 and you can discuss the situation in Chinese.

Note that any division of a CNCF member is welcome to certify, but that we need for there to be only one certification per product.

I'm going to close this issue for now, but I am very happy to reopen it after you have spoken to Donald and sorted out the confusion.

**Comment by donaldliu** [comment]
I have reached out the 2 companies of Inspur Group and they agree that we can all ignore comments from unrelated or unknown GitHub Ids ("crystal-qw" and "Seagullfy") and can continue processing the PR.  Please re-open this PR or suggest otherwise.

**Comment by taylorwaggoner** [comment]
You are now Certified Kubernetes
https://landscape.cncf.io/format=card-mode&selected=inspur-icks

**Pull request merged**
