### PR TITLE
docs: add AKS Engine v1.16 conformance results

### PR DESCRIPTION
**Pull request by jackfrancis**
Add 1.16 conformance results for a "vanilla" AKS Engine (@ v0.41.0) cluster:

- 1 control plane node
- 3 Linux (Ubuntu 16.04-LTS) nodes

Running 1.16.0:

https://github.com/kubernetes/kubernetes/releases/tag/v1.16.0

### CODE REVIEW

**Comment by dghubble** [comment]
sonobuoy master at this time of writing:

```
WARN[0001] The maximum supported Kubernetes version is 1.15.99, but the server version is v1.16.0. Sonobuoy will continue but unexpected results may occur.
```

**Comment by lachie83** [comment]
That's a hardcoded value It should run the conformance suite of the detected version as evident in the logs

**Comment by taylorwaggoner** [comment]
You are now Certified Kubernetes

**Comment by kdomanski** [comment]
I appears that these test results are ineligible for certification.

According to the submitted junit_01.xml, the following tests have been skipped:
```
[sig-scheduling] NoExecuteTaintManager Multiple Pods [Serial] evicts pods with minTolerationSeconds [Conformance]
[sig-scheduling] NoExecuteTaintManager Single Pod [Serial] removing taint cancels eviction [Conformance]
```
cc @taylorwaggoner

**Comment by dankohn** [comment]
@lachie83 Could you please comment?

**Comment by guusvw** [comment]
Any updates on that topic?
Cc @dankohn

**Pull request merged**
