### PR TITLE
Rename product - v1.14/ocsk to v1.14/olcne

### PR DESCRIPTION
**Pull request by mark-au**
Rename of product from #715, see #835 for discussion on how to proceed. 
Updated README.md to include detailed validation instructions not present in original submission. 

### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [x] If this is a new entry, have you submitted a signed [participation form](https://github.com/cncf/k8s-conformance/tree/master/participation-form)?
* [x] Did you include the product/project logo in SVG, EPS or AI format?  
* [x] Does your logo clearly state the name of the product/project and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [x] If your product/project is open source, did you include the `repo_url`?
* [x] Did you copy and paste the [installation and configuration instructions](https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions) into the README.md file in addition to linking to them?

### CODE REVIEW

**Comment by Djelibeybi** [comment]
Reviewed-by: Avi Miller <avi.miller@oracle.com>

**Comment by taylorwaggoner** [comment]
Great, thank you!
https://landscape.cncf.io/format=card-mode&organization=oracle&selected=oracle-linux-cloud-native-environment

**Comment by Djelibeybi** [comment]
> Great, thank you!
> https://landscape.cncf.io/format=card-mode&organization=oracle&selected=oracle-linux-cloud-native-environment

Hey @taylorwaggoner -- how do we get the Twitter handle changed to @OracleLinux for this card?

**Comment by dankohn** [comment]
@Djelibeybi Updated.

**Comment by Djelibeybi** [comment]
> @Djelibeybi Updated.

Awesome, thanks!

**Pull request merged**
