### PR TITLE
Supergiant.io Control Conformance Results

### PR DESCRIPTION
**Pull request by eldridgeh**
We have included both e2e.log and junit_01.xml files.
Thank you.

### CODE REVIEW

**Comment by taylorwaggoner** [comment]
@eldridgeh thanks for submitting!  A couple quick questions.  Is Supergiant Control the same product as https://landscape.cncf.io/format=card-mode&selected=supergiant?   It was noted in your participation form that "Supergiant Control Plane" was one of the product names, but I just wanted to make sure. 

Also, in your PRODUCT.yaml file, please update the "type" to be distribution, hosted, or installer per [these guidelines](https://github.com/cncf/k8s-conformance/blob/master/instructions.md#productyaml).  We currently have Supergiant listed as a distribution.  

Thanks!

**Comment by eldridgeh** [comment]
@taylorwaggoner Yes, Supergiant Control is the same product as Supergiant Control Plane. I also changed our type to 'installer.'
Thank you again!

**Comment by taylorwaggoner** [comment]
Thanks @eldridgeh.  Can you confirm that Supergiant Control is the same product as the one we already have listed in the landscape: [https://landscape.cncf.io/format=card-mode&selected=supergiant](https://landscape.cncf.io/format=card-mode&selected=supergiant)

If so, I will re-categorize it as an installer (instead of distribution) and will update your entry in the [Kubernetes Distributions & Platforms](https://docs.google.com/spreadsheets/d/1LxSqBzjOxfGx3cmtZ4EbB_BGCxT_wlxW_xgHVVa23es/edit#gid=0) document.  

If it is a completely different product than the Supergiant product we originally certified, please let me know.  Thanks!

**Comment by eldridgeh** [comment]
@taylorwaggoner Hey it's the same product, and is a vanilla Kubernetes installer. If you could update our entry that would be great!

The brand is Supergiant.io and the product the creates vanilla clusters is called Control. It is the same product as before.

Thank you again!

**Comment by taylorwaggoner** [comment]
You are now Certified Kubernetes
https://landscape.cncf.io/format=card-mode&selected=supergiant-control

**Pull request merged**
