### PR TITLE
Rename for v1.21/DAP Kubernetes Service Hatoba

### PR DESCRIPTION
**Pull request by syyama-net**
### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [x] If this is a new entry, have you submitted a signed [participation form](https://github.com/cncf/k8s-conformance/tree/master/participation-form)?
* [x] Did you include the product/project logo in SVG, EPS or AI format?  
* [x] Does your logo clearly state the name of the product/project and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [ ] If your product/project is open source, did you include the `repo_url`?
* [x] Did you copy and paste the [installation and configuration instructions](https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions) into the README.md file in addition to linking to them?

### CODE REVIEW

**Comment by taylorwaggoner** [comment]
@syyama-net thank you! please make sure to submit a new [participation form](https://github.com/cncf/k8s-conformance/tree/master/participation-form) for this name change. thanks!

**Comment by taylorwaggoner** [comment]
@syyama-net checking in, thanks!

**Comment by syyama-net** [comment]
@taylorwaggoner  
Our team member sent a new participation form for our service name change by email.

Please confirm.

**Comment by taylorwaggoner** [comment]
@syyama-net Could you please re-send the form to conformance@cncf.io?  Thanks!

**Comment by syyama-net** [comment]
@taylorwaggoner
> @syyama-net Could you please re-send the form to [conformance@cncf.io](mailto:conformance@cncf.io)? Thanks!

I have just replied to you. Please check the form.

And what is the bot message?
I think there are no errors in e2e.log.

Thanks.

**Comment by Riaankl** [comment]
@syyama-net I removed all the labels and let the cncf-ci bot do another check and all came out fine.
I also manually checked the log file and can not tell what the bot picked up initially.

**Comment by taylorwaggoner** [comment]
@syyama-net received the participation agreement, thanks!

Is this pull request the same as #1684? Or is something different? This product is already certified for v1.21 so you don't need to submit new test results - we just need to have the product renamed everywhere.

**Comment by syyama-net** [comment]
@taylorwaggoner 
> Is this pull request the same as #1684?

Yes, it is the same issue, so you can close #1684.

Thanks.

**Comment by taylorwaggoner** [comment]
@syyama-net thanks! As I mentioned in my last comment, since this product is already certified for 1.21, you don't need to submit new results, just the product.yaml and README with the new name displayed.  This is simply a name change request, correct? Thanks!

**Comment by syyama-net** [comment]
@taylorwaggoner 
Yes, please change our service name only.

**Comment by syyama-net** [comment]
@taylorwaggoner thank you for your advice.
I have changed the directory and files.

Could you please check?

Thank

**Comment by Riaankl** [comment]
@syyama-net please ignore the CNCF-CI bot comments that was posted in the last hour, we are running some test on the bot.

**Comment by syyama-net** [comment]
@taylorwaggoner How is it going?

**Comment by taylorwaggoner** [comment]
@syyama-net thanks for updating.  One last thing - instead of deleting the original PRODUCT file, could you please rename and update the original one?  When we change a product name, we just want to update all of the files for the original pull request, not add new files. Thanks!

**Comment by syyama-net** [comment]
@taylorwaggoner I closed this issue by mistake, please check #1820

**Pull request closed without merging**
