### PR TITLE
Conformance results for Giant Swarm on AWS

### PR DESCRIPTION
**Pull request by puja108**
vendor: Giant Swarm
name: Managed Kubernetes on AWS
version: stable-2017-11-17
website_url: https://giantswarm.io
documentation_url: https://docs.giantswarm.io
product_logo_url: https://www.dropbox.com/s/kydb137cjsix7du/giantswarm_ant.png

Note: I ran the tests as documented in https://github.com/cncf/k8s-conformance/blob/master/instructions.md twice, but I'm not getting any `versions.txt` out of sonobuoy. Any pointers as to how to get it or is it needed at all?

### CODE REVIEW

**Comment by dankohn** [comment]
Apologies, we still need to update our directions on manually including versions.txt for 1.7.

@timothysc @WilliamDenniss Could you please help us out?

**Comment by puja108** [comment]
Did it manually as mentioned in https://github.com/cncf/k8s-conformance/issues/55

**Comment by kbarnard10** [comment]
+1. Signed participation form needed. 

Please follow the instructions here to submit it: either via [PDF](https://github.com/cncf/k8s-conformance/blob/master/participation-form/Certified_Kubernetes_Form.pdf) or [DocuSign](https://na3.docusign.net/Member/PowerFormSigning.aspx?PowerFormId=ba08f93a-65ca-4c5d-8210-d5c858bb9208)

**Comment by puja108** [comment]
done, signed on DocuSign

**Pull request merged**
