### PR TITLE
Add Huawei Cloud CCE v1.23 conformance test result

### PR DESCRIPTION
**Pull request by RainbowMango**
### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [x] If this is a new entry, have you submitted a signed [participation form](https://github.com/cncf/k8s-conformance/tree/master/participation-form)?
* [x] Did you include the product/project logo in SVG, EPS or AI format?  
* [x] Does your logo clearly state the name of the product/project and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [x] If your product/project is open source, did you include the `repo_url`?
* [x] Did you copy and paste the [installation and configuration instructions](https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions) into the README.md file in addition to linking to them?

### CODE REVIEW

**Comment by RainbowMango** [comment]
cc @taylorwaggoner, please let me know if the `content type` of `website_url` and `documentation_url` must be `text/html`.
Thanks.

**Comment by taylorwaggoner** [comment]
@riaankl could you please help here, thanks!

**Comment by Riaankl** [comment]
@taylorwaggoner we are a the moment looking into the reason the bot keep checking this PR.

**Comment by RainbowMango** [comment]
> @taylorwaggoner we are a the moment looking into the reason the bot keep checking this PR. The URL's seem OK though.

@Riaankl Any update?

@taylorwaggoner Should we wait until we figure this out?

I'm asking because I want to know if there is anything I need to do( and I keep receiving annoying notifications :)).

**Comment by Riaankl** [comment]
@RainbowMango the bot keep checking all open PRs for changes.
Some times the Bot's URL check get a correct `text/html` resoponce and sometime a `application/json` response. Every time it get a `application/json` response it will issue a new error message. Sorry for the inconveniance, as we can not contol the response of the header request.
Soon as the PR merge it will stop spamming us all. :-)

**Comment by Riaankl** [comment]
> Thanks @Riaankl.
> 
> Then, @taylorwaggoner Can you help to confirm if the header must be `text/html`?

The "header must be `text/html`" is just a way to verify if the URL give a valid return.
Both URL's in question is valid, they are jsut confusing the Bot a little. We are working on a way around it.
That should not affect you PR negatively.

**Comment by taylorwaggoner** [comment]
You are now Certified Kubernetes

**Pull request merged**
