### PR TITLE
Conformance results for v1.18/kubedee

### PR DESCRIPTION
**Pull request by schu**
### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [ ] ~~If this is a new entry, have you submitted a signed [participation form](https://github.com/cncf/k8s-conformance/tree/master/participation-form)?~~ Not a new entry.
* [x] Did you include the product/project logo in SVG, EPS or AI format?  
* [x] Does your logo clearly state the name of the product/project and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [x] If your product/project is open source, did you include the `repo_url`?
* [x] Did you copy and paste the [installation and configuration instructions](https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions) into the README.md file in addition to linking to them?

Please note that one test failed:

```
Summarizing 1 Failure:

[Fail] [sig-cli] Kubectl client Guestbook application [It] should create and stop a working application  [Conformance]
/workspace/anago-v1.17.4-beta.0.54+12bf0cb73007af/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl/kubectl.go:2228

Ran 278 of 4842 Specs in 4912.384 seconds
FAIL! -- 277 Passed | 1 Failed | 0 Pending | 4564 Skipped
--- FAIL: TestE2E (4912.53s)
FAIL
```

Running the tests a second time didn't make the test pass. At least on Windows, the test is known to be flaky (fix merged for 1.18 in https://github.com/kubernetes/kubernetes/pull/85642).

I ran the tests on Ubuntu; is this a problem with the test or on my side?

Thanks.

### CODE REVIEW

**Comment by dankohn** [comment]
Yes, could you please post to #k8s-conformance on slack.k8s.io and get advice on getting the test to pass. Or else, you might just want to certify for 1.18.

**Comment by schu** [comment]
Did certify for 1.18 instead, all tests passed. Thanks!

**Comment by taylorwaggoner** [comment]
@schu great! Please post the setup instructions  from https://github.com/schu/kubedee/blob/master/contrib/terraform/hetzner-cloud/README.md into the README here and we should be good to go. Thanks!

**Comment by schu** [comment]
> Please post the setup instructions from https://github.com/schu/kubedee/blob/master/contrib/terraform/hetzner-cloud/README.md into the README

@taylorwaggoner done, thanks!

**Comment by taylorwaggoner** [comment]
You are now Certified Kubernetes

**Pull request merged**
