### PR TITLE
Here are the Kubernetes v1.19.8 conformance test results from a QingC…

### PR DESCRIPTION
**Pull request by ruiyaoOps**
…loud KubeSphere Engine (QKE) cluster, along with product description and readme.Thanks

Signed-off-by: yaorui <yaorui@yunify.com>

### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [ ] If this is a new entry, have you submitted a signed [participation form](https://github.com/cncf/k8s-conformance/tree/master/participation-form)?
* [x] Did you include the product/project logo in SVG, EPS or AI format?  
* [x] Does your logo clearly state the name of the product/project and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [x] If your product/project is open source, did you include the `repo_url`?
* [x] Did you copy and paste the [installation and configuration instructions](https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions) into the README.md file in addition to linking to them?

### CODE REVIEW

**Comment by ErinThacker** [comment]
You are certified Kubernetes.

**Comment by ruiyaoOps** [comment]
@ErinThacker  
Excuse me, why is QKE not displayed in 'Certified Kubernetes - Hosted 'after conformance certification, is there anything I need to do?
image

**Comment by ErinThacker** [comment]
@ruiyaoOps  - I'll get it on the landscape now. My apologies for the oversight!

**Comment by ruiyaoOps** [comment]
@ErinThacker  Thanks a lot, after you put it on the landscape, please @ me.

**Comment by ruiyaoOps** [comment]
image
Excuse me, why is QKE still not displayed in 'Certified Kubernetes - Hosted '? @ErinThacker 
What happened?

**Comment by ruiyaoOps** [comment]
https://github.com/cncf/k8s-conformance/issues/1544
I had created an issue to resolve this problem.  @ErinThacker

**Pull request merged**
