### PR TITLE
Conformance test results v1.15/metakube-aws, v1.15/metakube-openstack

### PR DESCRIPTION
**Pull request by cbeneke**

### CODE REVIEW

**Comment by cbeneke** [comment]
Sorry, miscommunication over here. Will open another PR later

**Comment by taylorwaggoner** [comment]
@cbeneke, thanks for submitting!  Wanted to check in with you regarding the logo.  You linked a white SysEleven logo, but we do not use white logos on the landscape. Would you like us to change it to be black instead, or perhaps use a different logo of your choice?  Thanks!

**Comment by cbeneke** [comment]
Hey, thanks for asking, we will provide a different logo and update the PR

**Comment by cbeneke** [comment]
rebased against master and updated logo source

**Comment by taylorwaggoner** [comment]
You are now Certified Kubernetes

**Pull request merged**
