### PR TITLE
Conformance results for v1.9/heptio

### PR DESCRIPTION
**Pull request by liztio**
vendor: Heptio
name: AWS-Quickstart
version: 0e5d5a9da1e4a874fc2dd8a184b295a9879a0876 
website_url: https://aws.amazon.com/quickstart/architecture/heptio-kubernetes
documentation_url: https://github.com/heptio/aws-quickstart
product_logo_url: https://d1.awsstatic.com/partner-network/QuickStart/datasheets/heptio-kubernetes-qs.38d79785e9e107b624e911225e79066ad378e019.png

### CODE REVIEW

**Comment by taylorwaggoner** [comment]
@liztio - Your client version needs to be 1.9 or higher

**Comment by dankohn** [comment]
@liztio More specifically, we're still accepting certifications for 1.8, but the client and server version need to pass. Please see step 5 of https://github.com/cncf/k8s-conformance/blob/master/reviewing.md

**Comment by liztio** [comment]
@taylorwaggoner @dankohn updated, sorry for the delay!

**Comment by taylorwaggoner** [comment]
Thanks @liztio! You are now Certified Kubernetes

**Pull request merged**
