### PR TITLE
Conformance results for v1.21/d2iq

### PR DESCRIPTION
**Pull request by dkoshkin**
### Pre-submission checklist:

```
vendor: D2iQ
name: Konvoy
version: v2.0.0-beta.6
website_url: https://d2iq.com/solutions/ksphere/konvoy
documentation_url: https://docs.d2iq.com/ksphere/konvoy/
product_logo_url: https://assets.d2iq.com/production/assets/D2iQ-logo.svg
type: distribution
description: 'Konvoy is a standalone distribution of Kubernetes that includes a native Kubernetes cluster pre-packaged for deployment with a complement of best-in-class add-on services enabled by default and ready for immediate use.'

```

*Please check each of these after submitting your pull request:*

* [ ] If this is a new entry, have you submitted a signed [participation form](https://github.com/cncf/k8s-conformance/tree/master/participation-form)?
* [ ] Did you include the product/project logo in SVG, EPS or AI format?  
* [ ] Does your logo clearly state the name of the product/project and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [ ] If your product/project is open source, did you include the `repo_url`?
* [x] Did you copy and paste the [installation and configuration instructions](https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions) into the README.md file in addition to linking to them?

### CODE REVIEW

**Comment by dkoshkin** [comment]
> The first test found to be mssing was [sig-node] NoExecuteTaintManager Multiple Pods [Serial] evicts pods with minTolerationSeconds [Disruptive] [Conformance]

May be caused by https://github.com/vmware-tanzu/sonobuoy/issues/1388.
Will rerun with the last known good version v0.50.0.

**Comment by Riaankl** [comment]
We traced it back to Sonobuoy and @johnSchnake fixed it with this [PR](https://github.com/vmware-tanzu/sonobuoy/pull/1390).
If you rerun Sonobuoy you should get the correct results to submit.

**Comment by johnSchnake** [comment]
Sorry for the inconvenience! I'm going through the PRs here now to see if anyone else was impacted in this way.

**Comment by Riaankl** [comment]
> Sorry for the inconvenience! I'm going through the PRs here now to see if anyone else was impacted in this way.

Thanks for helping to fix it. :smile:

**Comment by dkoshkin** [comment]
Thank you for the quick response! I was able to rerun the job with `v0.53.2` and see the missing test `[sig-node] NoExecuteTaintManager Multiple Pods [Serial] evicts pods with minTolerationSeconds [Disruptive]`.

**Comment by dkoshkin** [comment]
Hi @taylorwaggoner would appreciate a review here. Thank you!

**Comment by taylorwaggoner** [comment]
You are now Certified Kubernetes

**Comment by supershal** [comment]
Thank you @taylorwaggoner

**Pull request merged**
