### PR TITLE
Conformance results for v1.23/inspur-aistation-amd64

### PR DESCRIPTION
**Pull request by KangYingjie0**
### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [ ] If this is a new entry, have you submitted a signed [participation form](https://github.com/cncf/k8s-conformance/tree/master/participation-form)?
* [x] Did you include the product/project logo in SVG, EPS or AI format?  
* [x] Does your logo clearly state the name of the product/project and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [ ] If your product/project is open source, did you include the `repo_url`?
* [x] Did you copy and paste the [installation and configuration instructions](https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions) into the README.md file in addition to linking to them?

### CODE REVIEW

**Comment by taylorwaggoner** [comment]
@KangYingjie0 is this different than #1850? Thanks

**Comment by KangYingjie0** [comment]
@taylorwaggoner Thanks for your response, they are different products. The product we are submitting now is a platform software for AI development and training. And #1850 is a platform for AI inference.

**Comment by taylorwaggoner** [comment]
@KangYingjie0 but both products are called AIStation?  Could you possibly adjust the name on one or both products so that we can have different listings for them? We can't use the same exact name. So like AIStation Inference, or AIStation Training?

**Comment by KangYingjie0** [comment]
@taylorwaggoner OK. After internal discussion, we modified the product name. Please have a look.

**Comment by taylorwaggoner** [comment]
@KangYingjie0 great thanks!  We have the other AIStation product listed as a distribution. Could you please review the [definitions](https://github.com/cncf/k8s-conformance/blob/master/faq.md#what-is-a-distribution-hosted-platform-and-an-installer) and let me know if you wish to keep it as hosted? Thanks

**Comment by KangYingjie0** [comment]
Yes, your are right. I have changed the type of PRODUCT.type to distribution. Is there anything else I should do? Thanks.

**Comment by KangYingjie0** [comment]
@taylorwaggoner Yes, your are right. I have changed the type of PRODUCT.type to distribution. Is there anything else I should do? Thanks.

**Comment by taylorwaggoner** [comment]
You are now Certified Kubernetes
https://landscape.cncf.io/card-mode?organization=inspur-group&selected=inspur-ai-station-training-platform

**Pull request merged**
