### PR TITLE
Conformance results for v1.10/kops

### PR DESCRIPTION
**Pull request by justinsb**

### CODE REVIEW

**Comment by taylorwaggoner** [comment]
You are now Certified Kubernetes

**Comment by dankohn** [comment]
@justinsb Since kops always downloads and installs vanilla, upstream Kubernetes, I believe we should classify it as an installer, not a distribution. Could you please see the definitions at https://github.com/cncf/k8s-conformance/blob/master/faq.md and confirm.

**Comment by justinsb** [comment]
@dankohn I wasn't sure - kops can install additional software - in particular it can install CNI providers.  But we run official kubernetes - we don't do patches that we don't upstream first.

**Comment by dankohn** [comment]
Based on that, I’ll switch it. Thanks.

**Pull request merged**
