### PR TITLE
OpenShift 1.9 conformance result

### PR DESCRIPTION
**Pull request by smarterclayton**

### CODE REVIEW

**Comment by taylorwaggoner** [comment]
@smarterclayton - Please take a look at and update the version.txt file: the Server Version needs to read "{Major:"1", Minor:"9"...." before we can approve.  Thanks!

**Comment by smarterclayton** [comment]
Why?  All plus means is that we are past the major commit version.  That’s how Kube generates the value.

**Comment by taylorwaggoner** [comment]
The Client version is fine, but the Server version is missing the major and minor info:

+Server Version: version.Info**{Major:"", Minor:"",** GitVersion:"v1.9.1+a0ce1bc657", GitCommit:"a0ce1bc", GitTreeState:"clean", BuildDate:"2018-04-30T12:45:13Z", GoVersion:"go1.9", Compiler:"gc", Platform:"linux/amd64"}

**Comment by smarterclayton** [comment]
Ahh, that’s new.  Sorryz

**Comment by smarterclayton** [comment]
Updated, sorry for the delay.

**Comment by taylorwaggoner** [comment]
Looks great!  You are now Certified Kubernetes.

**Pull request merged**
