### PR TITLE
Add conformance test results for 1.14/docker-desktop-for-mac

### PR DESCRIPTION
**Pull request by ulrich**
Signed-off-by: Ulrich VACHON <ulrich.vachon@docker.com>

### CODE REVIEW

**Comment by taylorwaggoner** [comment]
@ulrich both of your PRs look good, but one small thing before certification.  Could you please delete the preferences_kub.png and version.txt file from each PR?  Thanks!

**Comment by ulrich** [comment]
> @ulrich both of your PRs look good, but one small thing before certification. Could you please delete the preferences_kub.png and version.txt file from each PR? Thanks!

OK. Thank you @taylorwaggoner.

**Comment by ulrich** [comment]
@taylorwaggoner done, thank you for support.

**Comment by taylorwaggoner** [comment]
You are now Certified Kubernetes

**Pull request merged**
