### PR TITLE
Conformance results for v1.18/CloudControl AppZ Platform

### PR DESCRIPTION
**Pull request by skumarpi**
### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [x] If this is a new entry, have you submitted a signed [participation form](https://github.com/cncf/k8s-conformance/tree/master/participation-form)?
* [x] Did you include the product/project logo in SVG, EPS or AI format?  
* [x] Does your logo clearly state the name of the product/project and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [x] If your product/project is open source, did you include the `repo_url`?
* [x] Did you copy and paste the [installation and configuration instructions](https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions) into the README.md file in addition to linking to them?

### CODE REVIEW

**Comment by amye** [comment]
@skumarpi: can you update this PR? It needs to reference the release to let the cncf-ci bot review the tests.

**Comment by ErinThacker** [comment]
@skumarpi - can you provide your signed participation form? I'm not finding it in our files.

**Comment by skumarpi** [comment]
We just sent the signed participation form to conformance@cncf.io

Let me know you are able to verify. Also attaching it here.
[Certified Kubernetes Conformance Program.pdf](https://github.com/cncf/k8s-conformance/files/6418843/Certified.Kubernetes.Conformance.Program.pdf)

**Comment by skumarpi** [comment]
Can we know the next step on this, believe we submitted everything as requested.

**Comment by skumarpi** [comment]
@ErinThacker 

Can we get an update on this request please.

**Comment by psganni** [comment]
@amye @ErinThacker @idvoretskyi Please advise us on the next steps. Thanks

**Comment by ErinThacker** [comment]
You are now Certified Kubernetes.

**Comment by psganni** [comment]
Erin and the team,

This is exciting news for us. Thanks for your assistance.

Prasad Ganni
Head of Platform Delivery
Cloud Control Solutions <https://www.ecloudcontrol.com>

**Pull request merged**
