### PR TITLE
Conformance results for v1.17/kublr

### PR DESCRIPTION
**Pull request by dmitry-irtegov**
Hello!  This is conformance results for kublr v1.17.0.

### CODE REVIEW

**Comment by taylorwaggoner** [comment]
@dmitry-irtegov thanks for submitting!  The results look great, but there's one quick thing to fix.  We've recently been [tightening our requirements](https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions
) for the README file.  Could you please copy and paste the installation/configuration instructions into the README, in addition to the URL you provided?
Thanks!

**Comment by dmitry-irtegov** [comment]
Hello again!  I copied and slightly adapted pages from our installation guides to the README.md, hope this helps.

**Comment by taylorwaggoner** [comment]
Thanks! You are now Certified Kubernetes

**Comment by dmitry-irtegov** [comment]
Thank you!!!

**Pull request merged**
