### PR TITLE
Conformance results for v1.24/plusserver-pske

### PR DESCRIPTION
**Pull request by sknop-cgn**
Signed-off-by: sknop <118932232+sknop-cgn@users.noreply.github.com>

### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [x] If this is a new entry, have you submitted a signed [participation form](https://github.com/cncf/k8s-conformance/tree/master/participation-form)?
* [ ] Did you include the product/project logo in SVG, EPS or AI format?  
* [ ] Does your logo clearly state the name of the product/project and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [ ] If your product/project is open source, did you include the `repo_url`?
* [x] Did you copy and paste the [installation and configuration instructions](https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions) into the README.md file in addition to linking to them?

### CODE REVIEW

**Comment by sknop-cgn** [comment]
@taylorwaggoner any update on this? Please let me know if anything is needed from my side.

**Comment by sknop-cgn** [comment]
@taylorwaggoner any update on this?

**Comment by taylorwaggoner** [comment]
Apologies @sknop-cgn I've been out of office for the past 2 weeks.  Could you please add a bit of detail about how to create/configure a cluster in your README?  Context [here](https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions). Thanks!

**Comment by sknop-cgn** [comment]
Hi @taylorwaggoner can you please specify what they need? 
1) a step-by-step dashboard guide to create a kubernetes cluster
2) a kubernetes manifest as an example for the conformance test
Thanks!

**Pull request closed without merging**
