### PR TITLE
Conformance results for v1.9/docker-for-mac and v1.9/docker-for-windows

### PR DESCRIPTION
**Pull request by guillaumerose**
This PR contains conformance tests for Docker for Desktop. 

Thanks!

### CODE REVIEW

**Comment by taylorwaggoner** [comment]
You are now Certified Kubernetes

**Comment by TaTaRsKiY059** [comment]
Update

**Review by aekewu1111 — COMMENTED** [review]
这

**Review by aekewu1111 — COMMENTED** [review]
这

**Review by aekewu1111 — COMMENTED** [review]
在

**Pull request merged**
