### PR TITLE
Conformance results for v1.18/opennebula-kubernetes-appliance

### PR DESCRIPTION
**Pull request by ospalax**
### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [x] If this is a new entry, have you submitted a signed [participation form](https://github.com/cncf/k8s-conformance/tree/master/participation-form)?
* [x] Did you include the product/project logo in SVG, EPS or AI format?  
* [x] Does your logo clearly state the name of the product/project and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [x] If your product/project is open source, did you include the `repo_url`?
* [x] Did you copy and paste the [installation and configuration instructions](https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions) into the README.md file in addition to linking to them?

### CODE REVIEW

**Comment by ospalax** [comment]
Hi,

if the subdirectory `opennebula-kubernetes-appliance` is too long - I may come up with something less descriptive - just let me know.

Also the `type` in the `PRODUCT.yaml` is maybe not correct as `installer` but out of the list of possible values it seemed to me as the most appropriate right after `distribution`. The thing is that this appliance is downloading and installing kubernetes (from kubernetes.io) but it also provides a framework for integration with OpenNebula (via contextualization) and complete cluster deployment (via OpenNebula's OneFlow functionality) - so maybe the correct type is `distribution`? I did not want to use this type because in the description of this type is this part: 

> includes patches to the upstream codebase

Which does not apply to this appliance - it is just vanilla upstream kubernetes packaged and scripted around.

Thank you in advance for a response

Best regards
Petr Ospalý

**Comment by taylorwaggoner** [comment]
@ospalax, we would suggest leaving it as an installer.  The product name (and directory) can be OpenNebula - Kubernetes Appliance if you wish, just let me know!

**Comment by ospalax** [comment]
> @ospalax, we would suggest leaving it as an installer. The product name (and directory) can be OpenNebula - Kubernetes Appliance if you wish, just let me know!

Hi, if the current directory is fine with you then it is fine with me.

Thank you

**Comment by taylorwaggoner** [comment]
You are now Certified Kubernetes
https://landscape.cncf.io/format=card-mode&selected=open-nebula-kubernetes-appliance

**Comment by ospalax** [comment]
Hi @taylorwaggoner,

thanks!

**Pull request merged**
