### PR TITLE
Conformance results for v1.11/kdc

### PR DESCRIPTION
**Pull request by voskvv**

### CODE REVIEW

**Comment by taylorwaggoner** [comment]
@voskvv thank you for submitting! The results look great, but there's a small issue with your logo.  We request that a product name match up with the logo text, so that the logos appear correctly when sorted alphabetically (https://github.com/cncf/landscape#logos).  

Your product name is Kubernetes Distribution by Containerum, but the logo just says Containerum.  To resolve, we can either call the product "Containerum Kubernetes Distribution" and use the logo you provided, or call the product "Exon LV Kubernetes Distribution by Containerum" and use the Exon LV logo from https://www.cncf.io/about/members/.  Alternatively, if you have a different logo that reads "Kubernetes Distribution by Containerum", that would be the best option.  

Please let me know how you'd like to proceed.

**Comment by voskvv** [comment]
@taylorwaggoner thank you for the review!
I've prepared a new logo that reads "Kubernetes Distribution by Containerum". 
Should I update the PRODUCT.yaml with the new logo url or add the link here in the comments section? 

Thanks!

**Comment by dankohn** [comment]
Please update PRODUCT.yaml. Please also note that we need the logo in SVG,
AI, or EPS format.
--
Dan Kohn <dan@linuxfoundation.org>
Executive Director, Cloud Native Computing Foundation https://www.cncf.io
+1-415-233-1000 https://www.dankohn.com

**Comment by voskvv** [comment]
@dankohn PRODUCT.yaml has been updated with a new logo. 
Thanks!

**Comment by taylorwaggoner** [comment]
You are now Certified Kubernetes
https://github.com/cncf/landscape/pull/930

@voskvv  Does Exon LV have an active twitter account that we can add to your Crunchbase profile here: https://www.crunchbase.com/organization/exonlab

Thanks!

**Comment by voskvv** [comment]
@taylorwaggoner Thank you very much!
Currently we use https://twitter.com/Containerumcom as the account for our products and services.

**Pull request merged**
