### PR TITLE
change company name for compass

### PR DESCRIPTION
**Pull request by april4**
### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [ ] If this is a new entry, have you submitted a signed [participation form](https://github.com/cncf/k8s-conformance/tree/master/participation-form)?
* [ ] Did you include the product/project logo in SVG, EPS or AI format?  
* [ ] Does your logo clearly state the name of the product/project and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [ ] If your product/project is open source, did you include the `repo_url`?
* [ ] Did you copy and paste the [installation and configuration instructions](https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions) into the README.md file in addition to linking to them?

### CODE REVIEW

**Comment by april4** [comment]
Our company(Caicloud Inc.) already acquired by Volcano Engine(which is a subsidiary of ByteDance Inc.,
https://mp.weixin.qq.com/s/-PorDs6_VZnK1dC-KSg3HQ, https://new.qq.com/omn/20200818/20200818A061DM00.html).

**Comment by taylorwaggoner** [comment]
@april4 thanks for submitting.  Please make sure to send in a new [Participation form](https://github.com/cncf/k8s-conformance/tree/master/participation-form) for this product.  Please also advise on what logo to use.  
Thanks!

**Comment by pendoragon** [comment]
@taylorwaggoner we have sent the conformance form via email today.

**Comment by taylorwaggoner** [comment]
We have updated the listing to Volcano Engine Compass: https://landscape.cncf.io/format=card-mode&selected=volcano-engine-compass
Thanks!

**Pull request merged**
