### PR TITLE
Add SOFAStack-CAFE v1.12 conformance results 

### PR DESCRIPTION
**Pull request by rootsongjc**
Signed-off-by: Jimmy Song <jingchao.sjc@antfin.com>

### CODE REVIEW

**Comment by taylorwaggoner** [comment]
@rootsongjc, thank you for submitting these results, but we are no longer certifying for v1.12, per [these guidelines](https://github.com/cncf/k8s-conformance/blob/master/faq.md#what-versions-of-kubernetes-can-be-certified).  v1.15 was released yesterday, so we are only certifying for v1.13, v1.14, and v1.15 now, if you would like to submit results for those versions.

We'll also need you to send in a [signed participation form](https://github.com/cncf/k8s-conformance/tree/master/participation-form) before we can move forward with certification.  

Please also note that we no longer require the version.txt file in your PR, per [these instructions](https://github.com/cncf/k8s-conformance/blob/master/instructions.md#contents-of-the-pr), so you can leave that out when you submit new results.  

Thanks!

**Comment by rangeryu** [comment]
@taylorwaggoner  Thanks Taylor for the notification. This is Ranger Yu who is @rootsongjc Jimmy's colleague working on the product mgmt. We are sorry for the delay of the submission because that we didn't want to disclose the product information too early and didn't know that the progress of v1.15 will have such impact on our certification.

I've just emailed to conformance@cncf.io with our participation form and our clarification. Thanks You and we are working on v1.14 as well.

**Comment by rootsongjc** [comment]
@taylorwaggoner If I knew that there was such an impact and predicted that Kubernetes 1.5 would be released yesterday, I would definitely submit the PR in advance. 😄

**Comment by taylorwaggoner** [comment]
You are now Certified Kubernetes
https://landscape.cncf.io/format=card-mode&selected=sofa-stack-cloud-application-fabric-engine

**Pull request merged**
