### PR TITLE
Conformance results for v1.17/ksyun

### PR DESCRIPTION
**Pull request by seamounts**
### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [x] If this is a new entry, have you submitted a signed [participation form](https://github.com/cncf/k8s-conformance/tree/master/participation-form)?
* [x] Did you include the product/project logo in SVG, EPS or AI format?  
* [x] Does your logo clearly state the name of the product/project and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [x] If your product/project is open source, did you include the `repo_url`?
* [x] Did you copy and paste the [installation and configuration instructions](https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions) into the README.md file in addition to linking to them?

### CODE REVIEW

**Comment by taylorwaggoner** [comment]
@seamounts thanks for submitting.  The results look great, but there's one thing to update. Per [these guidelines](https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions), could you please paste all instructions and requirements into the README file, in addition to linking to the URLs? Thanks!

**Comment by seamounts** [comment]
> @seamounts thanks for submitting. The results look great, but there's one thing to update. Per [these guidelines](https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions), could you please paste all instructions and requirements into the README file, in addition to linking to the URLs? Please update both this PR and #1021. Thanks!

Thank you. I have copied the contents of the document to readme, but the contents of the document are in Chinese。

**Comment by taylorwaggoner** [comment]
@seamounts thank you.  Could you please an online translator, such as Google Translate, to translate the instruction to English?  Please make sure that they still make sense, and then paste into the README?  Thanks!

**Comment by seamounts** [comment]
> @seamounts thank you. Could you please an online translator, such as Google Translate, to translate the instruction to English? Please make sure that they still make sense, and then paste into the README? Thanks!

I have already translated, please check。

**Comment by taylorwaggoner** [comment]
You are now Certified Kubernetes

**Pull request merged**
