### PR TITLE
Conformance results for v1.18/lstack

### PR DESCRIPTION
**Pull request by xishengcai**
### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [x] If this is a new entry, have you submitted a signed [participation form](https://github.com/cncf/k8s-conformance/tree/master/participation-form)?
* [x] Did you include the product/project logo in SVG, EPS or AI format?  
* [x] Does your logo clearly state the name of the product/project and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [x] If your product/project is open source, did you include the `repo_url`?
* [x] Did you copy and paste the [installation and configuration instructions](https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions) into the README.md file in addition to linking to them?

### CODE REVIEW

**Comment by taylorwaggoner** [comment]
@xishengcai thanks for submitting!  I have a question about your logo.  We have a [requirement ](https://github.com/cncf/landscape#logos)that the logo includes either the company or product name in English.  Do you have a logo available with the product or company name?  We can use [this logo from Launcher Tech's CNCF membership](https://landscape.cncf.io/logos/launcher-tech-member.svg) if you'd like, but we would then need to name your product listing "Launcher Tech LStack Container Service for Kubernetes" so that it alphabetizes correctly in the landscape.  Please let me know if you have any questions.  Thanks!

**Comment by xishengcai** [comment]
We don't have a log include name, I willing to accept your suggestion that use this log from Launcher Tech's CNCF membership 。

**Comment by xishengcai** [comment]
We don't have a logo available with the product or company name. I'm willing to accept your suggestion to use this log from Launcher Tech's CNCF membership.

**Comment by taylorwaggoner** [comment]
Great thank you!  In the README file, are there any additional instructions you could provide about how a user would create a cluster?  We're trying to ensure that a customer could recreate your conformance results using step by step instructions.  Thanks!

**Comment by xishengcai** [comment]
Sorry this is no more infromation. But don't worry,our platform is easy to operate.

**Comment by taylorwaggoner** [comment]
You are now Certified Kubernetes
https://landscape.cncf.io/format=card-mode&selected=launcher-tech-l-stack-container-service-for-kubernetes

**Pull request merged**
