### PR TITLE
Conformance results for v1.16/moondog

### PR DESCRIPTION
**Pull request by jwietelmann**
### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [x] If this is a new entry, have you submitted a signed [participation form](https://github.com/cncf/k8s-conformance/tree/master/participation-form)?
* [x] Did you include the product/project logo in SVG, EPS or AI format?  
* [x] Does your logo clearly state the name of the product/project and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [ ] ~If your product/project is open source, did you include the `repo_url`?~
* [x] Did you copy and paste the [installation and configuration instructions](https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions) into the README.md file in addition to linking to them?

### CODE REVIEW

**Comment by taylorwaggoner** [comment]
@jwietelmann thanks for submitting.  I noticed in your README that 

> Installation instructions will be available at https://moondog.co when Moondog goes public

In order to certify your product, we will need to review those instructions.  You can post them in the README now, or we could hold off on certification until your product goes public.  If the latter, I suggest that you close this PR and reopen a new one on the day you release the product.  We could [privately review](https://github.com/cncf/k8s-conformance/blob/master/instructions.md#amendment-for-private-review) ahead of the release day and then merge your PR quickly once you submit it.  Please let us know how you'd like to proceed. Thanks!

**Comment by jwietelmann** [comment]
@taylorwaggoner Sorry, a point of clarification. Our product is "released" and available now as a closed, proprietary installer that we run on a Revelry hosted cluster (also currently closed/proprietary). We have plans to make it more public than it currently is, and so I think I muddied the waters. I made it seem like this was unreleased software. It's available now, but at this moment in time you cannot self-install.

As a point of reference I've been looking at [this accepted submission](https://github.com/cncf/k8s-conformance/blob/master/v1.17/vmware-tanzu-kubernetes-grid), whose instructions reference a sales page whose only instructions are a "get in touch" button, and whose docs URL points to general company docs that do not include this product.

Can we just amend the README to be like the VMWare one by removing the language about future public docs?

(Revelry is a CNCF member, in case you do not have that info right in front of you.)

**Comment by jwietelmann** [comment]
What I would probably change our public conformance README to say is: "Moondog comes pre-installed with your [Revelry Managed Cloud](https://revelry.co/managed-cloud/)"

I can also privately send you our internal install instructions.

**Comment by taylorwaggoner** [comment]
@jwietelmann, we'll get back to you on this one.  The VMware product was originally certified in January before we posted [these guidelines](https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions).  That PR you mentioned was just a name change, but we missed asking them to provide more details in their README.  We'll get back to you with what's needed here. 
cc @dankohn

**Comment by taylorwaggoner** [comment]
You are now Certified Kubernetes
https://landscape.cncf.io/format=card-mode&organization=revelry&selected=moondog

**Pull request merged**
