### PR TITLE
Conformance results for v1.11/netease-qingzhou

### PR DESCRIPTION
**Pull request by chaolou**
Conformance results for Netease Qingzhou Microservice in Kubernetes v1.11

### CODE REVIEW

**Comment by taylorwaggoner** [comment]
@chaolou thanks for submitting.  Your results look great, but I would like to confirm if this is the same product you previously certified, Netease Container Service Dedicated.  https://github.com/cncf/k8s-conformance/tree/master/v1.11/netease

If it is a new product, please fill out a new participation form here: https://github.com/cncf/k8s-conformance/tree/master/participation-form.  You would also need to provide your logo in SVG, EPS, or AI format, and also provide the type and an optional description (https://github.com/cncf/k8s-conformance/blob/master/instructions.md#productyaml)

If this is the same product, but it has been renamed, we will still need your logo in the proper format in order to update.  Thanks!

**Comment by chaolou** [comment]
Actually this conformance results is a new product named "Netease Qinqzhou MicroService" by us,
also the new participation form already been sent to conformance@cncf.io by email attachment a moment ago, please check it. Thanks!

**Comment by taylorwaggoner** [comment]
@chaolou thanks for sending the updated form.  For your logo, you can either provide the product logo in SVG, EPS, or AI format (as per https://github.com/cncf/k8s-conformance/blob/master/instructions.md#productyaml) or we can use the Netease logo from here: https://landscape.cncf.io/selected=netease-container-service-dedicated.  Please let me know which you would prefer.  Thanks!

**Comment by chaolou** [comment]
Please keep the same logo(Netease logo) with the netease-container-service-dedicated, thanks!

**Comment by taylorwaggoner** [comment]
You are now Certified Kubernetes
https://github.com/cncf/landscape/pull/1036

**Pull request merged**
