### PR TITLE
Conformance results for v1.16/HostedJDOS

### PR DESCRIPTION
**Pull request by yangyefei-bj**
### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [x] If this is a new entry, have you submitted a signed [participation form](https://github.com/cncf/k8s-conformance/tree/master/participation-form)?
* [x] Did you include the product/project logo in SVG, EPS or AI format?  
* [x] Does your logo clearly state the name of the product/project and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [ ] If your product/project is open source, did you include the `repo_url`?
* [x] Did you copy and paste the [installation and configuration instructions](https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions) into the README.md file in addition to linking to them?

### CODE REVIEW

**Comment by taylorwaggoner** [comment]
@yangyefei-bj , thank you for submitting!  There are a few things to do before I can merge this PR.

First, please confirm that this product and the JD.com certified distribution from #788 have different code.

I believe you had wanted to rename [the distribution](https://landscape.cncf.io/format=card-mode&selected=jd-com-tig-jingdong-datacenter-os) to JD Datacenter OS (JDOS)?  

For this product, could we call it "JD.com JDOS Hosted" instead of "Hosted JDOS"? We want to make sure that the logo matches to the product name, for alphabetization purposes in the landscape.

And please confirm that it is okay for us to use [this JD.com logo](https://landscape.cncf.io/format=card-mode&selected=jd-com-member) that we use for your CNCF membership, for consistency on the Cloud Native Landscape.

Lastly, please add installation and configuration instructions for your Kubernetes implementation to your README, [per these guidelines](https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions).  Let us know if you have any questions.

Thanks!

**Comment by yangyefei-bj** [comment]
@taylorwaggoner , hi, taylor:

Regarding your questions.

First, I understand that the distribution is a software and hosted is a platform, we want to use the same set of code to do two ways of authentication, because we have a distribution (http://tig.jd.com/en/products/jdos), and also a platform based on this distribution (https://jdos3.jd.com), I think they are different, I do n’t know if I understand correctly.

This product can be called "JD.com JDOS Hosted".

It's okay to use JD.com logo.

Let us know if you have any questions. thanks.

**Comment by yangyefei-bj** [comment]
@taylorwaggoner hi, taylor:

I changed my README.md file,  do you have any other questions ?  thank you !

**Comment by yangyefei-bj** [comment]
@taylorwaggoner hi, taylor:
Is there any problem with my PR? If so, please tell me, thanks!

**Comment by yangyefei-bj** [comment]
@taylorwaggoner hi, taylor:
We are going to provide cloud service with JDOS hosted(https://jdos3.jd.com), so we want to make it hosted Certified, if there is any problem, please tell me, thanks very much!

**Comment by taylorwaggoner** [comment]
@yangyefei-bj, sorry for the delay here.  For the README, please paste in the step by step installation and configuration instructions, including how to provision a cluster.  Is there any special configuration necessary to get the tests to pass? We're trying to provide guidance so that your customers can later validate your conformance if they wish to. Thanks!

**Comment by yangyefei-bj** [comment]
@taylorwaggoner hi, taylor, thanks for your reply!
According to your request, I modified the README.
Please check compliance.
Thanks!

**Comment by taylorwaggoner** [comment]
@yangyefei-bj thanks!  Are there any specific steps one would need to take to create a cluster once they are logged into their JDOS account?  In other words, what other steps are needed to create the cluster once logged in?  Thanks!

**Comment by yangyefei-bj** [comment]
@taylorwaggoner thanks for your reminder！
I modified the README.
Please check compliance.
Thanks!

**Comment by taylorwaggoner** [comment]
You are now Certified Kubernetes
https://landscape.cncf.io/format=card-mode&organization=jd-com&selected=jd-com-jdos-hosted

**Comment by yangyefei-bj** [comment]
@taylorwaggoner thanks！

**Pull request merged**
