### PR TITLE
Add OpenStack Magnum conformance results

### PR DESCRIPTION
**Pull request by openstacker**

### CODE REVIEW

**Comment by hogepodge** [comment]
/lgtm
/approve
OpenStack Foundation signatory for conformance and OpenStack Magnum

**Comment by hogepodge** [comment]
@taylorwaggoner thanks for the feedback, happy to make those changes.

@openstacker 
* Updated logo is here: https://www.openstack.org/themes/openstack/images/project-mascots/Magnum/OpenStack_Project_Magnum_vertical.eps
* Please change the product name from "OpenStack Magnum" to "Magnum".

Thanks!

**Comment by openstacker** [comment]
@hogepodge Thanks for the info, just pushed a new patch.

@taylorwaggoner Thanks for your feedback. Please review again. Cheers.

**Comment by taylorwaggoner** [comment]
Thank you! You are now Certified Kubernetes.
https://github.com/cncf/landscape/pull/784

**Pull request merged**
