### PR TITLE
Conformance results for v1.27/stackit-kubernetes-engine

### PR DESCRIPTION
**Pull request by robinschneider**
### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [ ] If this is a new entry, have you submitted a signed [participation form](https://github.com/cncf/k8s-conformance/tree/master/participation-form)?
* [x] Did you include the product/project logo in SVG, EPS or AI format?  
* [x] Does your logo clearly state the name of the product/project and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [ ] If your product/project is open source, did you include the `repo_url`?
* [x] Did you copy and paste the [installation and configuration instructions](https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions) into the README.md file in addition to linking to them?

For a full list of requirements, please refer to these sections of the docs: [_Contents of the PR_](https://github.com/cncf/k8s-conformance/blob/master/instructions.md#contents-of-the-pr), and [_Requirements_](https://github.com/cncf/k8s-conformance/blob/master/instructions.md#requirements).

### CODE REVIEW

**Comment by taylorwaggoner** [comment]
@robinschneider thanks for submitting! Could you please add the steps in the README for how to create an account and project, as well as more details about setting up a cluster? It looks like this link is broken as well: https://docs.stackit.cloud/display/STACKIT/How+to+create+and+manage+a+project
Thanks!

**Comment by robinschneider** [comment]
> @robinschneider thanks for submitting! Could you please add the steps in the README for how to create an account and project, as well as more details about setting up a cluster? It looks like this link is broken as well: https://docs.stackit.cloud/display/STACKIT/How+to+create+and+manage+a+project Thanks!

I fixed the broken link and updated the description on how to create an account, project and cluster.

**Comment by robinschneider** [comment]
@taylorwaggoner I updated the documentation, is there anything else I have to do?

**Comment by taylorwaggoner** [comment]
@robinschneider thanks for making those updates! Could you also add the step by step details for creating a cluster? We ask that you provide the steps in addition to including the link in our FAQ [here](https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions). Thanks!

**Comment by robinschneider** [comment]
@taylorwaggoner sorry for missing that part! I provided a detailed description in addition to the link.

**Review by taylorwaggoner — APPROVED** [review]

**Comment by taylorwaggoner** [comment]
You are now Certified Kubernetes

**Pull request merged**
