### PR TITLE
Conformance results for v1.14/scaleway

### PR DESCRIPTION
**Pull request by Sh4d1**
Conformance results for v1.14/scaleway

Signed-off-by: Patrik Cyvoct <patrik@ptrk.io>

### CODE REVIEW

**Comment by taylorwaggoner** [comment]
@Sh4d1, thanks for submitting!  The results for 1.13 and 1.14 look great, just a couple of questions below, but we're unable to move forward with certification until you become a CNCF member.  I believe your team has been in touch with us about joining, but please let us know if you have any questions!

Once you send in your membership agreement, please also resend the [participation agreement](https://github.com/cncf/k8s-conformance/tree/master/participation-form), with the CNCF Member checkbox marked.  

You noted that the vendor is Online SAS.  Your company is already listed in the [Cloud Native Landscape](https://landscape.cncf.io/format=card-mode&selected=scaleway) under Scaleway.  Would it be alright to have your entry for Kubernetes Kapsule under Scaleway as well for consistency?  We will use your [Scaleway Crunchbase profile](https://www.crunchbase.com/organization/scaleway) to pull info into the Landscape, just like the existing entry.

Also, we will need to name your product "Scaleway Kubernetes Kapsule", so that your logo text matches up with the product name alphabetically in the landscape.  If you'd like to use a logo that just says "Kubernetes Kapsule", that would also work.   Thanks!

**Comment by Sh4d1** [comment]
Hello @taylorwaggoner !
So I've updated both the 1.13 and 1.14 PR to change the product name and the vendor

**Comment by Sh4d1** [comment]
Hi again @taylorwaggoner, as we are now a CNCF member, we just resubmitted the participation form with the modification you gave :) 
I think it's now possible to merge this PR and the other one?

Cheers

**Comment by taylorwaggoner** [comment]
You are now Certified Kubernetes
https://landscape.cncf.io/format=card-mode&selected=scaleway-kubernetes-kapsule

**Pull request merged**
