### PR TITLE
Conformance results for v1.14/vexxhost

### PR DESCRIPTION
**Pull request by guilhermesteinmuller**

### CODE REVIEW

**Comment by taylorwaggoner** [comment]
@guilhermesteinmuller thank you for submitting results!  Before we move forward, can you please make sure that your files are all under your v1.14 folder?  Also, please only include the files listed in [the instructions](https://github.com/cncf/k8s-conformance/blob/master/instructions.md#contents-of-the-pr).  Thanks!

**Comment by guilhermesteinmuller** [comment]
thank you @taylorwaggoner ! Could you check if everything is ok now?

**Comment by taylorwaggoner** [comment]
Looks great!  Is this still your repo: https://vexxhost.com/public-cloud/container-services/kubernetes/?

Thanks!

**Comment by guilhermesteinmuller** [comment]
> Looks great! Is this still your repo: https://github.com/vexxhost/magnum
> 
> Thanks!

Yeah, it is @taylorwaggoner !

**Comment by taylorwaggoner** [comment]
You are now Certified Kubernetes
https://landscape.cncf.io/format=card-mode&selected=vexxhost-kubernetes-container-service

**Pull request merged**
