### PR TITLE
Conformance results for v1.24/openshift-dedicated

### PR DESCRIPTION
**Pull request by MrSantamaria**
### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [x] If this is a new entry, have you submitted a signed [participation form](https://github.com/cncf/k8s-conformance/tree/master/participation-form)?
* [x] Did you include the product/project logo in SVG, EPS or AI format?  
* [x] Does your logo clearly state the name of the product/project and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [x] If your product/project is open source, did you include the `repo_url`?
* [x] Did you copy and paste the [installation and configuration instructions](https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions) into the README.md file in addition to linking to them?

For a full list of requirements, please refer to these sections of the docs: [_Contents of the PR_](https://github.com/cncf/k8s-conformance/blob/master/instructions.md#contents-of-the-pr), and [_Requirements_](https://github.com/cncf/k8s-conformance/blob/master/instructions.md#requirements).

Signed-off-by: Diego Santamaria [dsantama@redhat.com](mailto:dsantama@redhat.com)

### CODE REVIEW

**Comment by MrSantamaria** [comment]
The two test failing are part of the OVN version used in 1.24 which were not supported. 
It is to my understanding that those test will be removed from the conformance suite 1.26+
Will that change be back ported to previous api versions?

**Comment by Riaankl** [comment]
> The two test failing are part of the OVN version used in 1.24 which were not supported. It is to my understanding that those test will be removed from the conformance suite 1.26+ Will that change be back ported to previous api versions?

@MrSantamaria I have posted the question in [K8s-Conformance slack channel](https://kubernetes.slack.com/archives/C78F00H99/p1674673352277319).

**Comment by dcbw** [comment]
@MrSantamaria @Riaankl @derekwaynecarr

I have a PR open in kube to backport the demotion of those specific conformance tests to v1.25:

https://github.com/kubernetes/kubernetes/pull/112990

but I have gotten no response from various conformance-related people despite multiple pings, and despite talking to people at KubeCon Detroit last year.

**Comment by smarterclayton** [comment]
I responded to that PR, this seems reasonable if we have community agreement that the conformance tests were premature.

Adding conformance tests to an old version would worry me, removing them would not.  I will work with the working groups to get final consensus here but I am supportive to demote those tests.

**Comment by smarterclayton** [comment]
https://github.com/kubernetes/community/pull/7071 covers updating the project process to cover approval of the backport of https://github.com/kubernetes/kubernetes/pull/112990

**Comment by Riaankl** [comment]
These tests would be demoted for 1.25
https://github.com/kubernetes/kubernetes/pull/112990

**Comment by Riaankl** [comment]
@taylorwaggoner this [PR](https://github.com/kubernetes/kubernetes/pull/112990) will demote the test for 1.25.
After it merged these test would not be requiered for conformance 1.25.
Should also be done for 1.24, but that might take a while. This should not be a blocker for this PR.

**Comment by taylorwaggoner** [comment]
You are now Certified Kubernetes

**Pull request merged**
