### PR TITLE
Conformance results for v1.15/platform9

### PR DESCRIPTION
**Pull request by pshanbhag**

### CODE REVIEW

**Comment by taylorwaggoner** [comment]
@pshanbhag can you please copy and paste the instructions into the README, rather than linking to a URL?  Thanks!

**Comment by pshanbhag** [comment]
> @pshanbhag can you please copy and paste the instructions into the README, rather than linking to a URL? Thanks!

I can but that is a pretty detailed document. Do you want all of the steps duplicated in the README? Or I can drop that link altogether.

**Comment by pshanbhag** [comment]
I have updated the PR with abridged instructions instead of pointing it to our documentation URL.

**Comment by taylorwaggoner** [comment]
You are now Certified Kubernetes

**Pull request merged**
