### PR TITLE
Conformance results for v1.20/snaps-kubernetes

### PR DESCRIPTION
**Pull request by Sanjhana-Jayagopal**
### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [ ] If this is a new entry, have you submitted a signed [participation form](https://github.com/cncf/k8s-conformance/tree/master/participation-form)?
* [x] Did you include the product/project logo in SVG, EPS or AI format?  
* [x] Does your logo clearly state the name of the product/project and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [x] If your product/project is open source, did you include the `repo_url`?
* [x] Did you copy and paste the [installation and configuration instructions](https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions) into the README.md file in addition to linking to them?

### CODE REVIEW

**Comment by ErinThacker** [comment]
@Sanjhana-Jayagopal - we need detailed installation instructions in your README file.

**Comment by Sanjhana-Jayagopal** [comment]
@ErinThacker Would you like us to add anything specifically for the installation instructions? We have always submitted this README.md for our previous certifications.

**Comment by amye** [comment]
@ErinThacker: README is fine, we can go ahead here

**Comment by RandyLevensalor** [comment]
It looks like everything is good.  Can someone please merge this or provide feedback for any requirements that are not met?

**Pull request merged**
