### PR TITLE
Add conformance results for v1.10/k8s-tew

### PR DESCRIPTION
**Pull request by darxkies**

### CODE REVIEW

**Comment by dankohn** [comment]
Could you please create a new logo that doesn't incorporate the Kubernetes logo but does include the text "The Easier Way" in it?

**Comment by darxkies** [comment]
I have updated the logo and removed the Kubernetes logo. Is it ok that way?

**Comment by dankohn** [comment]
Could you add wording underneath so it is readable here: https://landscape.cncf.io/grouping=landscape&landscape=certified-kubernetes-distribution,certified-kubernetes-hosted,certified-kubernetes-installer

Otherwise, if you specify the text, we can do it for you.

**Comment by darxkies** [comment]
I think I got the idea and updated it. Is that ok?

**Comment by dankohn** [comment]
Logo looks good. Please also update PRODUCT.yaml to specify `type` as an installer.

https://github.com/cncf/k8s-conformance/blob/master/instructions.md#productyaml

**Comment by darxkies** [comment]
I have updated PRODUCT.yaml according to the provided link.

**Comment by taylorwaggoner** [comment]
You are now Certified Kubernetes
https://github.com/cncf/landscape/pull/726

**Comment by darxkies** [comment]
Thank you very much for your great support.

**Pull request merged**
