### PR TITLE
Conformance results for v1.23/ntnx-karbon

### PR DESCRIPTION
**Pull request by legacyrj**
… Karbon) for k8s v1.23

### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [ ] If this is a new entry, have you submitted a signed [participation form](https://github.com/cncf/k8s-conformance/tree/master/participation-form)?
* [x] Did you include the product/project logo in SVG, EPS or AI format?  
* [x] Does your logo clearly state the name of the product/project and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [ ] If your product/project is open source, did you include the `repo_url`?
* [x] Did you copy and paste the [installation and configuration instructions](https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions) into the README.md file in addition to linking to them?

### CODE REVIEW

**Comment by legacyrj** [comment]
@taylorwaggoner Please help us review PR and provide feedback. Thank you.

**Comment by taylorwaggoner** [comment]
@legacyrj thanks for submitting.  Looks like you have a few items to resolve for this PR.  Could you please take a look at the 3 items that failed? Thanks!

**Comment by legacyrj** [comment]
@taylorwaggoner I have addressed 2 issues and updated the PR. Following are the addressed issues: 
=====
[FAIL] the title of the submission does not seem to contain a Kubernetes release version that matches the release version in the submitted files
Kubernetes release version in the title () and folder structure (v1.23) don't match

[FAIL] the submission title is missing either a Kubernetes release version (v1.xx) or product name
title must be formatted like 'Conformance results for [KubernetesReleaseVersion]/[ProductName]' (e.g: Conformance results for v1.23/CoolKubernetes)
=====

Link to PR for k8s v1.22: https://github.com/cncf/k8s-conformance/pull/1911

**Comment by Riaankl** [comment]
Changing the title to the format "Conformance results for v1.23/ntnx-karbon" would resolve this other issues.

**Comment by taylorwaggoner** [comment]
You are now Certified Kubernetes

**Pull request merged**
