### PR TITLE
Conformance results for v1.17/BoCloud

### PR DESCRIPTION
**Pull request by TomatoAres**

### CODE REVIEW

**Comment by taylorwaggoner** [comment]
@TomatoAres thank you for submitting.  Before we can move forward, please paste in all cluster installation and configuration instructions into the README,[ per these guidelines](https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions).  Thanks!

**Comment by TomatoAres** [comment]
Thank you for your review.I have modified according to your reply and guidelines.

**Comment by taylorwaggoner** [comment]
Thank you, I see that you've added instructions for installing your platform.  Are there any instructions for configuring/installing a cluster needed?  Or is there any special configuration necessary to get the tests to pass? We're trying to provide guidance so that your customers can later validate your conformance if they wish to. Thanks!

**Comment by TomatoAres** [comment]
Thanks.I have already added the informations about how to install a cluster

**Comment by taylorwaggoner** [comment]
Thanks! You are now Certified Kubernetes

**Pull request merged**
