### PR TITLE
Expand certification terms to cover last 3 versions

### PR DESCRIPTION
**Pull request by WilliamDenniss**
Per email thread, updated terms for review.

### CODE REVIEW

**Comment by dims** [comment]
LGTM 👍 

cc @timothysc @duglin @bgrant0607

**Comment by duglin** [comment]
LGTM

**Comment by dankohn** [comment]
LGTM. @swinslow Can we please get your signoff on the drafting language.

**Comment by swinslow** [comment]
LGTM

We will also want to update the "Last updated" date in line 5 and to update the PDF so it stays in sync. I'll submit a separate PR to address these.

**Comment by dankohn** [comment]
There was consensus to go forward with this change.

**Pull request merged**
