### PR TITLE
Conformance results for v1.10/ebaocloud

### PR DESCRIPTION
**Pull request by cdyue**
vendor: eBaoTech
name: eBaoCloud Platform
version: v1.0.0
website_url: https://sg.ebaocloud.com/
documentation_url: https://sg.ebaocloud.com/
type: distribution
product_logo_url: https://enablement.ebaocloud.com/staticfile/img/logo.png

### CODE REVIEW

**Comment by cdyue** [comment]
Do I need to provide CNCF membership info?

**Comment by taylorwaggoner** [comment]
@cdyue - No need to provide membership info, we have everything we need there. 

There are a couple issues with the PR that need to be resolved.  Please make sure to delete the v1.7 files from the PR.  Also, you'll need to make sure that the Client Version in the version.txt file is fixed, so that it reflects the conformance version: {Major:"1", Minor:"10",... instead of {Major:"1", Minor:"7".  

Please update the link to your product logo to be in SVG, AI, or EPS format as per these guidelines: https://github.com/cncf/k8s-conformance/blob/master/instructions.md#productyaml

Lastly, please send us a signed Participation Form: https://github.com/cncf/k8s-conformance/blob/master/participation-form/Certified_Kubernetes_Form.pdf.  
Please let me know if you have any questions.

**Comment by cdyue** [comment]
I have fixed the issues.
My colleague will send signed Participation Form to you.

**Comment by dankohn** [comment]
Note that that is a reversed logo (white on blue). If you don't have a
non-reversed version, we'll create it for you.

--
Dan Kohn <dan@linuxfoundation.org>
Executive Director, Cloud Native Computing Foundation https://www.cncf.io
+1-415-233-1000 https://www.dankohn.com

**Comment by dankohn** [comment]
Non-reversed form of your logo:

[ebaotech.svg.zip](https://github.com/cncf/k8s-conformance/files/2045092/ebaotech.svg.zip)

**Comment by cdyue** [comment]
@dankohn Thank you. Please use the logo which is created by you.
I have uploaded it to the server:
https://enablement.ebaocloud.com/staticfile/img/ebaotech.svg

**Comment by cdyue** [comment]
@taylorwaggoner @dankohn  signed on DocuSign

**Comment by taylorwaggoner** [comment]
Thanks @cdyue!  You are now Certified Kubernetes

**Pull request merged**
