### PR TITLE
Conformance results for v1.13/robin.io

### PR DESCRIPTION
**Pull request by gkesavan**

### CODE REVIEW

**Comment by taylorwaggoner** [comment]
@gkesavan, thanks for submitting!  Results look great, but I wanted to confirm the product type with you.  We currently have you listed as a distribution.  Please review [these definitions](https://github.com/cncf/k8s-conformance/blob/master/faq.md#what-is-a-distribution-hosted-platform-and-an-installer) and confirm if your product should be a hosted platform instead.  Thanks!

**Comment by gkesavan** [comment]
> @gkesavan, thanks for submitting! Results look great, but I wanted to confirm the product type with you. We currently have you listed as a distribution. Please review [these definitions](https://github.com/cncf/k8s-conformance/blob/master/faq.md#what-is-a-distribution-hosted-platform-and-an-installer) and confirm if your product should be a hosted platform instead. Thanks!
 @taylorwaggoner I want through the definition and confirm that we are a distribution.

**Comment by gkesavan** [comment]
@taylorwaggoner Are you waiting for any other information from us?

**Comment by taylorwaggoner** [comment]
You are now Certified Kubernetes

**Pull request merged**
