### PR TITLE
Add conformance results for v1.10/kubeadm

### PR DESCRIPTION
**Pull request by stealthybox**
vendor: Weaveworks
name: kubeadm
version: v1.10.0
website_url: https://kubernetes.io/docs/setup/independent/create-cluster-kubeadm/
documentation_url: https://kubernetes.io/docs/setup/independent/create-cluster-kubeadm/
product_logo_url: https://raw.githubusercontent.com/kubernetes/kubernetes/master/logo/logo.svg

### CODE REVIEW

**Comment by stealthybox** [comment]
Fixes kubernetes/kubeadm/issues/766

**Comment by taylorwaggoner** [comment]
You are now Certified Kubernetes

**Comment by luxas** [comment]
LGTM, thanks for submitting @stealthybox!

**Pull request merged**
