### PR TITLE
Conformance results from v1.8/cfcr

### PR DESCRIPTION
**Pull request by bsnchan**
```
vendor: Cloud Foundry
name: Cloud Foundry Container Runtime
version: v0.8.0
website_url: https://www.cloudfoundry.org/container-runtime/
documentation_url: https://docs-kubo.cfapps.io/
product_logo_url: https://www.cloudfoundry.org/wp-content/uploads/2017/10/CFF-Container-Runtime-Full-Color-768x230.png
```

### CODE REVIEW

**Comment by bsnchan** [comment]
There is one test that is failing but should be resolved by https://github.com/kubernetes/kubernetes/pull/54581

**Comment by WilliamDenniss** [comment]
Thanks for fixing that issue, looks like it was just merged. If we assume the test will pass with that fix for now, can you commit to updating your conformance results once the fix is available in the e2e test image?

**Comment by bsnchan** [comment]
Thanks @WilliamDenniss - Do you know how we can get the e2e test image bumped to get the test PR in?

**Comment by WilliamDenniss** [comment]
+1 from my perspective, since you have proactively fixed the issue and I assume tested that you're now passing. Be aware that if the test still fails after the fix is merged, you could be decertified but I trust that you will re-test and verify that.

**Comment by bgrant0607** [comment]
Looks like a test bug, so I'm fine with excluding it until it is fixed.

**Comment by chipchilders** [comment]
@kbarnard10 CFF has signed the participation form now

**Comment by kbarnard10** [comment]
@bsnchan Looks like your version.txt file is missing. Can you add?

**Comment by bsnchan** [comment]
Hi @kbarnard10 - Sorry about that. We assumed that the because of issue mentioned [here](https://github.com/cncf/k8s-conformance/issues/55) that the version can be extracted from the e2e.log.

I've updated the PR with the test a new test run and a version.txt. Please let me know if you need anything else.

**Comment by kbarnard10** [comment]
+1

**Pull request merged**
