### PR TITLE
Conformance results for v1.15/kubeoperator

### PR DESCRIPTION
**Pull request by wanghe-fit2cloud**
Conformance results for v1.15/kubeoperator

### CODE REVIEW

**Comment by taylorwaggoner** [comment]
@wanghe-fit2cloud thanks for submitting!  Could you please update your PRODUCT.yaml file with a link to your logo [in SVG, EPS, or AI format](https://github.com/cncf/k8s-conformance/blob/master/faq.md#are-there-any-limitations-regarding-the-logo)?  Alternatively, we could use [your company logo](https://landscape.cncf.io/format=card-mode&organization=fit2-cloud).  Thanks!

**Comment by wanghe-fit2cloud** [comment]
Thanks for the help and guidance. I signed the document and updated the logo for now.

**Comment by wanghe-fit2cloud** [comment]
@taylorwaggoner 
KubeOperator is an open source product, So added the repo_url field in product.yaml

**Comment by taylorwaggoner** [comment]
@wanghe-fit2cloud, You are now Certified Kubernetes. https://landscape.cncf.io/format=card-mode&organization=fit2-cloud&selected=kube-operator

I have also opened a PR to add the repo.  Thanks!

**Pull request merged**
