### PR TITLE
Move konvoy product's Vendor to Nutanix

### PR DESCRIPTION
**Pull request by supershal**
The Konvoy product is no longer managed by D2IQ. This product will be own and managed by Nutanix going forward.
The product and documentation URL will remain the same.
Updating Vendor entry for 1.27 k8s conformance tests. 
### Pre-submission checklist:
```
vendor: Nutanix
name: Konvoy
version: v2.7.0-dev.4
website_url: https://d2iq.com/products/konvoy
documentation_url: https://d2iq.com/products/konvoy
product_logo_url: https://assets.d2iq.com/production/assets/D2iQ-logo.svg
type: distribution
description: 'Konvoy is a standalone distribution of Kubernetes that includes a native Kubernetes cluster pre-packaged for deployment with a complement of best-in-class add-on services enabled by default and ready for immediate use.'
contact_email_address: eng-tag@d2iq.com

```
*Please check each of these after submitting your pull request:*

* [ ] If this is a new entry, have you submitted a signed [participation form](https://github.com/cncf/k8s-conformance/tree/master/participation-form)?
* [X] Did you include the product/project logo in SVG, EPS or AI format?  
* [X] Does your logo clearly state the name of the product/project and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [ ] If your product/project is open source, did you include the `repo_url`?
* [x] Did you copy and paste the [installation and configuration instructions](https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions) into the README.md file in addition to linking to them?

For a full list of requirements, please refer to these sections of the docs: [_Contents of the PR_](https://github.com/cncf/k8s-conformance/blob/master/instructions.md#contents-of-the-pr), and [_Requirements_](https://github.com/cncf/k8s-conformance/blob/master/instructions.md#requirements).

### CODE REVIEW

**Comment by taylorwaggoner** [comment]
@supershal thanks for submitting this! Could you please also submit a new participation form so that we have the correct company/product name on file? https://github.com/cncf/k8s-conformance/tree/master/participation-form

Also, I just want to confirm that the contact email address will remain @d2iq.com
thanks!

**Comment by supershal** [comment]
@taylorwaggoner Thank you. I have submitted the new participation form. We can keep the email id same for now.

**Comment by taylorwaggoner** [comment]
Great thank you! One last question - do you want to use the Nutanix logo for this? Currently we use the D2iQ logo and call the product "D2iQ Konvoy", so that the logo and product name match. Thanks!

**Comment by supershal** [comment]
We can keep the same logo for now. Konvoy's page and documentation will be still provided from D2iQ website.

**Comment by supershal** [comment]
@taylorwaggoner please let me know if you need any more information from me that would unblock merging this PR

**Comment by taylorwaggoner** [comment]
@supershal ok great. I changed the company name in your listing [here](https://landscape.cncf.io/?group=certified-partners-and-providers&view-mode=card&item=platform--certified-kubernetes-distribution--d2iq-konvoy#platform--certified-kubernetes-distribution). does this look ok? Thanks!

**Comment by supershal** [comment]
Thank you @taylorwaggoner. The page looks great.

**Pull request merged**
