### PR TITLE
Conformance results for v1.13/Kingsoft Cloud

### PR DESCRIPTION
**Pull request by seamounts**

### CODE REVIEW

**Comment by taylorwaggoner** [comment]
@seamounts thank you for submitting.  A few things before we can certify:

1. Please send us a signed [participation form](https://github.com/cncf/k8s-conformance/tree/master/participation-form)
2. Please feel free to add more details about your product to your description in the PRODUCT.yaml file.  You can view examples [on the Landscape](https://landscape.cncf.io/category=certified-kubernetes-distribution,certified-kubernetes-hosted,certified-kubernetes-installer,special&format=card-mode&grouping=category).
3. Please delete your version.txt files in both Pull Requests.  We no longer require that file [in our instructions.](https://github.com/cncf/k8s-conformance/blob/master/instructions.md#contents-of-the-pr)
Thanks!

**Comment by seamounts** [comment]
@taylorwaggoner 
Thanks, I have sent the participation form email and modified the content based on your suggestions.

**Comment by taylorwaggoner** [comment]
Thanks, @seamounts.  Please also updated the "type" in the PRODUCT.yaml to distribution, hosted, or installer based on [these guidelines](https://github.com/cncf/k8s-conformance/blob/master/faq.md#what-is-a-distribution-hosted-platform-and-an-installer). Thanks!

**Comment by seamounts** [comment]
> Thanks, @seamounts. Please also updated the "type" in the PRODUCT.yaml to distribution, hosted, or installer based on [these guidelines](https://github.com/cncf/k8s-conformance/blob/master/faq.md#what-is-a-distribution-hosted-platform-and-an-installer). Thanks!
Thanks, i've updated it. Please check it.

**Comment by taylorwaggoner** [comment]
You are now Certified Kubernetes
https://landscape.cncf.io/format=card-mode&selected=kingsoft-container-engine

**Pull request merged**
