### PR TITLE
Conformance results for v1.15 using Konvoy

### PR DESCRIPTION
**Pull request by hectorj2f**
```
vendor: D2iQ
name: Konvoy
version: v1.0.0
website_url: https://d2iq.com/solutions/ksphere/konvoy
documentation_url: https://docs.d2iq.com/ksphere/konvoy/
product_logo_url: https://docs.d2iq.com/assets/D2IQ_Logotype_Color_Positive.png
type: distribution
description: 'Konvoy is a standalone distribution of Kubernetes that includes a native Kubernetes cluster pre-packaged for deployment with a complement of best-in-class add-on services enabled by default and ready for immediate use.'

```

### CODE REVIEW

**Comment by taylorwaggoner** [comment]
@hectorj2f, thank you for submitting these results. Before we can certify you, you will need to send in a [signed participation agreement](https://github.com/cncf/k8s-conformance/tree/master/participation-form) and either decide to [join CNCF](https://www.cncf.io/about/join/) or pay the [certification fee](https://github.com/cncf/k8s-conformance/blob/master/faq.md#what-is-the-cost-of-certification).  At that point, we can move forward with your PR.  The results look great, but we would need you to update the product file with a new logo that meets [these requirements](https://github.com/cncf/landscape#logos) of being in SVG format and with a transparent background.

At this time, I recommend closing this PR and reopening once you have joined CNCF or paid the fee.  Please let me know if you have any questions!

**Comment by hectorj2f** [comment]
@taylorwaggoner we are already part of the cncf. We are Mesosphere. I am a bit confused about your request about paying a fee.

**Comment by dankohn** [comment]
Please just change vendor to Mesosphere and then we’re happy to process.

**Comment by dankohn** [comment]
Please let us know if this is a new submission or a name change: https://github.com/cncf/k8s-conformance/blob/master/faq.md#do-i-need-to-re-submit-results-if-we-rebrand-our-product

Also, we need an SVG (or EPS or AI), not PNG, version of your logo.

**Comment by hectorj2f** [comment]
@dankohn Yeah, it is a rebranding, but this is a new product. I will change the logo to fit the requirements. We have the official launch on Monday, I hope we can sort this out without any problem :/.

**Comment by dankohn** [comment]
Yes. If you send in a signed participation form for the new product (the Docusign option is easiest), we can approve this over the weekend.

https://github.com/cncf/k8s-conformance/blob/master/participation-form/Certified_Kubernetes_Form.md

**Comment by hectorj2f** [comment]
@dankohn Thanks for the help and guidance. I signed the document and updated the logo with a temporal url for now. I imagine we can update it later.

**Comment by taylorwaggoner** [comment]
You are now Certified Kubernetes.
https://landscape.cncf.io/format=card-mode&organization=mesosphere&selected=d2i-q-konvoy

I have asked Crunchbase to update [Mesosphere's](https://www.crunchbase.com/organization/mesosphere) account name, Crunchbase URL, logo, and website to D2iQ so that your company name appears as D2iQ on the landscape.

Thanks!

**Pull request merged**
