### PR TITLE
Conformance results for v1.19/symplegma

### PR DESCRIPTION
**Pull request by ArchiFleKs**
Signed-off-by: Kevin Lefevre <lefevre.kevin@gmail.com>

### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [X] If this is a new entry, have you submitted a signed [participation form](https://github.com/cncf/k8s-conformance/tree/master/participation-form)?
* [X] Did you include the product/project logo in SVG, EPS or AI format?  
* [X] Does your logo clearly state the name of the product/project and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [X] If your product/project is open source, did you include the `repo_url`?
* [X] Did you copy and paste the [installation and configuration instructions](https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions) into the README.md file in addition to linking to them?

Could you also update the product logo on the CNCF landscape please :)

### CODE REVIEW

**Comment by taylorwaggoner** [comment]
@ArchiFleKs thanks for submitting! The PR looks great, but wanted to quickly chat about your logo request.  We can definitely change the logo, but it needs to include either the company name or the product name in text, not just the icon image.  Also, I believe that is the Particule logo - we have this product under clusterfrak-dynamics so wanted to check.  If you did want to use the full Particule logo, would you also want to change this product's affiliation on the landscape?  Please also note that the text on the logo needs to match with the product name so it alphabetizes correctly. 
thanks!

**Comment by taylorwaggoner** [comment]
@ArchiFleKs checking in! thanks!

**Comment by ArchiFleKs** [comment]
@taylorwaggoner sorry about the delay, we have not decided on the logo yet, do you mind waiting a little bit longer before merging this ?

**Comment by taylorwaggoner** [comment]
No problem!  Just let me know when you're ready!

**Comment by ArchiFleKs** [comment]
@taylorwaggoner should be ok now with the right name and right logo, also I moved it to "installer" which seems more appropriate than distribution.

**Comment by taylorwaggoner** [comment]
@ArchiFleKs updates have been made!  You are now Certified Kubernetes
https://landscape.cncf.io/format=card-mode&organization=particule&selected=symplegma

**Pull request merged**
