### PR TITLE
Conformance results for v1.21/robin.io

### PR DESCRIPTION
**Pull request by mgaunekar**
### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [x] If this is a new entry, have you submitted a signed [participation form](https://github.com/cncf/k8s-conformance/tree/master/participation-form)?
* [x] Did you include the product/project logo in SVG, EPS or AI format?  
* [x] Does your logo clearly state the name of the product/project and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [ ] If your product/project is open source, did you include the `repo_url`?
* [ ] Did you copy and paste the [installation and configuration instructions](https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions) into the README.md file in addition to linking to them?

### CODE REVIEW

**Comment by mgaunekar** [comment]
I used this command to generate results:
sonobuoy run --mode=certified-conformance
is this the right command?

**Comment by mgaunekar** [comment]
I used this command to generate results:
sonobuoy run --mode=certified-conformance
Is this the right command?

*Madhura Gaunekar * | *ROBIN <http://www.robin.io/> | *

*Automate Enterprise Applications on Kubernetes*

**Comment by taylorwaggoner** [comment]
@bernokl @Riaankl do you know what's happening with these test here?

**Comment by Riaankl** [comment]
We traced it back to Sonobuoy and @johnSchnake fixed it with this [PR](https://github.com/vmware-tanzu/sonobuoy/pull/1390).
If you rerun Sonobuoy you should get the correct results to submit.

**Comment by mgaunekar** [comment]
@Riaankl do I have to fetch latest Sonobuoy binary or run the same one and it will pull the latest fixed image?

**Comment by johnSchnake** [comment]
We patched Sonobuoy and released a fixed version here: https://github.com/vmware-tanzu/sonobuoy/releases/tag/v0.53.2

**Comment by mgaunekar** [comment]
thank you. I will re-run the tests.

**Comment by taylorwaggoner** [comment]
you are now Certified Kubernetes

**Pull request merged**
