### PR TITLE
Conformance test results for v1.21/Weave GitOps Enterprise

### PR DESCRIPTION
**Pull request by davidstauffer**
### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [x] If this is a new entry, have you submitted a signed [participation form](https://github.com/cncf/k8s-conformance/tree/master/participation-form)?
* [ ] Did you include the product/project logo in SVG, EPS or AI format?  
* [ ] Does your logo clearly state the name of the product/project and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [ ] If your product/project is open source, did you include the `repo_url`?
* [ ] Did you copy and paste the [installation and configuration instructions](https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions) into the README.md file in addition to linking to them?

### CODE REVIEW

**Comment by taylorwaggoner** [comment]
@davidstauffer is this a new product or just a rebranding of Weave Kubernetes Platform?  thanks!

**Comment by davidstauffer** [comment]
@taylorwaggoner It's the successor of the Weave Kubernetes Platform. Rebranding I think is accurate. Thanks!

**Comment by taylorwaggoner** [comment]
@davidstauffer we had Weave Kubernetes Platform listed as a distribution, but you have this one down as an installer.  Should I go forward with listing it as an installer? Thanks!

**Comment by davidstauffer** [comment]
@taylorwaggoner Yes. Please go forward and list it as an installer. That's better reflecting Weave GitOps Enterprise. Thanks!

**Comment by taylorwaggoner** [comment]
Great thanks! You are now Certified Kubernetes.  I will update the landscape to change the product to Weave GitOps Enterprise as an installer.  Thanks!

**Pull request merged**
