### PR TITLE
Conformance results for v1.16/starlingx

### PR DESCRIPTION
**Pull request by ildikov**
Adding the required description and test results to confirm
the conformance of StarlingX.

The filled out and signed application form is already sent to
the specified email address.

Signed-off-by: Ildiko Vancsa <ildiko.vancsa@gmail.com>

### CODE REVIEW

**Comment by taylorwaggoner** [comment]
@ildikov thanks for submitting!  A couple quick questions for you.  First, could you please add [a repo_url](https://github.com/cncf/k8s-conformance/blob/master/instructions.md#productyaml) to the product.yaml file in order to show that this is Open Source?  

Second, please paste all instructions into the README per [these guidelines](https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions). Or perhaps at a summary of the installation steps? In particular, is there any special configuration necessary to get the tests to pass? We're trying to provide guidance so that your customers can later validate your conformance if they wish to. Thanks!

**Comment by ildikov** [comment]
Thanks @taylorwaggoner for checking the patch. I fixed the repo URL, it points to the collection of the project repositories now. I will also work with the community to make sure the README file has a more detailed description about the installation process and will upload a new commit soon.

Thanks,
Ildikó

**Comment by taylorwaggoner** [comment]
@ildikov, we need the source to be hosted or mirrored to GitHub for the project to show as open source on the landscape. Directions to do so are here: https://help.github.com/en/github/getting-started-with-github/finding-ways-to-contribute-to-open-source-on-github#open-source-projects-with-mirrors-on-github

We require GitHub hosting because we rely on a bunch of their APIs to get metadata about a project.  

Thanks!

**Comment by ildikov** [comment]
@taylorwaggoner Thank you for the background information. I followed an example where I didn't see the GitHub repo. I fixed the url now.

**Comment by ildikov** [comment]
@taylorwaggoner I also added a more detailed description on how to install and configure the environment. Please let me know if that looks sufficient enough.

**Comment by ildikov** [comment]
@taylorwaggoner There is no one specific repository as the pieces of the integrated platform are distributed among the ones listed under the StarlingX project. Only exceptions are the test and documentation related items. Do you want a list of repos excluding those?

**Comment by taylorwaggoner** [comment]
@ildikov, in order to show as open source on the Cloud Native landscape, you'd have to pick one repo to use. People normally use either the main code or an installer. Perhaps https://github.com/starlingx/config?

**Comment by ildikov** [comment]
@taylorwaggoner Thanks for the suggestion, fixed up the repo_url now. Please let me know if there's anything else to edit.

**Comment by taylorwaggoner** [comment]
You are now Certified Kubernetes
https://landscape.cncf.io/format=card-mode&organization=open-stack&selected=starling-x

**Comment by ildikov** [comment]
@taylorwaggoner Awesome, thank you! A quick question. I saw that the page you pointed me to has the @openstack Twitter handle as opposed to @starlingx. Could you please remind how to fix that?

**Comment by taylorwaggoner** [comment]
@ildikov I opened a [pull request](https://github.com/cncf/landscape/pull/1617) to add the StarlingX Twitter URL, so it'll be updated today!
Thanks!

**Comment by ildikov** [comment]
@taylorwaggoner Awesome, thank you for the help!

**Pull request merged**
