### PR TITLE
add Conformance results for v1.18/InsureMO

### PR DESCRIPTION
**Pull request by cdyue**
vendor: eBaoTech
name: InsureMO
version: v1.0.0
website_url: https://portal.insuremo.com/
documentation_url: https://docs.insuremo.com/
type: hosted
product_logo_url: https://portal-tst.insuremo.com/assets/img/InsureMO_Logo_Primary.svg
description: InsureMO is a cloud native PAAS platform for insurance industry based on containerization and Kubernetes technology. It provides a repository of insurance products covering a wide range of standard products worldwide; and rich micro services and reusable APIs related to general insurance, life insurance and health insurance. It also provides a variety of reusable common services and APIs, as well as management, development, monitoring and DevOps tools to help insurers get their products up and running quickly. InsureMO is a cloud-based next generation insurance operation system that connects and enables insurers, traditional channels, affinity partners, and FinTech/InsurTech startups.

### CODE REVIEW

**Comment by taylorwaggoner** [comment]
@cdyue is this a new product or a renaming of eBaoCloud Platform?  You'll need to fill out a new participation form for the product - https://github.com/cncf/k8s-conformance/tree/master/participation-form

Thanks!

**Comment by taylorwaggoner** [comment]
@cdyue checking in on my last comment, thanks!  Can you confirm that this is the same product you already have certified? https://github.com/cncf/k8s-conformance/tree/master/v1.18/ebaocloud
Thanks!

**Comment by cdyue** [comment]
@taylorwaggoner it's an the same product as eBaoCloud, just an alias.

We have submitted the participation form for InsureMO, please check it.

**Comment by taylorwaggoner** [comment]
Ok thanks!  Would you like to rewrite the description for eBaoCloud so that it does not mention InsureMO, since these will be different listings? https://landscape.cncf.io/format=card-mode&organization=e-bao-tech&selected=e-bao-cloud
Thanks!

**Comment by cdyue** [comment]
@taylorwaggoner We will update the description for eBaoCloud later, please approve this PR for InsureMO. Thanks!

**Comment by taylorwaggoner** [comment]
You are now Certified Kubernetes
https://landscape.cncf.io/format=card-mode&selected=insure-mo

**Pull request merged**
