### PR TITLE
Conformance results for v1.20/kubeasz

### PR DESCRIPTION
**Pull request by gjmzj**
### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [x] If this is a new entry, have you submitted a signed [participation form](https://github.com/cncf/k8s-conformance/tree/master/participation-form)?
* [x] Did you include the product/project logo in SVG, EPS or AI format?  
* [x] Does your logo clearly state the name of the product/project and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [x] If your product/project is open source, did you include the `repo_url`?
* [x] Did you copy and paste the [installation and configuration instructions](https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions) into the README.md file in addition to linking to them?

### CODE REVIEW

**Comment by taylorwaggoner** [comment]
@gjmzj thanks for submitting.  I see that you marked "nonprofit" on your participation form.  Could you please provide more details about your nonprofit status? Thanks!

**Comment by gjmzj** [comment]
@taylorwaggoner thanks for your response. By now, all my have is a github repo(github.com/easzlab/kubeasz, Apache License 2.0) . So, it is a nonprofit project, i think.

**Comment by gjmzj** [comment]
@taylorwaggoner I don't know what else to do exactly, please let me know, many thanks!

**Comment by gjmzj** [comment]
OK, here is more about the repository [kubeasz](https://github.com/easzlab/kubeasz):
1. there is no organization, it's just a githhub opensource repository.
2. the first line commited on 26 Nov 2017, more than three years ago.
3. the repository is quite popular in China, with 6.6k stars , 2.5k forks and 50+ contributors.
4. the regular maintainer is only me; and a part time job
5. the very first supported k8s version is v1.6; and updated whenever a new version released; when v1.20 released, i decide to have `kubeasz` passing the conformance test

**Comment by amye** [comment]
@gjmzj, so given that, nonprofit status probably isn't accurate. Can you resubmit the participation form with that removed and we'll follow up?

**Comment by gjmzj** [comment]
so which one should i choose？
image
is there a way for an open source project to participate in the Certified Kubernetes Conformance Program?

**Comment by amye** [comment]
Neither of the above, but community distributions are treated like non-profits. 
We do need accurate paperwork though: https://github.com/cncf/k8s-conformance/blob/master/faq.md#what-about-community-distributions

**Comment by gjmzj** [comment]
@amye OK, i've re-submitted the `Participation Form` by DocuSign.
Thanks!

**Comment by gjmzj** [comment]
@amye OK, i've re-submitted the `Participation Form` by DocuSign.
Thanks!

**Comment by amye** [comment]
Participation form is in review on our side.

**Comment by amye** [comment]
Participation form approved

**Comment by amye** [comment]
You are now Certified Kubernetes

**Pull request merged**
