### PR TITLE
Conformance results for v1.20/vcluster

### PR DESCRIPTION
**Pull request by LukasGentele**
### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [x] If this is a new entry, have you submitted a signed [participation form](https://github.com/cncf/k8s-conformance/tree/master/participation-form)?
* [x] Did you include the product/project logo in SVG, EPS or AI format?  
* [x] Does your logo clearly state the name of the product/project and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [x] If your product/project is open source, did you include the `repo_url`?
* [x] Did you copy and paste the [installation and configuration instructions](https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions) into the README.md file in addition to linking to them?

### CODE REVIEW

**Comment by LukasGentele** [comment]
> This conformance request has the correct list of tests present in the junit file but at least one of the tests in e2e.log failed

I don't think this is correct. The `e2e.log` states:
```
SUCCESS! -- 311 Passed | 0 Failed | 0 Pending | 5356 Skipped
PASS

Ginkgo ran 1 suite in 1h28m22.852165557s
Test Suite Passed
```

**Comment by ErinThacker** [comment]
@hh - can you take a look at this e2e.log error? Much appreciated!

**Comment by bernokl** [comment]
I am unable to reproduce the error in my testing repo. I think it might have been a flake.
Please re-submit the pr, or could we please remove the labels @amye ?

**Comment by amye** [comment]
@bernokl We're seeing a few of these, something else going on?

**Comment by bernokl** [comment]
The timing of the ones I see makes me think there might have been issues with the infrastructure last week.
I have looked at the cluster and currently everything seems healthy.
Could you please remove labels on the ones with evidence missing and allow the bot to re-evaluate them?

**Comment by amye** [comment]
> The timing of the ones I see makes me think there might have been issues with the infrastructure last week.
> I have looked at the cluster and currently everything seems healthy.
> Could you please remove labels on the ones with evidence missing and allow the bot to re-evaluate them?

You were right, it was a infra bug!

**Comment by LukasGentele** [comment]
Thanks @amye, @bernokl and @ErinThacker for taking a look at this. Glad the infra hiccup has been resolved.

**Pull request merged**
