### PR TITLE
Conformance results for v1.18/mirantis-docker-enterprise

### PR DESCRIPTION
**Pull request by cranzy**
### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [x] If this is a new entry, have you submitted a signed [participation form](https://github.com/cncf/k8s-conformance/tree/master/participation-form)?
* [x] Did you include the product/project logo in SVG, EPS or AI format?  
* [x] Does your logo clearly state the name of the product/project and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [x] If your product/project is open source, did you include the `repo_url`?
* [x] Did you copy and paste the [installation and configuration instructions](https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions) into the README.md file in addition to linking to them?

### CODE REVIEW

**Comment by taylorwaggoner** [comment]
Hi @cranzy - just checking in.  Are you ready for review or still keeping as a draft? Thanks!

**Comment by cranzy** [comment]
> Hi @cranzy - just checking in. Are you ready for review or still keeping as a draft? Thanks!
Hi, 
for now we'll keep it as a draft. I'll update the PR once we are ready to proceed. Thank you.

**Comment by james-nesbitt** [comment]
Hi @taylorwaggoner.  Just wanted to clarify that we (Mirantis) started this PR early in order to prepare for an upcoming product release.  The test results and instructions are only viable on the day of the release, as the testable artifacts are not yet public.

**Comment by taylorwaggoner** [comment]
Ok great thanks!  Just @ mention me when you change this from draft to ready for review.  Thanks!

**Comment by cranzy** [comment]
@taylorwaggoner This PR is ready for review. Thank you!

**Comment by taylorwaggoner** [comment]
Great thanks! You are now Certified Kubernetes

**Pull request merged**
