### PR TITLE
Conformance results for v1.15/talos

### PR DESCRIPTION
**Pull request by rsmitty**
Signed-off-by: Spencer Smith <robertspencersmith@gmail.com>

### CODE REVIEW

**Comment by taylorwaggoner** [comment]
@rsmitty, thanks for submitting!  Your results look great!  Once we receive a [signed participation form](https://github.com/cncf/k8s-conformance/tree/master/participation-form) from you, we'll be able to merge.  Thanks!

**Comment by rsmitty** [comment]
@taylorwaggoner Thanks for taking a look! I've just emailed the participation form as well.

**Comment by taylorwaggoner** [comment]
@rsmitty, I wanted to confirm that this is the [correct repo](https://github.com/cncf/k8s-conformance/blob/master/instructions.md#productyaml) for your product? https://github.com/talos-systems/talos
If so, please add to your product.yaml file.  Thanks!

**Comment by rsmitty** [comment]
@taylorwaggoner Yes! That is our repo_url. Apologies. I just updated the PR.

**Comment by taylorwaggoner** [comment]
You are now Certified Kubernetes
https://landscape.cncf.io/format=card-mode&selected=talos

**Pull request merged**
