### PR TITLE
Conformance results for v1.15/huawei-fusionstage

### PR DESCRIPTION
**Pull request by itachipein**
Conformance results for v1.15/huawei-fusionstage

### CODE REVIEW

**Comment by itachipein** [comment]
@kevin-wangzefeng

**Comment by kevin-wangzefeng** [comment]
LGTM

**Comment by taylorwaggoner** [comment]
@itachipein, thank you for submitting.  The previous name we have listed for this product is Huawei FusionStage, not HUAWEI CLOUD Stack FusionStage.  Can you please confirm that you'd like to change the name on the [Cloud Native Landscape](https://landscape.cncf.io/format=card-mode&organization=huawei-technologies&selected=huawei-fusion-stage)? 

Also, please paste the instructions to deploy a cluster into the README file, rather than referring users to the FusionStage documentation.

Thanks!

**Comment by itachipein** [comment]
@taylorwaggoner Thank you for your proposal. I have changed the product name back to HUAWEI FusionStage

And also, I added the main steps to deploy a cluster into the README file.

Please review again. Thanks!

**Comment by taylorwaggoner** [comment]
Thanks! You are now certified Kubernetes

**Pull request merged**
