### PR TITLE
Submitting k8s conformance results for v1.21 for windrivercloud.

### PR DESCRIPTION
**Pull request by gwaines**
### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [x] If this is a new entry, have you submitted a signed [participation form](https://github.com/cncf/k8s-conformance/tree/master/participation-form)?
* [x] Did you include the product/project logo in SVG, EPS or AI format?  
* [x] Does your logo clearly state the name of the product/project and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [x] If your product/project is open source, did you include the `repo_url`?
* [x] Did you copy and paste the [installation and configuration instructions](https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions) into the README.md file in addition to linking to them?

### CODE REVIEW

**Comment by Riaankl** [comment]
@gwaines I think the point of failure is the file name of `v1.21/windrivercloud/e2e.log.txt` it should be the `v1.21/windrivercloud/e2e.log` file sans .`txt`
We are working on fix the bot to give a better error report.
Can you please update the file in your commit?

**Comment by gwaines** [comment]
I updated the name of the e2e.log file.
Let me know if there is anything else I need to do.

**Comment by gwaines** [comment]
DOH … sorry about that.
updated.
Greg

**Comment by Riaankl** [comment]
Thanks @gwaines for helping to expose the bug on the `bot`.
Bot is fixed now and after updating your file you PR is labeled with all the requiered labels.

**Comment by taylorwaggoner** [comment]
@gwaines thanks for submitting! Could you add a bit more detail, or steps, to set up the cluster?

> Set up a cluster following the Wind River Cloud Platform documentation.

Your company won't automatically appear in the landscape once this PR is merged - I will add them once it's approved. Typical turnaround time for approvals is 3-5 days.

Thanks!

**Comment by taylorwaggoner** [comment]
@gwaines apologies, I wasn't very clear in my last comment.  Could you please add the detailed instructions to the readme, rather than point to documentation? Please see our guidelines here: https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions
Thank you and sorry for the extra step!

**Comment by gwaines** [comment]
Any update on this PULL REQUEST ?

**Comment by taylorwaggoner** [comment]
You are now Certified Kubernetes.  Your listing will be available on the landscape soon!
https://github.com/cncf/landscape/pull/2492

**Comment by gwaines** [comment]
Thanks Taylor

**Comment by gwaines** [comment]
Hey Taylor,
Was just checking here: https://www.cncf.io/certification/software-conformance/ 
WINDRIVER shows up there now ... thanks.

One question ... how come when I select WINDRIVER, and it displays the info for Wind River Cloud Platform (WRCP), it shows as "License Not Open Source".  Wind River Cloud Platform is open source, based on the 'openstack starlingx' project.
I remember we had this issue when we initially did conformance for WRCP for k8s v1.16 or k8s v1.18 ... and it was due to me filling out something incorrectly in the PRODUCT.yaml .

Can you let me know what I need to update ?

**Comment by taylorwaggoner** [comment]
@gwaines sorry about that, that's my fault!  I didn't put in your GitHub repo URL when I added the product.  Apologies!  I've put in a new PR to fix here: https://github.com/cncf/landscape/pull/2503
Thanks!

**Comment by gwaines** [comment]
Thanks Taylor.
Greg.

**Pull request merged**
