### PR TITLE
Conformance results for v1.15/ccp

### PR DESCRIPTION
**Pull request by alexchan**
### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [ ] If this is a new entry, have you submitted a signed [participation form](https://github.com/cncf/k8s-conformance/tree/master/participation-form)?
* [ ] Did you include the product/project logo in SVG, EPS or AI format?  
* [ ] Does your logo clearly state the name of the product/project and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [ ] If your product/project is open source, did you include the `repo_url`?
* [x] Did you copy and paste the [installation and configuration instructions](https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions) into the README.md file in addition to linking to them?

### CODE REVIEW

**Comment by taylorwaggoner** [comment]
@alexchan the results look great, but one question.  Are you able to copy/paste the installation and configuration instructions into the README per [these guidelines](https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions)? Thanks!

**Comment by alexchan** [comment]
@taylorwaggoner The README has been updated with the steps on how the tests were performed.

**Comment by taylorwaggoner** [comment]
@alexchan thanks!  Are there any specific steps needed to create the cluster from the admin control dashboard that you could add?

**Comment by alexchan** [comment]
@taylorwaggoner Detailed cluster creation steps using the control dashboard has been added.  Thanks for reviewing!

**Comment by taylorwaggoner** [comment]
Thanks!  You are now Certified Kubernetes

**Pull request merged**
