### PR TITLE
Submit SUSE CaaS Platform 4.1

### PR DESCRIPTION
**Pull request by qnetter**
### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [x] If this is a new entry, have you submitted a signed [participation form](https://github.com/cncf/k8s-conformance/tree/master/participation-form)?
* [x] Did you include the product/project logo in SVG, EPS or AI format?  
* [x] Does your logo clearly state the name of the product/project and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [x] If your product/project is open source, did you include the `repo_url`?
* [x] Did you copy and paste the [installation and configuration instructions](https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions) into the README.md file in addition to linking to them?

### CODE REVIEW

**Comment by taylorwaggoner** [comment]
Thanks for submitting!  Before we can certify, please paste the deployment/installation instructions into the README, per these[ new guidelines](https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions).  Thanks!

**Comment by taylorwaggoner** [comment]
@qnetter checking in! Thanks!

**Comment by qnetter** [comment]
Just saw this now. Will check out others to model.

**Comment by taylorwaggoner** [comment]
Thanks, @qnetter

**Comment by qnetter** [comment]
More complete instructions for README.

**Comment by qnetter** [comment]
@taylorwaggoner this should be more to your liking.

**Comment by taylorwaggoner** [comment]
Thanks, @qnetter!  The instructions for 1.16 look great!  Could you please copy to 1.17 as well? Thanks!

**Comment by qnetter** [comment]
Of course. Just wanted to wait to get to completion on this one first.

**Comment by qnetter** [comment]
Of course. Just wanted to wait to get to completion on this one first.

**Comment by qnetter** [comment]
Should be ready to merge for 1.17.

**Comment by taylorwaggoner** [comment]
Hi @qnetter could you please review the files you included here?  There should be 8, not 10 most likely (Product, e2e.log, README, and junit for each version).  I see there's a random README file that's not under a SUSE directory.  Thanks!

**Comment by qnetter** [comment]
Sorry, just saw this. I'm a little lost. Can I just close this PR and submit the relevant 8 files again?

**Comment by qnetter** [comment]
Pretty sure this (a) deletes the misplaced README.md; (b) deletes the "foo" file; (c) replaces the 1.17 README.md with the correct file.

**Comment by taylorwaggoner** [comment]
Great, thank you so much!  You are now Certified Kubernetes

**Pull request merged**
