### PR TITLE
Update conformance results for v1.21/vmware-tanzu-kubernetes-grid

### PR DESCRIPTION
**Pull request by jayunit100**
### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [x] If this is a new entry, have you submitted a signed [participation form](https://github.com/cncf/k8s-conformance/tree/master/participation-form)?
* [x] Did you include the product/project logo in SVG, EPS or AI format?  
* [x] Does your logo clearly state the name of the product/project and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [x] If your product/project is open source, did you include the `repo_url`?
* [x] Did you copy and paste the [installation and configuration instructions](https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions) into the README.md file in addition to linking to them?

### CODE REVIEW

**Comment by jayunit100** [comment]
```
      <testcase name="[sig-api-machinery] ResourceQuota [Feature:ScopeSelectors] should verify ResourceQuota with best effort scope using scope-selectors." classname="Kubernetes e2e suite" time="0">
```

The above test was flagged as missing, any idea why?

**Comment by jayunit100** [comment]
merged the XML test results, retrying....

**Comment by jayunit100** [comment]
this is just an update, not a submissino, renamed PR appropriately.

**Comment by jayunit100** [comment]
resubmitted... im not sure why it sais these tests are failing.....

**Comment by randomvariable** [comment]
The tests need to be run without the parallel option I think?

**Comment by Riaankl** [comment]
@jayunit100 I looked at your e2e test result file and saw it contain 320 passed tests. Looking at this [PR](https://github.com/cncf/k8s-conformance/pull/1898) where the Bot is happy with the results there is [239](https://raw.githubusercontent.com/cncf/k8s-conformance/d09525a1862602ad19300a6b60c091c718d9955d/v1.21/alvistack-vagrant-kubernetes/e2e.log) tests that passes for v1.21. (239-320=19) That explain the list of 19 missing tests.
The bot check that the test contained in the e2e file match the test list for the corrisponding release.
Unless it contain and pass the correct list of tests the bot will complain about it.

Appoligies for the bot continually spamming you about the failure. we are working on that part.

**Comment by jayunit100** [comment]
@Riaankl ok thanks ! i guess we can merge this, then ?

**Comment by jayunit100** [comment]
@Riaankl ok thanks ! i guess we can merge this, then ?... 

i.e. it sounds like the bot is just complaining that there are extra tests that were run....

**Comment by jayunit100** [comment]
i think i can update this later today with a better e2e.log.  im wondering if maybe, combining the parallel results simply confused the bot somehow ....

**Comment by jayunit100** [comment]
I updated the conformance tests with a new cut of 1.21 that wasnt made in parallel.  maybe the bot will b happier this time

**Comment by jayunit100** [comment]
im going to close this, VMWares official conformance results are now at https://github.com/cncf/k8s-conformance/tree/master/v1.22/vmware-tanzu-kubernetes-grid

**Pull request closed without merging**
