### PR TITLE
Conformance results for v1.14/olcne

### PR DESCRIPTION
**Pull request by mark-au**
Note this is a re-certification and rename from https://github.com/cncf/k8s-conformance/pull/715

### CODE REVIEW

**Comment by taylorwaggoner** [comment]
@mark-au , thank you for submitting.  Before we can change the name, you will need to send in a [signed participation form](https://github.com/cncf/k8s-conformance/tree/master/participation-form), [per these guidelines](https://github.com/cncf/k8s-conformance/blob/master/faq.md#do-i-need-to-re-submit-results-if-we-rebrand-our-product).  

Please also [review the guidelines](https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions) for the README file and copy/paste all installation instructions into the file.

Last, please email me the SVG logo at twaggoner@linuxfoundation.org.
Thanks!

**Comment by mark-au** [comment]
Thanks for the quick response. I'll get the participation form updated and SVG emailed.
I did note the guidelines and included a Vagrant based example at the bottom of the README but will update it to include all steps.

**Comment by mark-au** [comment]
README updated.

**Comment by taylorwaggoner** [comment]
@mark-au - wanted to check in - have you sent the new participation form in yet?  Thanks!

**Comment by mark-au** [comment]
Not yet - it's currently undergoing review but I'll get back to you

**Comment by mark-au** [comment]
Legal review is taking longer than expected. Are you happy for this PR to remain open or shall I create a new one when the participation form is submitted?

**Comment by taylorwaggoner** [comment]
We can keep this open as long as you need, thanks!

**Comment by Djelibeybi** [comment]
Hey folks, just a heads-up that we emailed our freshly resigned form a few minutes ago, so hopefully you should receive that shortly and we can (finally) get this merged! :) We really do thank you for your patience.

**Comment by dankohn** [comment]
Can you please revise the PR to show that the only thing that has changed is the product name, as we can't accept a new certification for 1.14. Also, are you going to be adding a certification for 1.15, 1.16, or 1.17?

**Comment by Djelibeybi** [comment]
Hey Dan, we changed the product name when we updated Kubernetes from 1.12 to 1.14 so both the name and the version changed at the same time. Why is this a problem?

**Comment by Djelibeybi** [comment]
As @mark-au referenced, we got certification on our proposed 1.14 (previous name) via https://github.com/cncf/k8s-conformance/pull/715 release but then changed name and installation method and open this PR. So there is a previously certified 1.14 version, this is an update to that.

**Comment by Djelibeybi** [comment]
We will be adding certification for newer versions as soon as our builds are ready. Hoping to target 1.17 next.

**Comment by mark-au** [comment]
Just to be clear @dankohn how would you like the PR changed? I believe you want me to rename v1.14/ocsk/e2e.log file to v1.14/olcne/e2e.log instead of providing a new file and no longer add v1.14/olcne/sonobuoy.tar.gz?

**Comment by taylorwaggoner** [comment]
@mark-au I believe Dan meant to open a new PR that includes the product.yaml file with the new product name.  We don't need new e2e.logs, as we can't accept new results for 1.14.  And then once you are ready to submit results for 1.17, you would open another new PR that includes all of the required files.  

At this point, we just want to reflect the name change for the product in your most recent results for 1.14 and then we'll update on the Cloud Native Landscape.

**Comment by mark-au** [comment]
Thanks for the guidance @taylorwaggoner, this PR closed and #892 opened

**Pull request closed without merging**
