### PR TITLE
Conformance results for v1.18/kops

### PR DESCRIPTION
**Pull request by mikesplain**
### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [x] If this is a new entry, have you submitted a signed [participation form](https://github.com/cncf/k8s-conformance/tree/master/participation-form)?
* [x] Did you include the product/project logo in SVG, EPS or AI format?  
* [x] Does your logo clearly state the name of the product/project and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [x] If your product/project is open source, did you include the `repo_url`?
* [x] Did you copy and paste the [installation and configuration instructions](https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions) into the README.md file in addition to linking to them?

### CODE REVIEW

**Comment by taylorwaggoner** [comment]
@mikesplain thanks for submitting.  A couple things here before we can move forward.  

First, I noticed in your e2e.log that the kube-apiserver and e2e test version are v1.17.5 and should match the conformance version of 1.18.  See [#4 here](https://github.com/cncf/k8s-conformance/blob/master/reviewing.md#technical-requirements) for more info. Please update.

We have also started to tighten our README requirements per [these guidelines](https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions). Please update your README to include all relevant information in addition to providing the URL.  We're trying to provide step by step guidance so that your customers can later validate your conformance if they wish to. Thanks!

**Comment by mikesplain** [comment]
Oh gosh, how embarrassing. Currently kops 1.18 doesn't default to kubernetes 1.18.  I'll get that fixed up and update the readme asap. Thanks!

**Comment by taylorwaggoner** [comment]
@mikesplain just checking in!

**Comment by mikesplain** [comment]
Hi @taylorwaggoner so sorry for the delay on this, but I had realized how long that README.md was going to take.  I this this is more in line with what you all are looking for.

Let me know if I missed anything! Thanks!

**Comment by taylorwaggoner** [comment]
Great thanks!  You are now Certified Kubernetes

**Pull request merged**
