### PR TITLE
Conformance results for v1.19/dahua-MagicCube

### PR DESCRIPTION
**Pull request by dahuaAdmin**
### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [x] If this is a new entry, have you submitted a signed [participation form](https://github.com/cncf/k8s-conformance/tree/master/participation-form)?
* [x] Did you include the product/project logo in SVG, EPS or AI format?  
* [x] Does your logo clearly state the name of the product/project and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [ ] If your product/project is open source, did you include the `repo_url`?
* [ ] Did you copy and paste the [installation and configuration instructions](https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions) into the README.md file in addition to linking to them?

### CODE REVIEW

**Comment by ErinThacker** [comment]
Oh hold until CNCF membership is confirmed.

**Comment by taylorwaggoner** [comment]
@dahuaAdmin please provide more information about your product.  I'm not seeing any information on the website you linked.  You will also need to provide detailed, step by step instructions for how to install/configure your Kubernetes implementation, in your README.  Thanks!

**Comment by dahuaAdmin** [comment]
Product details have been updated on readme.

**Comment by dahuaAdmin** [comment]
@taylorwaggoner  Product details have been updated on readme.

**Comment by taylorwaggoner** [comment]
@dahuaAdmin thank you for providing more information about your product.  Could you please add more details about the steps in `2.Install Dahua Magic Cube Platform（Private Clouds）`about how to configure? Thanks!

**Comment by dahuaAdmin** [comment]
@taylorwaggoner  detailed installation and configuration instructions have been submitted.Thx!

**Comment by taylorwaggoner** [comment]
You are now Certified Kubernetes
https://landscape.cncf.io/card-mode?organization=dahua-technology&selected=dahua-magic-cube-platform

**Pull request merged**
