### PR TITLE
Conformance results for v1.13/kops

### PR DESCRIPTION
**Pull request by mikesplain**
Conformance results for v1.13/kops

Fixes https://github.com/kubernetes/kops/issues/7523

### CODE REVIEW

**Comment by mikesplain** [comment]
Also updated in regards to discussion on https://github.com/cncf/k8s-conformance/pull/708

**Comment by dankohn** [comment]
You mentioned updating it but haven't done so yet...

**Comment by mikesplain** [comment]
So sorry @dankohn! Fixed.

**Comment by taylorwaggoner** [comment]
Thanks! You are now Certified Kubernetes.

**Pull request merged**
