### PR TITLE
Conformance results for v1.17/vexxhost

### PR DESCRIPTION
**Pull request by guilhermesteinmuller**
### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [ ] If this is a new entry, have you submitted a signed [participation form](https://github.com/cncf/k8s-conformance/tree/master/participation-form)?
* [ ] Did you include the product/project logo in SVG, EPS or AI format?  
* [ ] Does your logo clearly state the name of the product/project and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [ ] If your product/project is open source, did you include the `repo_url`?
* [ ] Did you copy and paste the [installation and configuration instructions](https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions) into the README.md file in addition to linking to them?

### CODE REVIEW

**Comment by taylorwaggoner** [comment]
@guilhermesteinmuller thanks for submitting.  I noticed in your e2e.log that zero tests are showing in the "Passed" category.  Could you please take a look?  I believe this is an error, as that number tends to be over 200.   Thanks!

> SUCCESS! -- 0 Passed | 0 Failed | 0 Pending | 4842 Skipped

**Comment by guilhermesteinmuller** [comment]
Thank you so much @taylorwaggoner for pointing this out! 

Could you check if is everything ok now?

**Comment by guilhermesteinmuller** [comment]
thank you so much @taylorwaggoner to point that out! 

Could you check if everything is ok now?

**Comment by taylorwaggoner** [comment]
You are now Certified Kubernetes

**Pull request merged**
