### PR TITLE
Conformance results for v1.11/openshift-iks

### PR DESCRIPTION
**Pull request by rtheis**
Red Hat OpenShift on IBM Cloud version 3.11.129 conformance
results based on Kubernetes version 1.11.

### CODE REVIEW

**Comment by taylorwaggoner** [comment]
@rtheis, thank you for submitting, but I have a few items to go over with you about this PR. We're only certifying for v1.13, 1.14 and 1.15 right now, per [these guidelines](https://github.com/cncf/k8s-conformance/blob/master/faq.md#what-versions-of-kubernetes-can-be-certified), so we will not be able to review this PR for v1.11. 

Please confirm that this is a new product that you are certifying for the first time, and not an [existing certified product](https://docs.google.com/spreadsheets/d/1LxSqBzjOxfGx3cmtZ4EbB_BGCxT_wlxW_xgHVVa23es/edit#gid=0) for IBM or Red Hat?  If new, please send us a new [participation form](https://github.com/cncf/k8s-conformance/tree/master/participation-form) for it.  

Please include a link to your logo in SVG format when you open a PR for a more recent version.

Also, we no longer require a version.txt file per [these instructions](https://github.com/cncf/k8s-conformance/blob/master/instructions.md#contents-of-the-pr).

Please let us know if you have any questions!  Thanks!

**Comment by rtheis** [comment]
@taylorwaggoner Thanks for the review.  If you don't mind, I'll contact you via slack to discuss.

**Comment by taylorwaggoner** [comment]
@rtheis, sounds good!

**Comment by rtheis** [comment]
@taylorwaggoner Sorry, I tried to contact you via slack DM, but have been experience numerous slack issues on my end.  Anyway, I'll respond here.

This is a new product that we are certifying for the first time.  I would gladly send in a new participation form, but it sounds like the biggest problem is that Kubernetes v1.11 cannot be certified.  So I assume there's really nothing we can do from a certification perspective until the product reaches a certifiable Kubernetes release.  When we do get there, I will be sure to send the participation form, include a proper logo and remove version.txt.  Thanks.

**Pull request closed without merging**
