### PR TITLE
Conformance results for v1.20 OpenShift (4.7.0)

### PR DESCRIPTION
**Pull request by smarterclayton**
### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [x] If this is a new entry, have you submitted a signed [participation form](https://github.com/cncf/k8s-conformance/tree/master/participation-form)?
* [x] Did you include the product/project logo in SVG, EPS or AI format?  
* [x] Does your logo clearly state the name of the product/project and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [x] If your product/project is open source, did you include the `repo_url`?
* [x] Did you copy and paste the [installation and configuration instructions](https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions) into the README.md file in addition to linking to them?

### CODE REVIEW

**Comment by smarterclayton** [comment]
Hrm... I see 

```
<testcase name="[k8s.io] Container Runtime blackbox test on terminated container should report termination message [LinuxOnly] from log output if TerminationMessagePolicy FallbackToLogsOnError is set [NodeConformance] [Conformance]" classname="Kubernetes e2e suite" time="5.214857198"></testcase>
```
in the junit and 

```
• [SLOW TEST:5.215 seconds]
[k8s.io] Container Runtime
/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:624
  blackbox test
  /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/common/runtime.go:41
    on terminated container
    /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/common/runtime.go:134
      should report termination message [LinuxOnly] from log output if TerminationMessagePolicy FallbackToLogsOnError is set [NodeConformance] [Conformance]
      /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:629
------------------------------
{"msg":"PASSED [k8s.io] Container Runtime blackbox test on terminated container should report termination message [LinuxOnly] from log output if TerminationMessagePolicy FallbackToLogsOnError is set [NodeConformance] [Conformance]","total":-1,"completed":47,"skipped":939,"failed":0}
```
in the submitted logs.  Why would the automation not find that?

**Comment by smarterclayton** [comment]
(I also compared the tests and I have a 1:1 match with the test names run for a number of other 1.20 conformance tests)

**Comment by smarterclayton** [comment]
@ErinThacker can you point me to how I can debug the bot not detecting the test correctly?

**Comment by ErinThacker** [comment]
@smarterclayton - let me take a look with a colleague and get back to you on Monday.

**Comment by smarterclayton** [comment]
Talked with @hh and I think it's https://github.com/cncf-infra/prow-config/blob/9d3c12d48ea6dd8f42dfd864e047dffac1ea59b2/prow/external-plugins/verify-conformance-tests/plugin/plugin.go#L365

The junit here is:

```
<testsuites>
	<testsuite name="Kubernetes e2e suite" tests="311" skipped="0" failures="0" time="6847.197805231001">
		<testcase name="[k8s.io] Container Lifecycle Hook when create a pod with lifecycle hook should execute poststart exec hook properly [NodeConformance] [Conformance]" classname="Kubernetes e2e suite" time="15.435896438"></testcase>
```

Which is a valid junit structure (and is created by some build processing tooling).  It looks like the PR check is only checking what sonobuoy generates, which is a bit too strict.  It's probably enough to have the unmarshal struct have both "testsuites" and "testsuite" and scan both.  In the meantime I'll manually update the junit.

https://llg.cubic.org/docs/junit/

**Comment by ErinThacker** [comment]
You are now certified Kubernetes.

**Pull request merged**
