### PR TITLE
Conformance results for 1.16/docker-desktop-for-mac

### PR DESCRIPTION
**Pull request by ulrich**
### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [x] If this is a new entry, have you submitted a signed [participation form](https://github.com/cncf/k8s-conformance/tree/master/participation-form)?
* [ ] Did you include the product/project logo in SVG, EPS or AI format?  
* [x] Does your logo clearly state the name of the product/project and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [ ] If your product/project is open source, did you include the `repo_url`?
* [x] Did you copy and paste the [installation and configuration instructions](https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions) into the README.md file in addition to linking to them?

Add conformance test results for 1.16/docker-desktop-for-mac

Signed-off-by: Ulrich VACHON <ulrich.vachon@docker.com>

### CODE REVIEW

**Comment by taylorwaggoner** [comment]
@ulrich thanks for submitting!  We're in the process of asking everyone to make sure that their README files provide clear step by step instructions for how to create your conformance results.  Are there any additional installation or configuration instructions that you could add to your README here and in #1010 ?  Thanks!

**Comment by ulrich** [comment]
@taylorwaggoner Indeed, I just used a versioned binary of Sonobuoy (0.16). I can amend the README. Thanks!

**Comment by taylorwaggoner** [comment]
You are now Certified Kubernetes

**Comment by ulrich** [comment]
Thank you @taylorwaggoner

**Pull request merged**
