### PR TITLE
Conformance results for v1.17/h3c-cloudos

### PR DESCRIPTION
**Pull request by Yzerost**
### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [ *] If this is a new entry, have you submitted a signed [participation form](https://github.com/cncf/k8s-conformance/tree/master/participation-form)?
* [ *] Did you include the product/project logo in SVG, EPS or AI format?  
* [ *] Does your logo clearly state the name of the product/project and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [ ] If your product/project is open source, did you include the `repo_url`?
* [* ] Did you copy and paste the [installation and configuration instructions](https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions) into the README.md file in addition to linking to them?

### CODE REVIEW

**Comment by taylorwaggoner** [comment]
@Yzerost thanks!  Are there any installation and configuration instructions that you could copy and paste into the README, based on [these guidelines](https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions)? In particular, is there any special configuration necessary to get the tests to pass? We're trying to provide guidance so that your customers can later validate your conformance if they wish to.

**Comment by Yzerost** [comment]
@taylorwaggoner thanks!The installation instructions has updated in README.md and no special configuration necessary to get the tests to pass. Please check .Best Wishes~

**Comment by Yzerost** [comment]
@taylorwaggoner Sorry to bother you，can i know what's wrong with my pull request, is there something need to update?Please let me know.Our certification will expire on March25,2020, please help to handle this PR before expired,Thank you very much!!

**Comment by taylorwaggoner** [comment]
@Yzerost sorry for the delay here.  In your README you have included this step:

> Follow the instructions on the web UI and deploy H3C CloudOS Platform

Could you post these instructions or provide a summary?  We are asking that all installation and configuration instructions be pasted into the README, from start to finish, so that a customer could follow along and get the same results.  Thanks1

**Comment by Yzerost** [comment]
@taylorwaggoner Thanks you for your reply. I have updated README and add a summary of installation and configuration instructions . please check again .Thank you very much !

**Comment by taylorwaggoner** [comment]
Thanks! You are now Certified Kubernetes

**Pull request merged**
