### PR TITLE
Conformance results for v1.22/scaleway

### PR DESCRIPTION
**Pull request by jtherin**
### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [x] If this is a new entry, have you submitted a signed [participation form](https://github.com/cncf/k8s-conformance/tree/master/participation-form)?
* [x] Did you include the product/project logo in SVG, EPS or AI format?  
* [x] Does your logo clearly state the name of the product/project and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [ ] If your product/project is open source, did you include the `repo_url`?
* [x] Did you copy and paste the [installation and configuration instructions](https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions) into the README.md file in addition to linking to them?

### CODE REVIEW

**Comment by jtherin** [comment]
I've run `sonobuoy run --mode=certified-conformance` with 0 failed, a bug in sonobuoy or in the bot ?

**Comment by jtherin** [comment]
Seems caused by vmware-tanzu/sonobuoy#1388.

**Comment by Riaankl** [comment]
We traced it back to Sonobuoy and @johnSchnake fixed it with this [PR](https://github.com/vmware-tanzu/sonobuoy/pull/1390).
I see the rerun of Sonobuoy gott the correct results to submit.

**Comment by Sh4d1** [comment]
Yep it was built from master branch on the last run!

**Comment by taylorwaggoner** [comment]
You are now Certified Kubernetes

**Pull request merged**
