### PR TITLE
Rename aks to alauda-aks to avoid namespace clash

### LINKED ISSUE #453: AKS naming collision
It looks like in 1.13 conformance that the aks directory name (that was used by Azure Kubernetes Service) prior to 1.13 has now been used by Alauda Kubernetes (AKS). 
Reference:

https://github.com/cncf/k8s-conformance/tree/master/v1.13/aks
https://github.com/cncf/k8s-conformance/tree/master/v1.12/aks
https://github.com/cncf/k8s-conformance/tree/master/v1.11/aks
https://github.com/cncf/k8s-conformance/tree/master/v1.10/aks

I suggest that we prefix the aks with the provider name: eg. azure-aks and alauda-aks. 

cc @taylorwaggoner @jing2uo

### PR DESCRIPTION
**Pull request by lachie83**
Fixes #453

/cc @dankohn @WilliamDenniss @taylorwaggoner @jing2uo

Signed-off-by: Lachlan Evenson <lachlan.evenson@microsoft.com>

### CODE REVIEW

**Comment by dankohn** [comment]
@taylorwaggoner Please update the links in https://docs.google.com/spreadsheets/d/1LxSqBzjOxfGx3cmtZ4EbB_BGCxT_wlxW_xgHVVa23es/edit#gid=0 and then merge this.

**Comment by cimomo** [comment]
Hi @lachie83 , please rename the directory as "alauda-kubernetes". Thanks!

**Comment by lachie83** [comment]
I've renamed the directory at the request of @cimomo.

cc @dankohn @taylorwaggoner

**Comment by taylorwaggoner** [comment]
Thank you for updating

**Pull request merged**
