### PR TITLE
Require e2e test version to match conformance version

### PR DESCRIPTION
**Pull request by dankohn**
I believe this change matches the original intent.

### CODE REVIEW

**Comment by dims** [comment]
👍

**Comment by spiffxp** [comment]
Lgtm. Good catch

**Comment by johnSchnake** [comment]
https://github.com/kubernetes/kubernetes/blob/5268f69405251a4a74130fa903e055a59071179a/test/e2e/e2e.go#L133 is the code from the test output (not Sonobuoy) where this is printed.

**Comment by WilliamDenniss** [comment]
+1, I believe this follows the original intent.

**Comment by dankohn** [comment]
@taylorwaggoner excellent job noticing this discrepancy.

**Pull request merged**
