### PR TITLE
Conformance results for v1.20/openstack-magnum

### PR DESCRIPTION
**Pull request by brtknr**
### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [x] If this is a new entry, have you submitted a signed [participation form](https://github.com/cncf/k8s-conformance/tree/master/participation-form)?
* [x] Did you include the product/project logo in SVG, EPS or AI format?  
* [x] Does your logo clearly state the name of the product/project and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [x] If your product/project is open source, did you include the `repo_url`?
* [x] Did you copy and paste the [installation and configuration instructions](https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions) into the README.md file in addition to linking to them?

### CODE REVIEW

**Comment by brtknr** [comment]
Is this a bug?

**Comment by Riaankl** [comment]
> Is this a bug?

@brtknr , yes is seem to be a bug.
We are trying to sort it out as soon as possible.

**Comment by brtknr** [comment]
Blocked by kubernetes/kubernetes#98940

**Comment by Riaankl** [comment]
Hi @brtknr,
Yes, @heyste is part of our team, He identified the bug and created the PR to fix it.
SIG Network needs to approve the PR. Then things can move along again.

**Comment by brtknr** [comment]
Superseded by https://github.com/cncf/k8s-conformance/pull/1320

**Pull request closed without merging**
