### PR TITLE
Add conformance results for v1.14/kubeadm

### PR DESCRIPTION
**Pull request by stealthybox**
This patch improves the README from previous versions to bootstrap a multi-node cluster.
Blocking for results and extracting them to the host is now atomated.

vendor: Weaveworks
name: kubeadm
version: v1.14.2
website_url: https://kubernetes.io/docs/setup/independent/create-cluster-kubeadm/
repo_url: https://github.com/kubernetes/kubeadm/
documentation_url: https://kubernetes.io/docs/setup/independent/create-cluster-kubeadm/
product_logo_url: https://raw.githubusercontent.com/kubernetes/kubernetes/master/logo/logo.svg
type: installer
description: kubeadm helps you bootstrap a minimum viable Kubernetes cluster that conforms to best practices.

### CODE REVIEW

**Comment by dankohn** [comment]
Repo needs to be a GitHub repo (not a directory). https://github.com/kubernetes/kubeadm works.

I suspect you want to keep the logo as it is here: https://landscape.cncf.io/selected=weaveworks-kubeadm

**Comment by luxas** [comment]
> I suspect you want to keep the logo as it is here: https://landscape.cncf.io/selected=weaveworks-kubeadm

We're filing this under Weaveworks as one of the companies backing kubeadm, but this is still the OSS code of the core k8s project. We've just listed the k8s logo for all versions so far too, e.g. https://github.com/cncf/k8s-conformance/blob/master/v1.13/kubeadm/PRODUCT.yaml

**Comment by dankohn** [comment]
Would you like our designer to work with you to create a kubeadm logo? The 4 other certified installers that are part of K8s all have one: https://landscape.cncf.io/category=certified-kubernetes-installer&format=card-mode&grouping=organization&organization=cloud-native-computing-foundation-cncf

Or, we can just write `kubeadm` under the K8s logo like we do with https://landscape.cncf.io/format=card-mode&organization=netflix,square,uber

**Comment by stealthybox** [comment]
> Repo needs to be a GitHub repo (not a directory). https://github.com/kubernetes/kubeadm works.

fixed this

**Comment by dankohn** [comment]
We'll approve shortly but please reach out to me on Slack if you'd like help on a kubeadm logo.

**Comment by luxas** [comment]
> We'll approve shortly but please reach out to me on Slack if you'd like help on a kubeadm logo.

yes, will do!

**Comment by luxas** [comment]
This one should be ready to go

**Comment by taylorwaggoner** [comment]
You are now Certified Kubernetes

**Pull request merged**
