### PR TITLE
Conformance results for v1.16/innovo-imke

### PR DESCRIPTION
**Pull request by getafixx**
### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [ ] If this is a new entry, have you submitted a signed [participation form](https://github.com/cncf/k8s-conformance/tree/master/participation-form)?
* [x] Did you include the product/project logo in SVG, EPS or AI format?  
* [x] Does your logo clearly state the name of the product/project and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [ ] If your product/project is open source, did you include the `repo_url`?
* [x] Did you copy and paste the [installation and configuration instructions](https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions) into the README.md file in addition to linking to them?

### CODE REVIEW

**Comment by taylorwaggoner** [comment]
@getafixx thanks for submitting.  We're in the process of asking everyone to make sure that their README files provide clear step by step instructions for how to recreate your conformance results. Are there any additional installation or configuration instructions that you could add to your README that would walk a user through the process?  Thanks!

**Comment by getafixx** [comment]
@taylorwaggone I will check again that they are correct.

**Comment by getafixx** [comment]
@taylorwaggone updated the readme instructions. I hope this helps.

**Comment by taylorwaggoner** [comment]
@getafixx thanks for updating!  I noticed you said "Your email should be sent from the cncf.io domain."  These instructions would be for a customer to use to validate your conformance results, not CNCF, so they wouldn't have access to email from the cncf.io domain.

**Comment by getafixx** [comment]
@taylorwaggoner OK this was just because I was trying not to give credentials. 

Normally users have to go through sales to get an account. How do I write this part to allow you or CNCF users get an account?

**Comment by taylorwaggoner** [comment]
@getafixx you should treat this as if your customer wanted to recreate your conformance results.  So including the normal process to get an account is fine.

**Comment by taylorwaggoner** [comment]
Checking in!  Let me know if you have any questions

**Comment by getafixx** [comment]
@taylorwaggoner sorry been on holiday and I am still on holiday. I will see if I have time to change the details or we can just ignore that comment. I am back in a week.

**Comment by getafixx** [comment]
@taylorwaggoner specific email domain instructions removed. - please try again.

**Comment by taylorwaggoner** [comment]
You are now Certified Kubernetes
https://landscape.cncf.io/format=card-mode&selected=i-nnovo-managed-kubernetes-engine

**Comment by getafixx** [comment]
@taylorwaggoner Thank you very much!

**Pull request merged**
