### PR TITLE
Conformance results for v1.18/tenxcloud

### PR DESCRIPTION
**Pull request by nkwangleiGIT**
### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [x] If this is a new entry, have you submitted a signed [participation form](https://github.com/cncf/k8s-conformance/tree/master/participation-form)?
We already submitted the test results for previous K8S versions（v1.10 & v1.12）, how can I check if we should submit the form again?

* [x] Did you include the product/project logo in SVG, EPS or AI format?  
Yes

* [x] Does your logo clearly state the name of the product/project and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
Yes

* [x] If your product/project is open source, did you include the `repo_url`?
It's not open source.

* [x] Did you copy and paste the [installation and configuration instructions](https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions) into the README.md file in addition to linking to them?
I added the steps and also provide the link to the README.md file.

### CODE REVIEW

**Comment by taylorwaggoner** [comment]
@nkwangleiGIT thanks for submitting.  A few things before we can move forward.

- Please submit a [signed participation agreement](https://github.com/cncf/k8s-conformance/tree/master/participation-form)
- Add a product description to your PRODUCT file [per these guidelines](https://github.com/cncf/k8s-conformance/blob/master/instructions.md#productyaml)
- please paste all installation and configuration instructions, including how to provision a cluster, into the README. We're trying to provide step by step guidance so that your customers can later validate your conformance if they wish to.  Please review [this FAQ](https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions) for more info.

Thanks!

**Comment by taylorwaggoner** [comment]
@nkwangleiGIT checking in on this, thanks!

**Comment by nkwangleiGIT** [comment]
@taylorwaggoner 
1) I signed the participation agreement using docusign, here is the link:
https://na3.docusign.net/Signing/?insession=1&ti=20f209782d9b492ea2628015137036e9
2) Added the description.
3) I think I already added the detail steps about how to provision a K8s cluster, including the master and the worker nodes.
Thanks!

**Comment by taylorwaggoner** [comment]
Thanks for the form and for adding the description!  For the README, are there any other installation steps you could provide that would help someone replicate your results if they wanted to?  Thanks!

**Comment by nkwangleiGIT** [comment]
@taylorwaggoner  I just added more details to the README file, please check again, thanks!

**Comment by taylorwaggoner** [comment]
You are now Certified Kubernetes
https://landscape.cncf.io/format=card-mode&organization=tenx-cloud&selected=tenx-cloud-container-enterprise

**Pull request merged**
