### PR TITLE
K8s tew/v1.17

### PR DESCRIPTION
**Pull request by darxkies**
### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [X] If this is a new entry, have you submitted a signed [participation form](https://github.com/cncf/k8s-conformance/tree/master/participation-form)?
* [X] Did you include the product/project logo in SVG, EPS or AI format?  
* [X] Does your logo clearly state the name of the product/project and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [X] If your product/project is open source, did you include the `repo_url`?
* [X] Did you copy and paste the [installation and configuration instructions](https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions) into the README.md file in addition to linking to them?

### CODE REVIEW

**Comment by taylorwaggoner** [comment]
@darxkies thanks for submitting! #865 looks good, but this PR is for 1.17 but is showing that it's going to the 1.16 directory.  Also, the e2e log is showing 1.16 instead of 1.17:

> Feb 23 17:36:37.724: INFO: e2e test version: v1.16.7
Feb 23 17:36:37.725: INFO: kube-apiserver version: v1.16.7

Could you please take a look? Thanks!

**Comment by darxkies** [comment]
I have added the missing files. Please let me know if that works for you and sorry for the inconvenience.

**Comment by taylorwaggoner** [comment]
You are now Certified Kubernetes

**Comment by darxkies** [comment]
Thank you.

**Pull request merged**
