### PR TITLE
Conformance results for v1.7/Tectonic

### PR DESCRIPTION
**Pull request by cpanato**
vendor: CoreOS
name: Tectonic
version: 1.7.5-tectonic.1
website_url: https://coreos.com/tectonic/
documentation_url: https://coreos.com/tectonic/docs/latest/
product_logo_url: https://coreos.com/assets/images/brand/tectonic-bycoreos-color.png

### CODE REVIEW

**Comment by kbarnard10** [comment]
+1

**Comment by sudhaponnaganti** [comment]
Thank you @kbarnard10 - I assume this is the final approval for certification besides submitting participation form.

**Comment by dankohn** [comment]
Correct, you've done everything necessary and we'll be accepting all the pull requests at the same time, the morning of the announcement, at which point your certification will be effective.

**Comment by sudhaponnaganti** [comment]
Thanks @dankohn for the clarification

**Comment by dghubble** [comment]
@sudhaponnaganti can you call this Tectonic please?

**Comment by robszumski** [comment]
@cpanato update to the logo url: https://coreos.com/assets/images/brand/tectonic-bycoreos-color.png

**Pull request merged**
