### PR TITLE
Conformance results for v1.14/kops

### PR DESCRIPTION
**Pull request by mikesplain**
Conformance results for v1.14/kops.

Fixes https://github.com/kubernetes/kops/issues/7523

### CODE REVIEW

**Comment by dankohn** [comment]
We're pretty sure, based on our [definition](https://github.com/cncf/k8s-conformance/blob/master/faq.md#what-is-a-distribution-hosted-platform-and-an-installer), that kops is an installer rather than a distribution. We've been classifying you that way on the landscape: https://landscape.cncf.io/category=certified-kubernetes-installer&format=card-mode&grouping=category&organization=cloud-native-computing-foundation-cncf

Are you OK if we edit these to say installer?

**Comment by mikesplain** [comment]
Thanks @dankohn, let me talk to the team and confirm our view on that.  Our office hours are friday so it may take until then for us to confirm. Thanks!

**Comment by justinsb** [comment]
@dankohn can you clarify the intent of the distinction?

kops is a ready-to-go kubernetes - it includes cloudproviders, CNI controllers, additional addons etc.  We commit to keeping these working for our end users even as things change underneath us in the upstream kubernetes project.  In other words, we are more than the "core" kubernetes, and we offer greater compatibility guarantees.  So if the intent is to say "a distribution is ready to use, an installer is a building block", then kops is a distribution.

However, kops sticks to the open source and kubernetes community ethos.  When we find bugs, we prefer to fix them upstream rather than work around them.  When we need a new piece of functionality, we go through the OSS channels (e.g. subprojects of sig-cluster-lifecycle).  kops is itself a kubernetes community subproject.  So if the intent is to say "a distribution may not be as close to the open source community", then that's not kops!

Maybe we should just get our logo in both categories :-)

**Comment by dankohn** [comment]
Thanks for the note. The intent is for you to be aware of the differences between installer and distribution and pick the one that best fits what you do. Do you actually keep a separate copy of Kubernetes in your repo that diverges from upstream (until patches are accepted)?

**Comment by justinsb** [comment]
We are a kubernetes project, so we would want to get patches into k/k first.  So no, we don't and would not (in normal circumstances) carry a patch to k/k in kops.

This intent - that installers run the pure upstream binaries and distributions have patched the upstream binaries - was not clear to me as a consumer of kubernetes.  Should we rename distributions to "forked distributions", and installers to "pure upstream", so this distinction is clearer?

**Comment by dankohn** [comment]
I just modified the distribution definition to remove mention of additional software and instead focus on whether the implementation is carrying patches or not. See https://github.com/cncf/k8s-conformance/commit/340f85da34efa2320c58c4b4206b58ecc04dfa1c

I think that better clarifies the distinction we were aiming for.

Based on those updated definitions, is kops an installer?

**Comment by justinsb** [comment]
Thanks @dankohn that is indeed much clearer to me now!

Based on that, kops is an installation tool, and proud to be so :-)

Would you like @mikesplain and I to tweak this conformance submission?

**Comment by dankohn** [comment]
Sure, that would be great if you could update the PRs. Thanks for your help showing where our definitions were confusing.

**Comment by mikesplain** [comment]
Thanks for talking that through @dankohn and @justinsb! PR updates incoming.

**Comment by taylorwaggoner** [comment]
You are now Certified Kubernetes

**Pull request merged**
