### PR TITLE
Update OpenShift conformance results for the 1.8 release

### PR DESCRIPTION
**Pull request by smarterclayton**
This is a pre-release version of OpenShift 3.8 based on Kubernetes 1.8.1+.

Also update with the correct product numbers for the matching
conformance report.

### CODE REVIEW

**Comment by kbarnard10** [comment]
@smarterclayton - Looks like your Client Version should be 1.8 or higher.

**Comment by smarterclayton** [comment]
Yeah, it must not have picked up the correct tags.  Will look.

**Comment by smarterclayton** [comment]
Updated against Kube 1.8.5

**Comment by kbarnard10** [comment]
Looks good now. You are now Certified Kubernetes

**Pull request merged**
