### PR TITLE
gardener supporting new k8s release

### PR DESCRIPTION
**Pull request by OlegLoewen**
- gardener supporting new k8s release v1.16
- regarding #759 upload retested v1.15 results
- add alicloud test results for v1.14 - v1.16

### CODE REVIEW

**Comment by taylorwaggoner** [comment]
@OlegLoewen thank you!  The results look great, but before I can merge, could you please copy and paste the instructions to reproduce the results into the README, rather than linking to documentation?  https://github.com/cncf/k8s-conformance/blob/master/instructions.md#contents-of-the-pr

Thanks!

**Comment by OlegLoewen** [comment]
@taylorwaggoner done

**Comment by OlegLoewen** [comment]
@taylorwaggoner let me know if anything missing. Also regarding #790

**Comment by OlegLoewen** [comment]
> @taylorwaggoner let me know if anything missing. Also regarding #790

@erikwilson, since Taylor is in absence for a longer time, maybe you can take a look at the PRs and merge them?

**Comment by taylorwaggoner** [comment]
@OlegLoewen, I apologize for the big delay here. We are tightening the requirements for the README files and have added [an explanation to the Conformance FAQ](https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions).

Could you please make sure that all of the README's in this PR have the instructions pasted into the file, in addition to providing the URL?

Thank you!  Again, sorry for the delay in my response!

**Comment by OlegLoewen** [comment]
Hello @taylorwaggoner, no issue. Somehow I missed to add the description to some files, sorry. Can you please check again?
However, I kept the following part, because the description is really long, I hope this is fine:

> ## Install Gardener on your Kubernetes Landscape
> Follow the instructions on https://github.com/gardener/garden-setup

**Comment by taylorwaggoner** [comment]
@OlegLoewen, thank you for updating.  Unfortunately we do need the installation instructions per the guidelines I linked before.  Could you please add a simplified version of the instructions into each README for this PR and #790?  Thank you very much!

**Comment by OlegLoewen** [comment]
@taylorwaggoner okay, I added the additional description. Please review again.

**Comment by taylorwaggoner** [comment]
Thank you!  You are now Certified Kubernetes

**Pull request merged**
