### PR TITLE
New conformance results for Red Hat OpenShift on IBM Cloud

### PR DESCRIPTION
**Pull request by rtheis**
Red Hat OpenShift on IBM Cloud conformance results for
version 4.4 which is based on Kubernetes version 1.17.

### CODE REVIEW

**Comment by taylorwaggoner** [comment]
@rtheis thanks for submitting.  For the README, could you paste in the UI cluster creation instructions that you referenced here:

> ### UI 
> Go to [IBM Cloud catalog](https://cloud.ibm.com/catalog?category=containers) and select `Red Hat OpenShift on IBM Cloud` and follow the instructions to create a cluster.

Thanks!

**Comment by rtheis** [comment]
Will do

**Comment by rtheis** [comment]
Thanks @taylorwaggoner.  I've updated the README accordingly.

**Comment by taylorwaggoner** [comment]
Thanks! You are now Certified Kubernetes

**Pull request merged**
