### PR TITLE
Conformance results for v1.16/ace

### PR DESCRIPTION
**Pull request by tossmilestone**

### CODE REVIEW

**Comment by tossmilestone** [comment]
@taylorwaggoner PTAL

**Comment by taylorwaggoner** [comment]
@tossmilestone , thank you for submitting.  Results look great, but there's one item that needs edited before I can merge.  Please copy and paste the instructions to create and deploy a cluster directly into the README, per [these guidelines](https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions).

Also, you can go ahead and delete the version.txt file, as it's no longer required.

Thanks!

**Comment by tossmilestone** [comment]
@taylorwaggoner updated, plz review it again.

**Comment by taylorwaggoner** [comment]
You are now Certified Kubernetes
https://landscape.cncf.io/format=card-mode&organization=alauda&selected=alauda-cloud-enterprise-ace

**Pull request merged**
