### PR TITLE
Conformance test results for v1.9/AWS (CoreOS Tectonic)

### PR DESCRIPTION
**Pull request by coverprice**
vendor: CoreOS
name: Tectonic
version: 1.9.6-tectonic.1
website_url: https://coreos.com/tectonic/
documentation_url: https://coreos.com/tectonic/docs/latest/
product_logo_url: https://coreos.com/assets/images/brand/tectonic-bycoreos-color.png

Submitted by James Russell (jrussell@redhat.com)

### CODE REVIEW

**Comment by taylorwaggoner** [comment]
Hi @coverprice - Please fix the version.txt file so that the Client Version reads: version.Info{Major:"1", Minor:"9".  (Currently it shows "Major:"1", Minor:"10"") . Everything else looks good!

**Comment by coverprice** [comment]
@taylorwaggoner It's 1.10 because that's the version of `kubectl` I used to launch the tests; I don't think it would have an impact on test results. I didn't see anywhere in the instructions that the kubectl version should match the server version, but I'm happy to re-run the tests if that's the case.

**Comment by dankohn** [comment]
Taylor is following the review instructions set here:
https://github.com/cncf/k8s-conformance/blob/master/reviewing.md#how-to-review-conformance-results

You could propose a change to those if you don't think they make sense, and
then the working group would review your PR.

--
Dan Kohn <dan@linuxfoundation.org>
Executive Director, Cloud Native Computing Foundation https://www.cncf.io
+1-415-233-1000 https://www.dankohn.com

**Comment by coverprice** [comment]
Thank you for the reference (and the quick turnaround time). I think the review instructions look correct, and also that I'm complying with them. From the instructions (emphasis mine):
> 5. Look at version.txt. Verify that the major.minor component of the **client** version (which represents the Kubernetes version of the e2e tests that were run) **is equal to or greater than** the Conformance Version.
The client in this case is 1.10, which is greater than the conformance version (1.9.6). So I think it complies, no?

**Comment by taylorwaggoner** [comment]
@coverprice you are absolutely right, so sorry about that!  You are now Certified Kubernetes

**Comment by coverprice** [comment]
@taylorwaggoner Thank you, and thanks especially for your fast turnaround time! It's much appreciated.

**Pull request merged**
