### PR TITLE
Conformance Results for v1.23/gardener

### PR DESCRIPTION
**Pull request by dguendisch**
### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [x] If this is a new entry, have you submitted a signed [participation form](https://github.com/cncf/k8s-conformance/tree/master/participation-form)?
* [x] Did you include the product/project logo in SVG, EPS or AI format?  
* [x] Does your logo clearly state the name of the product/project and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [x] If your product/project is open source, did you include the `repo_url`?
* [x] Did you copy and paste the [installation and configuration instructions](https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions) into the README.md file in addition to linking to them?

cc @hendrikKahl

### CODE REVIEW

**Comment by Riaankl** [comment]
@dguendisch It seem there is 5 products in this PR.
Please submit one product per PR as there are checked and approved inducidually.

**Comment by dguendisch** [comment]
@Riaankl we were asked in the past to separate our 2 products (sap-cp and Gardener) into distinct PRs, see https://github.com/cncf/k8s-conformance/pull/1291#issuecomment-765743659
We did so with future PRs. What you see in this PR is however one product: Gardener simply supports to create K8s clusters on different cloud providers, it's not a different "product".
So, is it really necessary to submit our support of different cloud providers (we do that from inside one "product") in 5 different PRs and considering we have https://github.com/cncf/k8s-conformance/pull/1840 as well so it sums up to 10 PRs when we support a new K8s version?

**Comment by Riaankl** [comment]
The CNCF-CI bot is checking the four files releate to a single Sonobouy output and confirm that all content is as expected.
If multiple files of the same type are included the Bot can not do these checks to match up which belong together.
Sorry for the inconvenience, but yes please break it into separate PRs.
https://github.com/cncf/k8s-conformance/blob/master/instructions.md#contents-of-the-pr
/cc @taylorwaggoner

**Comment by dguendisch** [comment]
@Riaankl one final question: in the past the bot was obviously able to check our PRs, see https://github.com/cncf/k8s-conformance/pull/1677#issuecomment-953712255
Has this changed in the meantime and the bot can now only check one "product" whereas it could check multiple ones in the past?

**Comment by Riaankl** [comment]
The bot did not previously check if there is more than one product in the PR, only if the there is 4 files and all requiements are met for the 4 matching files. So the requiements are still the same, just better managed. Hope that clarify.

**Comment by taylorwaggoner** [comment]
@dguendisch we really appreciate your help with this new process of submitting one product (or cloud provider) per Pull Request. Please let us know if you have any other questions! Thanks!

**Comment by hendrikKahl** [comment]
I believe this PR can be closed in favor of this bunch of PRs: https://github.com/cncf/k8s-conformance/pulls?q=is%3Apr+label%3Arelease-v1.23+gardener

**Comment by dguendisch** [comment]
Closing as these are followed up in dedicated PRs.

**Pull request closed without merging**
