### PR TITLE
Add Conformance results for v1.16/clearlinux

### PR DESCRIPTION
**Pull request by CraigSterrett**
Initial commit of conformance results for Intel Clear Linux

Signed-off-by: Craig Sterrett <craig.Sterrett@intel.com>

### CODE REVIEW

**Comment by taylorwaggoner** [comment]
@CraigSterrett, thanks for submitting! Do you have this logo in EPS or SVG format?   We need to convert to SVG for the Cloud Native landscape and the AI image you linked to doesn't convert correctly.  I can have our designer take a look after the holidays, but I wanted to check with you this week.  Thanks!

**Comment by CraigSterrett** [comment]
@taylorwaggoner enjoy the holidays, everyone that I could ask are out until Jan 6th. I'll provide an update after that.

**Comment by taylorwaggoner** [comment]
@CraigSterrett, my designer was able to recreate your logo, so we're good there!  Before I can move forward, could you please update your repo_url to point to the primary GitHub repo containing the source data?  Thanks!

**Comment by CraigSterrett** [comment]
Hi @taylorwaggoner I could use some help to answer your last question regarding the primary github repo. The address I put in points to the collection of repos that make up the Clear Linux distribution. What we are certifying is that if you install the cloud-native-basic bundle on top of Clear Linux you then have a conformant Kubernetes environment. The repo for the [cloud-native-basic bundle ](https://github.com/clearlinux/clr-bundles/blob/master/bundles/cloud-native-basic )is not very helpful to the end user as it just defines the packages that Clear installs when you install that bundle. Because of the complexity of the Clear Linux distribution I am not quite sure what to put in as the primary url. Maybe point to the [contributing readme](https://github.com/clearlinux/distribution/blob/master/contributing.md)?

**Comment by dankohn** [comment]
We'll just use https://github.com/clearlinux/clr-bundles thanks.

**Comment by CraigSterrett** [comment]
@dankohn Great, thanks. Do you want me to push a new product.yaml with that change?

**Comment by dankohn** [comment]
Please do.

**Comment by CraigSterrett** [comment]
@dankohn Let me know if you need any other updates.

**Comment by taylorwaggoner** [comment]
You are now Certified Kubernetes
https://landscape.cncf.io/format=card-mode&organization=intel&selected=clear-linux-project

**Pull request merged**
