### PR TITLE
Conformance Results for v1.22/JDOS

### PR DESCRIPTION
**Pull request by hitorig**
### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [ ] If this is a new entry, have you submitted a signed [participation form](https://github.com/cncf/k8s-conformance/tree/master/participation-form)?
* [x] Did you include the product/project logo in SVG, EPS or AI format?  
* [x] Does your logo clearly state the name of the product/project and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [ ] If your product/project is open source, did you include the `repo_url`?
* [x] Did you copy and paste the [installation and configuration instructions](https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions) into the README.md file in addition to linking to them?

### CODE REVIEW

**Comment by taylorwaggoner** [comment]
@hitorig please include a link to a pure SVG file for your logo. thanks!

**Comment by taylorwaggoner** [comment]
@hitorig thanks!  JD Cloud holds the CNCF membership now, so this would fall under that membership, correct?  We would categorize this conformance listing under their company details: https://landscape.cncf.io/card-mode?organization=jd-cloud. We can use the logo you provided though. Does that all work?

**Comment by hitorig** [comment]
Yes.
Thanks!


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cncf/k8s-conformance"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月28日(星期四) 凌晨5:11
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [cncf/k8s-conformance] Conformance Results for v1.22/JDOS (PR #1915)





 
@hitorig thanks!  JD Cloud holds the CNCF membership now, so this would fall under that membership, correct?  We would categorize this conformance listing under their company details: https://landscape.cncf.io/card-mode?organization=jd-cloud. We can use the logo you provided though. Does that all work?

**Comment by taylorwaggoner** [comment]
You are now Certified Kubernetes

**Comment by hitorig** [comment]
Hello, our project is not open source. So there is no repo_url, now since N/A is illegal, what should be filled in?
And the url in the product_url field is indeed an svg, why is it illegal?

I am waiting for your response
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; yours sincerely




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cncf/k8s-conformance"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月22日(星期五) 下午5:57
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [cncf/k8s-conformance] Conformance Results for v1.22/JDOS (PR #1915)





 
12 of 14 requirements have passed. Please review the following:
  
[FAIL] it appears that URL(s) in the PRODUCT.yaml aren't correctly formatted URLs  
URL for field 'repo_url' in PRODUCT.yaml is not a valid URL, parse "N/A": invalid URI for request
  
 
[FAIL] it appears that URL(s) in the PRODUCT.yaml don't resolve to the correct data type  
URL field 'product_logo_url' in PRODUCT.yaml resolving content type 'text/html; charset=utf-8' must be (image/svg, or application/postscript)
  
  
for a full list of requirements, please refer to these sections of the docs: content of the PR, and requirements.

**Pull request merged**
