### PR TITLE
Documentation link update

### PR DESCRIPTION
**Pull request by legacyrj**
### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [ ] If this is a new entry, have you submitted a signed [participation form](https://github.com/cncf/k8s-conformance/tree/master/participation-form)?
* [ ] Did you include the product/project logo in SVG, EPS or AI format?  
* [ ] Does your logo clearly state the name of the product/project and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [ ] If your product/project is open source, did you include the `repo_url`?
* [ ] Did you copy and paste the [installation and configuration instructions](https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions) into the README.md file in addition to linking to them?

For a full list of requirements, please refer to these sections of the docs: [_Contents of the PR_](https://github.com/cncf/k8s-conformance/blob/master/instructions.md#contents-of-the-pr), and [_Requirements_](https://github.com/cncf/k8s-conformance/blob/master/instructions.md#requirements).

### CODE REVIEW

**Comment by oaktowner** [comment]
Conformance test already passed -- we are only changing some of the metadata (URLs, logos, etc) in the wake of our acquisition.

**Review by oaktowner — APPROVED** [review]
Branding/logo/URL changes only. Please approve!

**Comment by taylorwaggoner** [comment]
@legacyrj @oaktowner I mentioned this in email to some of your team members a couple days ago, but we need a new signed [participation form](https://github.com/cncf/k8s-conformance/tree/master/participation-form) with the new product name and other details, per our guidelines [here](https://github.com/cncf/k8s-conformance/blob/master/faq.md#do-i-need-to-re-submit-results-if-we-rebrand-our-product). Thanks!

**Comment by legacyrj** [comment]
Hello @taylorwaggoner, We have emailed the participation on Oct 3rd. Please verify the form and confirm status on PR.

**Review by taylorwaggoner — APPROVED** [review]

**Pull request merged**
