### PR TITLE
Conformance results for v1.21/kind

### PR DESCRIPTION
**Pull request by amwat**
### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [x] If this is a new entry, have you submitted a signed [participation form](https://github.com/cncf/k8s-conformance/tree/master/participation-form)?
* [x] Did you include the product/project logo in SVG, EPS or AI format?  
* [x] Does your logo clearly state the name of the product/project and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [x] If your product/project is open source, did you include the `repo_url`?
* [x] Did you copy and paste the [installation and configuration instructions](https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions) into the README.md file in addition to linking to them?

### CODE REVIEW

**Comment by BenTheElder** [comment]
> This request is not yet verifiable, please confirm that your e2e logs reference the release you are submitting for

This comment is a big vague @cncf-ci 🙃 

What is expected here? Early in [the submitted log](https://raw.githubusercontent.com/cncf/k8s-conformance/4d6819000b29e5233a5663b090867845d93e8f28/v1.21/kind/e2e.log) I see:
> May 24 23:50:41.422: INFO: e2e test version: v1.21.1
> May 24 23:50:41.423: INFO: kube-apiserver version: v1.21.1

**Comment by amye** [comment]
@hh to review

**Comment by bernokl** [comment]
@amye please update the subject of the pr to reflect the version you ar trying to submit for:
It would look something like 
`Conformance results for 1.21/kind`
Ref:  https://github.com/cncf/k8s-conformance/blob/master/instructions.md#uploading

**Comment by amye** [comment]
@bernokl: Not actually my PR, this is @amwat

**Comment by BenTheElder** [comment]
Seems like the directory being touched + the logs should be validated over the PR title ..?

Thanks!

**Comment by hh** [comment]
I think the logic to verify that the submission (we only allow one per PR) matches the title is part of the process.

From https://github.com/cncf/k8s-conformance/blob/master/instructions.md#uploading :

### Uploading

Prepare a PR to https://github.com/cncf/k8s-conformance. Here are directions to prepare a pull request from a fork. In the descriptions below, X.Y refers to the kubernetes major and minor version, and $dir is a short subdirectory name to hold the results for your product. Examples would be gke or openshift.

Description: `Conformance results for vX.Y/$dir`

**Comment by ErinThacker** [comment]
You are now certified Kubernetes.

**Pull request merged**
