### PR TITLE
Conformance results for v1.17/netease-dedicated

### PR DESCRIPTION
**Pull request by chaolou**
### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [ ] If this is a new entry, have you submitted a signed [participation form](https://github.com/cncf/k8s-conformance/tree/master/participation-form)?
* [x] Did you include the product/project logo in SVG, EPS or AI format?  
* [x] Does your logo clearly state the name of the product/project and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [ ] If your product/project is open source, did you include the `repo_url`?
* [x] Did you copy and paste the [installation and configuration instructions](https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions) into the README.md file in addition to linking to them?

### CODE REVIEW

**Comment by taylorwaggoner** [comment]
@chaolou thank you for submitting.  Please paste in the instructions from the operation guide you mentioned below into your README file, per [these guidelines](https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions).

>  (1) Create three virtual machines for k8s master node and one virtual machine for k8s worker node on netease cloud platform according to [the operation  guide](https://www.163yun.com/help/documents/71794571663822848), each has at least 2 CPUs and 2 GiB RAM.

Thanks!

**Comment by taylorwaggoner** [comment]
@chaolou checking in on this, thanks!

**Comment by taylorwaggoner** [comment]
@chaolou please let us know if you have any questions!

**Comment by chaolou** [comment]
I added the operation guide figures in README file, I think it's clear enough now.

**Comment by taylorwaggoner** [comment]
You are now Certified Kubernetes

**Pull request merged**
