### PR TITLE
Conformance results for v1.16/KubeOperator

### PR DESCRIPTION
**Pull request by wanghe-fit2cloud**
Conformance results for v1.16/KubeOperator

### CODE REVIEW

**Comment by taylorwaggoner** [comment]
@wanghe-fit2cloud thank you for submitting.  Per [these guidelines](https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions), could you please copy/paste in all instructions and requirements in addition to linking to the URLs? Thanks!

**Comment by wanghe-fit2cloud** [comment]
Ok. Thank you very much for your reply!

**Comment by wanghe-fit2cloud** [comment]
@taylorwaggoner thanks. I have updated the README for the detailed setup of installations.

**Comment by taylorwaggoner** [comment]
You are now Certified Kubernetes

**Pull request merged**
