### PR TITLE
Conformance results for v1.17/Bizmicro Portal

### PR DESCRIPTION
**Pull request by ssebayam**
### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [x] If this is a new entry, have you submitted a signed [participation form](https://github.com/cncf/k8s-conformance/tree/master/participation-form)?
* [ ] Did you include the product/project logo in SVG, EPS or AI format?  
* [ ] Does your logo clearly state the name of the product/project and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [ ] If your product/project is open source, did you include the `repo_url`?
* [x] Did you copy and paste the [installation and configuration instructions](https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions) into the README.md file in addition to linking to them?

### CODE REVIEW

**Comment by ssebayam** [comment]
PRODUCT.yaml has been updated.

**Comment by ssebayam** [comment]
I've added product_logo_url to be published on cncf.io.

**Comment by taylorwaggoner** [comment]
@ssebayam please provide the logo in SVG, EPS, or AI format if you have it.  If not, we can use your company logo from the landscape.  Thanks!

**Comment by ssebayam** [comment]
@taylorwaggoner Will update logo soon. Thanks!

**Comment by ssebayam** [comment]
@taylorwaggoner PRODUCT.yaml has been updated to adopt svg file format. Thanks!

**Comment by taylorwaggoner** [comment]
You are now Certified Kubernetes
https://landscape.cncf.io/format=card-mode&selected=bizmicro

**Pull request merged**
