### PR TITLE
Conformance results for v1.21/alvistack-ansible-collection-kubernetes

### PR DESCRIPTION
**Pull request by hswong3i**
### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [x] If this is a new entry, have you submitted a signed [participation form](https://github.com/cncf/k8s-conformance/tree/master/participation-form)?
* [x] Did you include the product/project logo in SVG, EPS or AI format?  
* [x] Does your logo clearly state the name of the product/project and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [x] If your product/project is open source, did you include the `repo_url`?
* [x] Did you copy and paste the [installation and configuration instructions](https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions) into the README.md file in addition to linking to them?

Fixes #1614

### CODE REVIEW

**Comment by hswong3i** [comment]
@taylorwaggoner could we revoke the CNCF membership subscription as per https://github.com/cncf/k8s-conformance/pull/1620#issuecomment-939106096?

**Comment by taylorwaggoner** [comment]
@hswong3i what do you mean by revoke the membership subscription?

**Comment by hswong3i** [comment]
> @hswong3i what do you mean by revoke the membership subscription?

Recently my partners and I try to contact memberships@cncf.io for paying the membership fee but no reply. We guess that because our conformance test results already expired for a few months.

Therefore we submit our conformance test results for 1.21/1.22/1.23 with latest update, and looking for some assistance for cncf membership subscription.

**Comment by taylorwaggoner** [comment]
@hswong3i is your company name Alvistack? I don't show any record of you having a CNCF membership or having a conformance product with us. I see you tried to submit conformance results [a few months ago](https://github.com/cncf/k8s-conformance/pull/1620) , but I don't think you ended up becoming a member, so we closed them out. Would you like to join CNCF and continue with the conformance results? I don't see any messages from you to memberships@cncf.io lately, but please feel free to reach out to our China team at china@cncf.io. They'll be able to help you become a CNCF member. @donaldliu

**Comment by kpyan8s** [comment]
Hi @taylorwaggoner, it is Francis from PantaRei Design Limited, partner of @hswong3i.

Last time we register our account in https://www.cncf.io/lfmembership and got an email reply from salesops@linuxfoundation.org on 21 Oct, 2021. However, we did not receive any follow up from their side.

Our account email is support@pantarei-design.com and Organization Name is PantaRei Design.

This time, I will contact china@cncf.io first with this pull request information. I will follow up the procedure after communication with team.

**Comment by taylorwaggoner** [comment]
@kpyan8s  thanks! We'll keep these PRs open until you have become a member.

**Comment by kpyan8s** [comment]
@taylorwaggoner thanks, we got reply from Keith Chan, CNCF China Director and we will keep contact with him.

**Comment by taylorwaggoner** [comment]
Great thanks @kpyan8s!  Please note that 1.21 is going to expire next week and we will only be accepting submissions for 1.22 and higher.  You'll need to become a member before May 3 in order to certify for 1.21. Thanks

**Comment by hswong3i** [comment]
In between refresh conformance test result as below:
* Upgrade from Ubuntu 20.04 to 22.04
* CNI replace from Weave to Cilium
* Remove csi-cephfs (as not a must for conformance test)
* Simplify and double check README.md procedures

**Comment by kpyan8s** [comment]
Hi @taylorwaggoner, thank you for your update, we check with CNCF China team about our membership application, it will take around 2 to 3 weeks.

We will provide submission for 1.22 or higher soon.

@hswong3i FYI

**Comment by hswong3i** [comment]
> Great thanks @kpyan8s! Please note that 1.21 is going to expire next week and we will only be accepting submissions for 1.22 and higher. You'll need to become a member before May 3 in order to certify for 1.21. Thanks

@taylorwaggoner thank you for your kindly reminder, and our latest version for v1.24 is now submitted to #1959.

**Pull request closed without merging**
