### PR TITLE
Conformance results for v1.19/asuscloudinfra

### PR DESCRIPTION
**Pull request by IrisChanTW**
### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [x] If this is a new entry, have you submitted a signed [participation form](https://github.com/cncf/k8s-conformance/tree/master/participation-form)?
* [x] Did you include the product/project logo in SVG, EPS or AI format?  
* [x] Does your logo clearly state the name of the product/project and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [x] If your product/project is open source, did you include the `repo_url`?
* [x] Did you copy and paste the [installation and configuration instructions](https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions) into the README.md file in addition to linking to them?

### CODE REVIEW

**Comment by taylorwaggoner** [comment]
@IrisChanTW the results for 1.19 look great.  Can you please delete the README file for 1.16 from this PR?  Then I can merge.  Thanks!

**Comment by IrisChanTW** [comment]
Dear Taylor,

We have fixed the PR, thank you!

Best Regards,
Iris Chan 詹子陞

ASUS Cloud Corporation｜www.asuscloud.com
TEL:+886-2-28987477 Ext.86002
Mobile:+886-926335108



Taylor Waggoner <notifications@github.com> 於 2020年9月17日 週四 上午4:01寫道：

**Comment by taylorwaggoner** [comment]
You are now Certified Kubernetes

**Comment by IrisChanTW** [comment]
Dear Taylor,

Thank you!


BR,
Iris

Taylor Waggoner <notifications@github.com> 於 2020年9月18日 週五 上午3:50 寫道：

**Pull request merged**
