### PR TITLE
Conformance results for v1.24/mirantis-kubernetes-engine

### PR DESCRIPTION
**Pull request by ekitagawa**
Signed-off-by: Eiichi Kitagawa <ekitagawa@mirantis.com>

### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [ ] If this is a new entry, have you submitted a signed [participation form](https://github.com/cncf/k8s-conformance/tree/master/participation-form)?
* [x] Did you include the product/project logo in SVG, EPS or AI format?  
* [x] Does your logo clearly state the name of the product/project and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [ ] If your product/project is open source, did you include the `repo_url`?
* [x] Did you copy and paste the [installation and configuration instructions](https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions) into the README.md file in addition to linking to them?

### CODE REVIEW

**Comment by ekitagawa** [comment]
Please let me know if I'm missing any info on this PR.  Thank you in advance.

**Comment by Riaankl** [comment]
@ekitagawa PR heading should follow the [guide line](https://github.com/cncf/k8s-conformance/blob/master/instructions.md#contents-of-the-pr) for the CNCF-CI bot to check it.

**Comment by ekitagawa** [comment]
@Riaankl Does this meet the requirement?  
Thank you for the comment.  I went through the documentation, and I'm not quite show how exactly I got it wrong.  I also added space between `1.24` and `0` following your feedback on our previous PR.  Maybe, the requirement changed since then?

https://github.com/cncf/k8s-conformance/pull/1683#issuecomment-965760021

This time, I'm just going through past approved PRs and trying to match the pattern as the doc isn't giving me a good example.  (It has a really helpful example for PRODUCT.yaml though.)

Any advice will be greatly appreciated.  And thank you for your patience.

**Comment by Riaankl** [comment]
> @Riaankl Does this meet the requirement? Thank you for the comment. I went through the documentation, and I'm not quite show how exactly I got it wrong. I also added space between `1.24` and `0` following your feedback on our previous PR. Maybe, the requirement changed since then?
> 
> [#1683 (comment)](https://github.com/cncf/k8s-conformance/pull/1683#issuecomment-965760021)
> 
> This time, I'm just going through past approved PRs and trying to match the pattern as the doc isn't giving me a good example. (It has a really helpful example for PRODUCT.yaml though.)
> 
> Any advice will be greatly appreciated. And thank you for your patience.

You got it perfectly correct! The PR heading must have the word `Conformance` in the title to trigger the CNCF-CI Bot.
Your PR now have all the labels. (I just keep an eye on PR's comming in the have issues when checked by the bot and advise as I can)

**Comment by ekitagawa** [comment]
Great!  Thank you for the confirmation!

**Comment by taylorwaggoner** [comment]
You are now Certified Kubernetes

**Comment by ekitagawa** [comment]
Yay!  Thank you so much @taylorwaggoner

**Pull request merged**
