### PR TITLE
Conformance results for v1.16/QKE 

### PR DESCRIPTION
**Pull request by MrYourM**
### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [ ] If this is a new entry, have you submitted a signed [participation form](https://github.com/cncf/k8s-conformance/tree/master/participation-form)?
* [x] Did you include the product/project logo in SVG, EPS or AI format?  
* [x] Does your logo clearly state the name of the product/project and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [x] If your product/project is open source, did you include the `repo_url`?
* [x] Did you copy and paste the [installation and configuration instructions](https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions) into the README.md file in addition to linking to them?

### CODE REVIEW

**Comment by taylorwaggoner** [comment]
@MrYourM thanks for submitting.  I wanted to check in with you regarding the logo.  We had previously used [this logo](https://www.cncf.io/wp-content/uploads/2019/04/kubesphere-1.svg) for QKE before the conformance certification for this product expired on Dec 25, 2019.  I see that you have changed the name to Qingcloud Kubesphere Engine in the pull request, instead of the former name [KubeSphere®️ (QKE)](https://github.com/cncf/k8s-conformance/blob/master/v1.13/QKE/PRODUCT.yaml).  The logo will need to match the product name in order to be in correct alphabetical order in the landscape.  Would you like to call the product KubeSphere®️ (QKE) again and use the Kubesphere logo?  Thanks!

**Comment by MrYourM** [comment]
@taylorwaggoner Thank you, KubeSphere is a kubenetes distribution, however QingCloud KubeSphere Engine (QKE) is a hosted platform on QingCloud, so we update name to QingCloud KubeSphere Engine (QKE) instead of KubeSphere®️ (QKE) in this PR, and update logo to QingCloud Logo

**Comment by taylorwaggoner** [comment]
Ok thanks for updating!  Before we can certify, please make sure to paste all installation and configuration instructions into your README, in addition to linking to the user guide, [per these guidelines](https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions).

I also wanted to check in regarding the Kubesphere distribution.  I emailed Spencer, Ray, and kubesphere@yunify.com on May 28 about your conformance certification expiring on June 19.  Do you plan to submit new results before that date? Thanks!

**Comment by calvinyv** [comment]
@taylorwaggoner thanks for the reminder, we will submit KubeSphere conformance testing report in these two days. @Forest-L

**Comment by taylorwaggoner** [comment]
Thanks!  For this PR, all I need from you now is to update the README per my comment above.

Thanks!

**Comment by MrYourM** [comment]
@taylorwaggoner completed, thanks

**Comment by calvinyv** [comment]
@taylorwaggoner For KubeSphere updated conformance testing result, pls check https://github.com/cncf/k8s-conformance/pull/1013, thx.

**Comment by taylorwaggoner** [comment]
You are now Certified Kubernetes
https://landscape.cncf.io/format=card-mode&organization=qing-cloud&selected=qing-cloud-kube-sphere-engine-qke

**Pull request merged**
