### PR TITLE
Conformance results for v1.17/rafay

### PR DESCRIPTION
**Pull request by vishalk-rafay**
### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [ ] If this is a new entry, have you submitted a signed [participation form](https://github.com/cncf/k8s-conformance/tree/master/participation-form)?
* [x] Did you include the product/project logo in SVG, EPS or AI format?  
* [x] Does your logo clearly state the name of the product/project and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [ ] If your product/project is open source, did you include the `repo_url`?
* [x] Did you copy and paste the [installation and configuration instructions](https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions) into the README.md file in addition to linking to them?

### CODE REVIEW

**Comment by vishalk-rafay** [comment]
Conformance results for v1.17/rafay

**Comment by taylorwaggoner** [comment]
@vishalk-rafay thanks for submitting! We've recently tightened our [README requirements](https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions
) to ensure that the READMEs contain detailed directions on how to install and configure the Kubernetes implementations. Could you please copy/paste in all instructions and requirements in addition to linking to the URLs? Thanks!

**Comment by vishalk-rafay** [comment]
@taylorwaggoner I have updated the README for the detailed setup of installations.
Please let me know if I need to update the document further.

**Comment by taylorwaggoner** [comment]
You are now Certified Kubernetes
https://landscape.cncf.io/format=card-mode&organization=rafay-systems&selected=rafay

**Pull request merged**
