### PR TITLE
Conformance results for v1.17/elastisys-compliant-kubernetes

### PR DESCRIPTION
**Pull request by OlleLarsson**
### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [x] If this is a new entry, have you submitted a signed [participation form](https://github.com/cncf/k8s-conformance/tree/master/participation-form)?
* [x] Did you include the product/project logo in SVG, EPS or AI format?  
* [x] Does your logo clearly state the name of the product/project and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [x] If your product/project is open source, did you include the `repo_url`?
* [x] Did you copy and paste the [installation and configuration instructions](https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions) into the README.md file in addition to linking to them?

### CODE REVIEW

**Comment by taylorwaggoner** [comment]
@OlleLarsson, the results look great, but there's one thing to update. Per [these guidelines](https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions), could you please paste all instructions and requirements into the README in addition to linking to the URL? We're trying to provide step by step guidance so that your customers can later validate your conformance if they wish to. Thanks!

**Comment by taylorwaggoner** [comment]
@OlleLarsson checking in! thanks!

**Comment by OlleLarsson** [comment]
We are going to put the certification on hold for a little while, so I am closing this pull request for the time being.

Thank you for your time!

**Comment by taylorwaggoner** [comment]
Thanks @OlleLarsson - your 1.14 certification has expired, but please feel free to re-certify for a more recent version whenever you're ready!  Thanks!

**Pull request closed without merging**
