### PR TITLE
Conformance results for v1.13/vmware-aws-quickstart

### PR DESCRIPTION
**Pull request by johnSchnake**

### CODE REVIEW

**Comment by johnSchnake** [comment]
cc @rosskukulinski

**Comment by rosskukulinski** [comment]
Great, thanks @johnSchnake

**Comment by rosskukulinski** [comment]
@johnSchnake some tweaks please to product.yaml

```
description: This Quick Start sets up a flexible, secure AWS environment and launches a Kubernetes cluster automatically into a configuration of your choice.
name: VMware AWS Quick Start
product_logo_url: https://landscape.cncf.io/logos/v-mware-pks.svg
type: installer
```

**Comment by taylorwaggoner** [comment]
You are now Certified Kubernetes
https://landscape.cncf.io/format=card-mode&selected=v-mware-aws-quick-start

**Comment by rosskukulinski** [comment]
Thanks @taylorwaggoner !

**Pull request merged**
