### PR TITLE
CNCF conformance results for k8s v1.24/ntnx-karbon

### PR DESCRIPTION
**Pull request by legacyrj**
…y known as Karbon) for k8s v1.24/ntnx-karbon

Signed-off-by: legacyrj (raj.surve@nutnaix.com)
Signed-off-by: legacyrj <raj.surve@nutanix.com>

### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [ ] If this is a new entry, have you submitted a signed [participation form](https://github.com/cncf/k8s-conformance/tree/master/participation-form)?
* [x] Did you include the product/project logo in SVG, EPS or AI format?  
* [x] Does your logo clearly state the name of the product/project and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [x] If your product/project is open source, did you include the `repo_url`?
* [x] Did you copy and paste the [installation and configuration instructions](https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions) into the README.md file in addition to linking to them?

### CODE REVIEW

**Comment by legacyrj** [comment]
Hello @taylorwaggoner, Please help us review PR and provide feedback. Thank you.

**Comment by legacyrj** [comment]
Regarding failed tests: 

1. Field:  'contact_email_address' does not exist in 'PRODUCT.yaml'
2. URL error existed in previous PR as well: https://github.com/cncf/k8s-conformance/pull/2055

**Comment by legacyrj** [comment]
Hello @taylorwaggoner, All tests have passed. Please help us review PR and provide feedback.  Thank you.

**Comment by taylorwaggoner** [comment]
Please update logo url to https://landscape.cncf.io/logos/nutanix-karbon.svg

**Comment by legacyrj** [comment]
@taylorwaggoner updated logo as per your comment. Thank you.

**Comment by taylorwaggoner** [comment]
You are now Certified Kubernetes

**Pull request merged**
