### PR TITLE
Conformance results for v1.18/typhoon

### PR DESCRIPTION
**Pull request by dghubble**
[Typhoon](https://typhoon.psdn.io/) minimal and free distro, refreshed to show v1.18 results. :clinking_glasses:  

```
vendor: Poseidon
name: Typhoon
version: v1.18.0
website_url: https://typhoon.psdn.io/
repo_url: https://github.com/poseidon/typhoon
documentation_url: https://typhoon.psdn.io/
product_logo_url: https://storage.googleapis.com/poseidon/typhoon.svg
type: distro
description: Minimal and free Kubernetes distribution via Terraform
```

History: [v1.8](https://github.com/cncf/k8s-conformance/pull/40), [v1.11](https://github.com/cncf/k8s-conformance/pull/260), [v1.12](https://github.com/cncf/k8s-conformance/pull/356), [v1.13](https://github.com/cncf/k8s-conformance/pull/399), [v1.14](https://github.com/cncf/k8s-conformance/pull/536), [v1.15](https://github.com/cncf/k8s-conformance/pull/638), [v1.16](https://github.com/cncf/k8s-conformance/pull/724), [v1.17](https://github.com/cncf/k8s-conformance/pull/792)

### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [x] If this is a new entry, have you submitted a signed [participation form](https://github.com/cncf/k8s-conformance/tree/master/participation-form)?
* [x] Did you include the product/project logo in SVG, EPS or AI format?  
* [x] Does your logo clearly state the name of the product/project and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [x] If your product/project is open source, did you include the `repo_url`?
* [x] Did you copy and paste the [installation and configuration instructions](https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions) into the README.md file in addition to linking to them?

### CODE REVIEW

**Comment by taylorwaggoner** [comment]
@dghubble thanks for submitting!  Please paste the cluster installation instructions into the README when you have a moment.  We've recently been tightening the [README requirements](https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions). Thank you!

**Comment by dghubble** [comment]
The README does contain the detailed instructions for how to provision a Typhoon cluster with the various required settings to achieve conformance. I can't tell, are there generic instructions you'd like me to add in or do you mean you'd like there to be no external links of any kind?

**Comment by dghubble** [comment]
Looking at other PR reviews, I think the desire is to have docs pasted inline here and remove links to external sources. I've added the general / common docs here and removed the external links.

Folks can still find our detailed tutorials for 13 different OS + cloud combinations in our project if needed.

**Comment by taylorwaggoner** [comment]
Thanks! You can link to external sources, but we are asking for the docs to be pasted inline like you have done.  Do you want to add any links back to the README?

**Comment by dghubble** [comment]
I think having the updated docs and just the one link to https://github.com/poseidon/typhoon/blob/v1.18.0/README.md#modules is the most future proof. Since the pinned version won't change and shows the exact supported OS / cloud in a particular Kubernetes release. So all good to go from this end :D

Thanks!

**Comment by taylorwaggoner** [comment]
You are now Certified Kubernetes

**Pull request merged**
