### PR TITLE
Conformance results for v1.17/Harmonycloud-installer

### PR DESCRIPTION
**Pull request by WinterZhou**
### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [x] If this is a new entry, have you submitted a signed [participation form](https://github.com/cncf/k8s-conformance/tree/master/participation-form)?
* [x] Did you include the product/project logo in SVG, EPS or AI format?  
* [x] Does your logo clearly state the name of the product/project and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [ ] If your product/project is open source, did you include the `repo_url`?
* [x] Did you copy and paste the [installation and configuration instructions](https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions) into the README.md file in addition to linking to them?

### CODE REVIEW

**Comment by WinterZhou** [comment]
@taylorwaggoner hi, we want recategorize it as a installer. this PR is our installer product certification. 
Many Thanks!

**Comment by taylorwaggoner** [comment]
@WinterZhou please confirm that you want to recategorize your product from a distribution to an installer.  Please note that we just changed the product from a hosted platform to a distribution earlier this week in #920.  Thanks

**Comment by WinterZhou** [comment]
@taylorwaggoner  No, We want to authenticate both the distribution and installer versions. The previous #920 is the distribution version and this PR is the installer version. What should we do?Thanks

**Comment by taylorwaggoner** [comment]
Hi @WinterZhou - you will need to decide whether your product should be listed as a distribution or an installer - it can't be listed as both.  Please let us know if you have questions!

**Comment by WinterZhou** [comment]
@taylorwaggoner hi, This PR (Harmonycloud-installer) and #920 are different products, can't this PR product be certified as an installer?

**Pull request closed without merging**
