### PR TITLE
Submitting k8s conformance results for v1.20 for windrivercloud.

### PR DESCRIPTION
**Pull request by gwaines**
### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [ ] If this is a new entry, have you submitted a signed [participation form](https://github.com/cncf/k8s-conformance/tree/master/participation-form)?
* [ ] Did you include the product/project logo in SVG, EPS or AI format?  
* [ ] Does your logo clearly state the name of the product/project and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [ ] If your product/project is open source, did you include the `repo_url`?
* [ ] Did you copy and paste the [installation and configuration instructions](https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions) into the README.md file in addition to linking to them?

### CODE REVIEW

**Comment by gwaines** [comment]
Any guidance on the failed test ?

It is related to this issue:
https://github.com/kubernetes/kubernetes/pull/100449

Should we just remove the nginx-ingress Admission Controller and re-run the test ?

Greg.

**Comment by taylorwaggoner** [comment]
@gwaines we are not certifying for v1.20 per [these guidelines](https://github.com/cncf/k8s-conformance/blob/master/faq.md#what-versions-of-kubernetes-can-be-certified).  You will need to resubmit for 1.21, 1.22, or 1.23.  Thanks!

**Comment by Riaankl** [comment]
@gwaines I remember having seen a provious PR where that customization of Ingress resulted in a failed tests, however I can not seen to locate it. I also noted in the [PR](https://github.com/kubernetes/kubernetes/pull/100449#issuecomment-804788806) you mentioned there is a few solutions and limitations discussed. Would any of that help?

**Comment by gwaines** [comment]
Will the 1x failed test cases prevent getting our k8s-conformance certification approved ?
Greg.


p.s. … we have tested with the suggested solution, and everything passes … although it’s really a workaround for what looks like an issue with the k8s conformance test … just wanted to check whether I really need to do this workaround or not.

**Comment by gwaines** [comment]
adding carlos

From: Waines, Greg
Sent: Monday, January 24, 2022 8:17 AM
To: cncf/k8s-conformance ***@***.***>; cncf/k8s-conformance ***@***.***>
Cc: Mention ***@***.***>; Yan, Bin (Elizabeth) ***@***.***>
Subject: RE: [cncf/k8s-conformance] Submitting k8s conformance results for v1.20 for windrivercloud. (PR #1785)

Will the 1x failed test cases prevent getting our k8s-conformance certification approved ?
Greg.


p.s. … we have tested with the suggested solution, and everything passes … although it’s really a workaround for what looks like an issue with the k8s conformance test … just wanted to check whether I really need to do this workaround or not.

**Comment by gwaines** [comment]
Thanks Taylor … we’ll submit the 1.21 that we have available in our product now.
Greg.



p.s. Will the 1x failed test cases prevent getting our k8s-conformance certification approved ?   (see attached email)

… we have tested with the suggested solution, and everything passes … although it’s really a workaround for what looks like an issue with the k8s conformance test … just wanted to check whether I really need to do this workaround or not.

**Comment by taylorwaggoner** [comment]
@gwaines Unfortunately we can't approve PRs with any failed tests per our [reviewing instructions](https://github.com/cncf/k8s-conformance/blob/master/reviewing.md#technical-requirements) (bullet 5).  The test results must say PASS and this is what yours say:

> Ran 311 of 5668 Specs in 5370.227 seconds
FAIL! -- 310 Passed | 1 Failed | 0 Pending | 5357 Skipped
--- FAIL: TestE2E (5370.27s)
FAIL

**Comment by gwaines** [comment]
Yeah suspected that was the case.
Thanks for confirming.
We’ll do the changes to the way we are testing to get a 100% pass.
Greg.

**Pull request closed without merging**
