### PR TITLE
Conformance results for v1.20/vanillastack

### PR DESCRIPTION
**Pull request by galexrt**
Signed-off-by: Alexander Trost <galexrt@googlemail.com>

This PR contains an updated version of the participation form, should it be updated in the initial conformance results directory or simply added to this new one?

### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [x] If this is a new entry, have you submitted a signed [participation form](https://github.com/cncf/k8s-conformance/tree/master/participation-form)?
* [x] Did you include the product/project logo in SVG, EPS or AI format?  
* [x] Does your logo clearly state the name of the product/project and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [x] If your product/project is open source, did you include the `repo_url`?
* [x] Did you copy and paste the [installation and configuration instructions](https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions) into the README.md file in addition to linking to them?

### CODE REVIEW

**Comment by galexrt** [comment]
I'm not quite sure what tests we are missing from the results as we ran `sonobuoy run --mode=certified-conformance --plugin-env e2e.E2E_SKIP` (running sonobuoy `v0.53.2`).

I'm going to re-run the tests just to make sure that it wasn't a flake.

**Comment by taylorwaggoner** [comment]
@Riaankl ptal

**Comment by taylorwaggoner** [comment]
@hh please take a look, thanks!

**Comment by galexrt** [comment]
Sorry for the delay, we are going to re-run the tests and will get back to you.

**Comment by taylorwaggoner** [comment]
hi @galexrt  - we are not certifying for 1.20 anymore, so i'm going to close this out.  Please re-submit for 1.21 or higher when you are ready, thanks!

**Pull request closed without merging**
