### PR TITLE
Conformance results for v1.12/alicloud

### PR DESCRIPTION
**Pull request by xlgao-zju**
Signed-off-by: Xianglin Gao <xianglin.gxl@alibaba-inc.com>

### CODE REVIEW

**Comment by xlgao-zju** [comment]
@taylorwaggoner hi, Alibaba Cloud Kubernetes Service (ACK) is the same product as Alibaba Cloud Container Service, os it's great to update the product name in the list.

**Comment by taylorwaggoner** [comment]
@xlgao-zju thank you for confirming!  I apologize for not mentioning this before, but could you please fill out a new participation form that includes the new product name, based on this requirement: https://github.com/cncf/k8s-conformance/blob/master/faq.md#do-i-need-to-re-submit-results-if-we-rebrand-our-offering

Here is the link to the participation form: https://github.com/cncf/k8s-conformance/tree/master/participation-form

Thank you!

**Comment by xlgao-zju** [comment]
@taylorwaggoner hi, we have filled and submitted the new participation form via `DocuSign`.

**Comment by taylorwaggoner** [comment]
You are now Certified Kubernetes.
Updated name reflected here: https://landscape.cncf.io/format=card-mode&selected=alibaba-cloud-container-service-for-kubernetes

Thanks!

**Pull request merged**
