### PR TITLE
Conformance results for v1.18/ido-openness

### PR DESCRIPTION
**Pull request by mparamas-zz**
### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [x] If this is a new entry, have you submitted a signed [participation form](https://github.com/cncf/k8s-conformance/tree/master/participation-form)?
* [x] Did you include the product/project logo in SVG, EPS or AI format?  
* [x] Does your logo clearly state the name of the product/project and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [ ] If your product/project is open source, did you include the `repo_url`?
* [x] Did you copy and paste the [installation and configuration instructions](https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions) into the README.md file in addition to linking to them?

### CODE REVIEW

**Comment by taylorwaggoner** [comment]
You are now Certified Kubernetes
https://landscape.cncf.io/format=card-mode&organization=intel&selected=open-ness-ido

**Comment by mparamas-zz** [comment]
> You are now Certified Kubernetes
> https://landscape.cncf.io/format=card-mode&organization=intel&selected=open-ness-ido

@taylorwaggoner Could you help update the project name in landscape from "OpenNESS (IDO)" to "Intel® Distribution of OpenNESS" ?

**Comment by taylorwaggoner** [comment]
@mparamas-zz, we ask that the logo and product name match up so that the logos sort correctly in alphabetical order.  Do you have a different logo with the text "Intel® Distribution of OpenNESS"? Thanks!

**Comment by mparamas-zz** [comment]
@taylorwaggoner Thank you for the prompt response.
We refer to same logo For OpenNESS - Open & Licensed version with different title.
   Open       -  OpenNESS
   Licensed - Intel® Distribution of OpenNESS
Is it mandatory to have different logo per title ? pls clarify

**Comment by taylorwaggoner** [comment]
@mparamas-zz we need to have the logo text match the product name so that everything sorts correctly alphabetically.  Please see #5 here: https://github.com/cncf/landscape#logos
Thanks!

**Pull request merged**
