### PR TITLE
Conformance results for v1.17/ericsson-ccd

### PR DESCRIPTION
**Pull request by JanMkl**
### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [x] If this is a new entry, have you submitted a signed [participation form](https://github.com/cncf/k8s-conformance/tree/master/participation-form)?
* [x] Did you include the product/project logo in SVG, EPS or AI format?  
* [x] Does your logo clearly state the name of the product/project and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [ ] If your product/project is open source, did you include the `repo_url`?
* [x] Did you copy and paste the [installation and configuration instructions](https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions) into the README.md file in addition to linking to them?

### CODE REVIEW

**Comment by taylorwaggoner** [comment]
@JanMkl, your results look great, but there's one thing to update. Per [these guidelines](https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions), please paste all installation and configuration instructions, including provisioning the cluster, into the README. We're trying to provide step by step guidance so that your customers can later validate your conformance if they wish to. Thanks!

**Comment by taylorwaggoner** [comment]
@JanMkl checking in on this! thanks!

**Comment by taylorwaggoner** [comment]
@JanMkl please let me know if you have any questions about my comment above. Thanks!

**Comment by JanMkl** [comment]
@taylorwaggoner I will add the deployment instruction to the readme and get back to you shortly.

**Comment by JanMkl** [comment]
Now extended readme with instruction containing the steps to create the cluster using Openstack stack create.

**Comment by taylorwaggoner** [comment]
You are now Certified Kubernetes

**Pull request merged**
