### PR TITLE
Conformance results for v1.18/vmware-tanzu-kubernetes-grid

### PR DESCRIPTION
**Pull request by frapposelli**
/cc @taylorwaggoner

### CODE REVIEW

**Comment by taylorwaggoner** [comment]
@frapposelli thanks for submitting!  Please paste all cluster set up and configuration instructions into the README rather than directing to your documentation. We're trying to provide step by step guidance so that your customers can later validate your conformance if they wish to. Thanks!

**Comment by frapposelli** [comment]
@taylorwaggoner done 😄

**Comment by taylorwaggoner** [comment]
@frapposelli sorry for my delayed response here, but could you also update the README for 1.18?  Thanks so much!

**Comment by frapposelli** [comment]
@taylorwaggoner done! completely missed the other readme 😄

**Comment by taylorwaggoner** [comment]
You are now Certified Kubernetes.

**Pull request merged**
