### PR TITLE
Conformance results for v1.19/cloudboostr

### PR DESCRIPTION
**Pull request by miro-grapeup**
### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [ ] If this is a new entry, have you submitted a signed [participation form](https://github.com/cncf/k8s-conformance/tree/master/participation-form)?
* [x] Did you include the product/project logo in SVG, EPS or AI format?  
* [x] Does your logo clearly state the name of the product/project and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [x] If your product/project is open source, did you include the `repo_url`?
* [x] Did you copy and paste the [installation and configuration instructions](https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions) into the README.md file in addition to linking to them?

### CODE REVIEW

**Comment by ErinThacker** [comment]
@miro-grapeup - do you have a signed Participation Form on file with CNCF? I've looked in the file but cannot find it.  Perhaps it's under a different name?

**Comment by miro-grapeup** [comment]
@ErinThacker I have changed the description. This is not a new entry - we were already certified with versions 1.15 and 1.17. So, I am pretty sure that we have already signed a Participation Form.

**Comment by miro-grapeup** [comment]
@ErinThacker @taylorwaggoner is there anything blocking still? Can we move forward with merge? :)

**Comment by amye** [comment]
Reverting, merged by mistake because we're still missing the participation form.

**Comment by miro-grapeup** [comment]
@amye  and @ErinThacker  - so the merge was sucessfull, right? I can see the results are added in the main repo branch, but I cannot see our product on CNCF landscape (https://landscape.cncf.io/card-mode?category=certified-kubernetes-distribution&grouping=category), should we just wait some more time?

**Pull request merged**
