### PR TITLE
Conformance results for v1.20/kubermatic

### PR DESCRIPTION
**Pull request by xrstf**
### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [x] If this is a new entry, have you submitted a signed [participation form](https://github.com/cncf/k8s-conformance/tree/master/participation-form)?
* [x] Did you include the product/project logo in SVG, EPS or AI format?  
* [x] Does your logo clearly state the name of the product/project and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [x] If your product/project is open source, did you include the `repo_url`?
* [x] Did you copy and paste the [installation and configuration instructions](https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions) into the README.md file in addition to linking to them?

### CODE REVIEW

**Comment by brtknr** [comment]
Looks like the bug is still there

**Comment by xrstf** [comment]
Anything I should be doing about this? I saw that other 1.20 conformance results had the same issue.

**Comment by Riaankl** [comment]
> Anything I should be doing about this? I saw that other 1.20 conformance results had the same issue.

[PR#98940](https://github.com/kubernetes/kubernetes/pull/98940) was created to fix the issue.
We will look into it further.

**Comment by Riaankl** [comment]
@xrstf I believe we figured out the issue causing the failure of PR checks.
on 16 Jan, after the release for 1.20 was cut, two commits changed the 1.20 conformance.yaml file.
This cause a mismatch between what you get out of Sonobuoy and that the bot check against the v1.20 .yaml file.
A [PR](https://github.com/kubernetes/kubernetes/pull/99081/) was created to revert these commits, and that should stop the pain we are experiencing. 
We will discuss the topic at the next conformance meeting to see how the historical conformance.yaml file should be protected against unwanted change.
Once the PR merge I believe the bot will check are label your PR correctly.

**Comment by taylorwaggoner** [comment]
You are now Certified Kubernetes

**Pull request merged**
