### PR TITLE
Add AKS 1.15 conformance

### PR DESCRIPTION
**Pull request by lachie83**
Signed-off-by: Lachlan Evenson <lachlan.evenson@microsoft.com>

### CODE REVIEW

**Comment by taylorwaggoner** [comment]
@lachie83 , the results look great, but could you please copy and paste all installation instructions into the README file, rather than link to the webpage?  We are tightening the requirements for the README files and have [added some instructions to our FAQ](https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions). Please also update #832 and #833 
Let us know if you have questions!
Thanks!

**Comment by taylorwaggoner** [comment]
@lachie83 , wanted to check in on this PR and #832 and #833.  Let us know if you have any questions!

**Comment by lachie83** [comment]
Hi @taylorwaggoner I've updated the README based on what I see from other conformant platforms within the v1.15 directory

**Comment by taylorwaggoner** [comment]
You are now Certified Kubernetes

**Pull request merged**
