### PR TITLE
Conformance results for v1.19/Moondog

### PR DESCRIPTION
**Pull request by bit-herder**
### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [x] If this is a new entry, have you submitted a signed [participation form](https://github.com/cncf/k8s-conformance/tree/master/participation-form)?
* [x] Did you include the product/project logo in SVG, EPS or AI format?  
* [x] Does your logo clearly state the name of the product/project and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [x] If your product/project is open source, did you include the `repo_url`?
* [x] Did you copy and paste the [installation and configuration instructions](https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions) into the README.md file in addition to linking to them?

### CODE REVIEW

**Comment by taylorwaggoner** [comment]
@bit-herder thanks for submitting!  The results look great, but can you please add the installation instructions to the README per [these guidelines](https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions)?
Thanks!

**Comment by bit-herder** [comment]
@taylorwaggoner 

hi, this is a re-certification, please see this original certification issue for the original response to this: 

https://github.com/cncf/k8s-conformance/pull/900#issuecomment-604491287

If that is sufficient please LMK, if not please let me know that as well and I will try my best to get it corrected. We are up against a deadline of Sept 18th. Thanks for your help and understanding.

**Comment by taylorwaggoner** [comment]
@bit-herder thanks for the clarification!  Could you please edit the README to say something about how a customer would go about getting this installed? Maybe something about who to contact, etc? Thanks!

**Comment by bit-herder** [comment]
updated! Please let me know if there is anything else you require.

**Comment by taylorwaggoner** [comment]
Thanks! You are now Certified Kubernetes

**Pull request merged**
