### PR TITLE
Conformance results for v1.19/taikun

### PR DESCRIPTION
**Pull request by chnyda**
Signed-off-by: Cedric Hnyda <cedric.hnyda@itera.io>

### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [x] If this is a new entry, have you submitted a signed [participation form](https://github.com/cncf/k8s-conformance/tree/master/participation-form)?
* [x] Did you include the product/project logo in SVG, EPS or AI format?  
* [x] Does your logo clearly state the name of the product/project and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [ ] If your product/project is open source, did you include the `repo_url`?
* [x] Did you copy and paste the [installation and configuration instructions](https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions) into the README.md file in addition to linking to them?

### CODE REVIEW

**Comment by taylorwaggoner** [comment]
@chnyda thanks for submitting. Are there any additional instructions you could provide in the README to make it easy for a user to recreate the results?  We're looking for detailed instructions as much as possible.  
Thanks!

**Comment by chnyda** [comment]
Thanks for your feedback @taylorwaggoner . I just added more instruction on how to create the cluster with Taikun (it is already intuitive) and how to run the tests.

**Comment by taylorwaggoner** [comment]
Awesome thank you!  Could you please update the readme in #1548 as well?

**Comment by chnyda** [comment]
We updated both README @taylorwaggoner  :)

**Comment by taylorwaggoner** [comment]
You are now Certified Kubernetes.
https://landscape.cncf.io/card-mode?organization=itera-technologies-a-s&selected=taikun

**Pull request merged**
