### PR TITLE
Conformance Results for v1.21/gardener

### PR DESCRIPTION
**Pull request by dguendisch**
### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [x] If this is a new entry, have you submitted a signed [participation form](https://github.com/cncf/k8s-conformance/tree/master/participation-form)?
* [x] Did you include the product/project logo in SVG, EPS or AI format?  
* [x] Does your logo clearly state the name of the product/project and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [x] If your product/project is open source, did you include the `repo_url`?
* [x] Did you copy and paste the [installation and configuration instructions](https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions) into the README.md file in addition to linking to them?

As requested by @taylorwaggoner in https://github.com/cncf/k8s-conformance/pull/1291#issuecomment-765743659 we're now splitting the PRs for "products" `sap-cp` and `gardener` into two distinct ones.

cc @schrodit

### CODE REVIEW

**Comment by dguendisch** [comment]
@taylorwaggoner can you help getting this merged?

**Comment by taylorwaggoner** [comment]
@dguendisch same issue as #1546 with some of the files pointing to 1.20 instead of 1.21. thanks!

**Comment by dguendisch** [comment]
Answered in https://github.com/cncf/k8s-conformance/pull/1546#issuecomment-894064876, thanks for pointing out!

**Comment by taylorwaggoner** [comment]
Great thanks. You are now Certified Kubernetes

**Pull request merged**
