### PR TITLE
Bump kube-conformance image for k8s v1.11

### PR DESCRIPTION
**Pull request by chuckha**
Signed-off-by: Chuck Ha <chuck@heptio.com>

### CODE REVIEW

**Comment by chuckha** [comment]
@stealthybox

**Comment by stealthybox** [comment]
design ref: https://github.com/kubernetes/kubeadm/issues/951#issuecomment-401150927

This blocks https://github.com/kubernetes/kubeadm/issues/951

**Comment by stealthybox** [comment]
@chuckha I'll try this yaml for another conformance run and see if things pass.

**Comment by chuckha** [comment]
I am also in the middle of a run, a 1.10.5 cluster running 1.11.0 conformance tests

**Comment by stealthybox** [comment]
LGTM :+1:
```
root@vagrant:/vagrant/v1.11# cat version.txt

Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T20:17:28Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T20:08:34Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}

root@vagrant:/vagrant/v1.11# tail plugins/e2e/results/e2e.log
------------------------------
SSJun 28 21:03:55.667: INFO: Running AfterSuite actions on all node
Jun 28 21:03:55.667: INFO: Running AfterSuite actions on node 1
Jun 28 21:03:55.667: INFO: Skipping dumping logs from cluster

Ran 143 of 998 Specs in 3937.022 seconds
SUCCESS! -- 143 Passed | 0 Failed | 0 Pending | 855 Skipped PASS

Ginkgo ran 1 suite in 1h5m37.659108319s
Test Suite Passed
```

**Pull request merged**
