### PR TITLE
Rename PKS to TKGI and add 1.16 conformance

### PR DESCRIPTION
**Pull request by ktchen14**
### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [x] If this is a new entry, have you submitted a signed [participation form](https://github.com/cncf/k8s-conformance/tree/master/participation-form)?
* [x] Did you include the product/project logo in SVG, EPS or AI format?  
* [x] Does your logo clearly state the name of the product/project and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [x] Did you copy and paste the [installation and configuration instructions](https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions) into the README.md file in addition to linking to them?

### CODE REVIEW

**Comment by taylorwaggoner** [comment]
@ktchen14, thanks for submitting. The new results for 1.16 look good!  However, we’ve been tightening up our [requirements for the README files](https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions) and ask that all installation and configuration instructions be pasted into the README in addition to providing the URLs. I noticed that the v1.8 and v1.9 READMEs are slightly different than all of the more recent ones - there are several broken URLs that need to be updated.  Please let me know if you have any questions!

**Comment by ktchen14** [comment]
Hi @taylorwaggoner: I can definitely fix up the 1.8 and 1.9 READMEs. I'll try to take a pass at copying the installation instructions into the READMEs as well.

**Comment by taylorwaggoner** [comment]
@ktchen14 thanks! Let me know if you have any questions

**Comment by taylorwaggoner** [comment]
@ktchen14 checking in! thanks!

**Comment by ktchen14** [comment]
Okay I've inlined a short version of the installation instructions for Kubernetes v1.10+. As v1.8 and v1.9 are so out of date, I wasn't able to update those instructions.

**Comment by ktchen14** [comment]
Hi @taylorwaggoner. Let me know if I need to do anything else here. Thanks!

**Comment by taylorwaggoner** [comment]
Great thanks!  You are now Certified Kubernetes

**Pull request merged**
