### PR TITLE
Conformance results for v1.19/h3c-cloudos

### PR DESCRIPTION
**Pull request by jiangchunlong597**

### CODE REVIEW

**Comment by taylorwaggoner** [comment]
@jiangchunlong597 please make sure you are including all required tests. thanks!

**Comment by jiangchunlong597** [comment]
Conformance results for v1.19/h3c-cloudos

**Comment by jiangchunlong597** [comment]
@taylorwaggoner   hi，anything else needed？

**Comment by taylorwaggoner** [comment]
You are now Certified Kubernetes

**Comment by jiangchunlong597** [comment]
@taylorwaggoner  thanks!

**Pull request merged**
