### PR TITLE
Conformance results for v1.25/kubespray

### PR DESCRIPTION
**Pull request by cristicalin**
### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [x] If this is a new entry, have you submitted a signed [participation form](https://github.com/cncf/k8s-conformance/tree/master/participation-form)?
* [x] Did you include the product/project logo in SVG, EPS or AI format?  
* [x] Does your logo clearly state the name of the product/project and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [x] If your product/project is open source, did you include the `repo_url`?
* [x] Did you copy and paste the [installation and configuration instructions](https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions) into the README.md file in addition to linking to them?

For a full list of requirements, please refer to these sections of the docs: [_Contents of the PR_](https://github.com/cncf/k8s-conformance/blob/master/instructions.md#contents-of-the-pr), and [_Requirements_](https://github.com/cncf/k8s-conformance/blob/master/instructions.md#requirements).

### CODE REVIEW

**Comment by taylorwaggoner** [comment]
@cristicalin thanks!  Please add a contact email address in the PRODUCT file per the error above, thanks!

**Comment by cristicalin** [comment]
Hi @taylorwaggoner we are working to come up with an email list since currently the project doesn't have one. I reached out to the CNCF to create a distribution list for maintainers on lists.cncf.io and update the PR once we manage to settle the matter.

**Comment by taylorwaggoner** [comment]
@cristicalin checking in here, thanks!

**Comment by taylorwaggoner** [comment]
@cristicalin checking in

**Comment by taylorwaggoner** [comment]
@cristicalin you can put down any contact for now and we can update as needed later

**Comment by taylorwaggoner** [comment]
@cristicalin is there any contact we can put here for Kubespray?  1.28 comes out next week and we won't be able to certify for 1.25 any longer, so best to get this put through ASAP. thanks

**Comment by taylorwaggoner** [comment]
@cristicalin I'm going to push this through but please add a contact email address to your next pull request. Thanks!

You are now Certified Kubernetes

**Comment by taylorwaggoner** [comment]
Also, 1.25 expires on September 9, so you will need to submit newer results before then. If you could send me an email address I will send you the expiration notice. thanks

**Pull request merged**
