### PR TITLE
Change Mirantis Docker Enterprise naming to Mirantis Kubernetes Engine

### PR DESCRIPTION
**Pull request by nickchase**
### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [x] If this is a new entry, have you submitted a signed [participation form](https://github.com/cncf/k8s-conformance/tree/master/participation-form)?
* [x] Did you include the product/project logo in SVG, EPS or AI format?  
* [x] Does your logo clearly state the name of the product/project and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [x] If your product/project is open source, did you include the `repo_url`?
* [x] Did you copy and paste the [installation and configuration instructions](https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions) into the README.md file in addition to linking to them?

### CODE REVIEW

**Comment by taylorwaggoner** [comment]
@nickchase thanks for submitting!  Could you update this PR so that the product name is changed in your most recent 1.18 results? thanks!

**Comment by taylorwaggoner** [comment]
@nickchase checking in on my last comment thanks

**Comment by taylorwaggoner** [comment]
@nickchase checking in!

**Comment by amye** [comment]
@nickchase: Could you update this PR so that the product name is changed in your most recent 1.18 results? Thanks!

**Comment by ErinThacker** [comment]
@idvoretskyi @nickchase @amye - has this been resolved?

**Comment by ErinThacker** [comment]
Update has been squashed & merged.

**Pull request merged**
