### PR TITLE
Conformance results for v1.12/microk8s

### PR DESCRIPTION
**Pull request by ktsakalozos**
Conformance results for microk8s v1.12 by Canonical

### CODE REVIEW

**Comment by taylorwaggoner** [comment]
@ktsakalozos thank you for submitting these results!  They look great, but I'll need a couple things from you before we can merge.  First, as this is the first submission for microk8s, can you please submit a new participation form for this product?  https://github.com/cncf/k8s-conformance/tree/master/participation-form

Second, please update the PRODUCT.yaml to include the type, and possibly a description of microk8s if you'd like, per the instructions here: https://github.com/cncf/k8s-conformance/blob/master/instructions.md#productyaml

Thanks!

**Comment by taylorwaggoner** [comment]
@ktsakalozos Wanted to check in with you.  I haven't seen the new participation form come through yet for microk8s.  Please let me know if you have any questions!

**Comment by ktsakalozos** [comment]
@taylorwaggoner the legal team will take care of signing the form on behalf of Canonical. I assume they will not face any problems since they have done the same thing for the Canonical Distribution of Kubernetes (CDK). @tvansteenburgh may have more info on this.

**Comment by taylorwaggoner** [comment]
@ktsakalozos @tvansteenburgh you are now Certified Kubernetes.  We classified your product as an installer based on these guidelines https://github.com/cncf/k8s-conformance/blob/master/faq.md#what-is-a-distribution-hosted-platform-and-an-installer

Please let us know if you have any questions!

**Comment by ktsakalozos** [comment]
thanks @taylorwaggoner

**Pull request merged**
