### PR TITLE
K8S Diamanti D20 1.14 conformance

### PR DESCRIPTION
**Pull request by AlexDiamanti**
Please, review our results and approve.

Thanks,
Diamanti

### CODE REVIEW

**Comment by taylorwaggoner** [comment]
@AlexDiamanti, results look great!  I'd like to confirm the product name before we move forward with certification.  We have your product listed as 'D10' on the [K8s distro sheet](https://docs.google.com/spreadsheets/d/1LxSqBzjOxfGx3cmtZ4EbB_BGCxT_wlxW_xgHVVa23es/edit#gid=0) and 'Diamanti Converged Container Infrastructure' [on the landscape](https://landscape.cncf.io/format=card-mode&selected=diamanti-converged-container-infrastructure).  Your product name in this PR is D20. Can you please confirm if these are all the same product?  Please submit an updated [participation form](https://github.com/cncf/k8s-conformance/tree/master/participation-form) with the current name. Thanks!

**Comment by AlexDiamanti** [comment]
Thank You, Taylor.  We need to change Product name from "Diamanti-D10" to "Diamanti-DXX".  We already have D10 and D20 appliances with different hardware both capable of running our software distributions.  Latest version of the hardware is D20 and latest version of the software is 2.3.x   Product name "Diamanti-DXX" should cover all of the hardware models appropriately.

Thanks.

**Comment by AlexDiamanti** [comment]
Participation form was completed and sent out.

**Comment by taylorwaggoner** [comment]
@AlexDiamanti, do you want to update your description to say Diamanti-DXX as well?  And is that how you'd like it updated in the landscape?

**Comment by AlexDiamanti** [comment]
Sure. Thanks

**Comment by taylorwaggoner** [comment]
You are now Certified Kubernetes.
https://landscape.cncf.io/format=card-mode&grouping=category&organization=diamanti&selected=diamanti-dxx

**Pull request merged**
