### PR TITLE
Conformance results for v1.18/kubespray

### PR DESCRIPTION
**Pull request by Miouge1**
Adding Kubespray v2.14 with support for k8s v1.18.

### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [x] If this is a new entry, have you submitted a signed [participation form](https://github.com/cncf/k8s-conformance/tree/master/participation-form)?
* [x] Did you include the product/project logo in SVG, EPS or AI format?  
* [x] Does your logo clearly state the name of the product/project and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [x] If your product/project is open source, did you include the `repo_url`?
* [x] Did you copy and paste the [installation and configuration instructions](https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions) into the README.md file in addition to linking to them?

### CODE REVIEW

**Comment by Miouge1** [comment]
Mmm not too sure what is wrong with the files. File names look correct? Anyone who can point me in the right direction?

**Comment by Miouge1** [comment]
I think that the e2e.log has an appropriate k8s version:

```console
$ grep "e2e test versio" e2e.log
Dec  1 19:07:09.532: INFO: e2e test version: v1.18.2
```

**Comment by taylorwaggoner** [comment]
Looking into this, will keep you posted!

**Comment by hh** [comment]
I think this may be an issue with the pr title. The bot was written to find and use the Kubernetes version specified in the title based on the following:

https://github.com/cncf/k8s-conformance/blob/master/instructions.md#uploading

Description: ```Conformance results for vX.Y/$dir```

@cncf-ci likely got confused with the multiple vX.Y when searching for the k8s version and went with the first one it found.

 While I can tell you are looking to certify k8s v1.18, the bot thought you where trying to certify k8s v2.14 in the logs and supporting files.

Retitle as documented and it should pass!

**Comment by Miouge1** [comment]
Thank you! That makes sense.

**Comment by taylorwaggoner** [comment]
You are now Certified Kubernetes

**Pull request merged**
