### PR TITLE
Conformance results for v1.18/KubeOps

### PR DESCRIPTION
**Pull request by demcaNative**
### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [x] If this is a new entry, have you submitted a signed [participation form](https://github.com/cncf/k8s-conformance/tree/master/participation-form)?
* [x] Did you include the product/project logo in SVG, EPS or AI format?  
* [x] Does your logo clearly state the name of the product/project and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [x] If your product/project is open source, did you include the `repo_url`?
* [x] Did you copy and paste the [installation and configuration instructions](https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions) into the README.md file in addition to linking to them?

### CODE REVIEW

**Comment by taylorwaggoner** [comment]
@demcaNative just checking in about the participation form.  Please let me know if you have any questions about filling it out and sending it in.  Thanks!

**Comment by demcaNative** [comment]
Hello Mr Waggoner,

sure, I just told our managing director about this matter, he’ll surely go for it soon.

Thank you for your help.

Best wishes and stay safe,
Can Demir

**Comment by taylorwaggoner** [comment]
@demcaNative checking in on the participation form, thanks!

**Comment by taylorwaggoner** [comment]
@demcaNative any word on the participation form? thanks!

**Comment by taylorwaggoner** [comment]
@demcaNative I'm going to close this out but feel free to reopen once a participation form is sent in, thanks!

**Comment by demcaNative** [comment]
Hello @taylorwaggoner sorry for this huge delay, the participation form is sent in. How do we proceed from now?

**Comment by taylorwaggoner** [comment]
@demcaNative please let me know where the participation form was sent - I haven't received it yet. Thanks!

**Comment by demcaNative** [comment]
@taylorwaggoner sure I'm on it, I'll let you know asap.

**Comment by demcaNative** [comment]
Good evening @taylorwaggoner the participation form was just send in. Hope to hear from you soon.

**Comment by taylorwaggoner** [comment]
@demcaNative thanks! I sent a reply a couple of days ago - we need the form to have the product name KubeOps listed. Thanks

**Comment by demcaNative** [comment]
Hello @taylorwaggoner as we have renamed our product to lima I have changed the product description according to the form. But I see no possibility to change the directory name in this pull request. Do I have to change other things for compliance? Greetings

**Comment by amye** [comment]
Options: 
1) You may be able to edit this PR from your local copy and change the directory names in there. 
2) Refiling with the new name. 

Hope that helps!

**Comment by amye** [comment]
@demcaNative: I would move your conformance files to a new folders called 'Lima' under the 1.18 folder, then delete the https://github.com/demcaNative/k8s-conformance/tree/master/v1.18/KubeOps folder. 
Alternatively, you can open a new pull request with the correct name.

**Comment by ErinThacker** [comment]
@demcaNative @amye  - has this been resolved?

**Comment by demcaNative** [comment]
We added this change in a pull request: https://github.com/cncf/k8s-conformance/pull/1383

**Comment by ErinThacker** [comment]
@demcaNative - I hate to ask for this again, but I need the participation form. I can't find it, could be under a different name. Can you send it one more time to kcsp@cncf.io?

**Comment by amye** [comment]
1.18 is past availability for conformance.

**Pull request closed without merging**
