### PR TITLE
 Conformance results for v1.20/hpe-ezmeral-runtime-enterprise

### PR DESCRIPTION
**Pull request by vadbluedata**
### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [x ] If this is a new entry, have you submitted a signed [participation form](https://github.com/cncf/k8s-conformance/tree/master/participation-form)?
* [ x] Did you include the product/project logo in SVG, EPS or AI format?  
* [ x] Does your logo clearly state the name of the product/project and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [ x] If your product/project is open source, did you include the `repo_url`?
* [x ] Did you copy and paste the [installation and configuration instructions](https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions) into the README.md file in addition to linking to them?

### CODE REVIEW

**Comment by taylorwaggoner** [comment]
@vadbluedata thanks for submitting!  Is this a rebrand of "HPE Ezmeral Container Platform" or a different product?

**Comment by vadbluedata** [comment]
This is a different k8s product - the way we build k8s is different, but its currently bundled into HPE Ezmeral Container Platform. So from user's perspective the only difference is a different .bin file and different k8s version - the "hpe" one.

**Comment by taylorwaggoner** [comment]
Ok thanks!  Since it does have a different product name please fill out a new participation form for it - https://github.com/cncf/k8s-conformance/tree/master/participation-form
Thanks!

**Comment by taylorwaggoner** [comment]
You are now Certified Kubernetes
your listing will be live by early next week
https://github.com/cncf/landscape/pull/2374

**Comment by taylorwaggoner** [comment]
@vadbluedata please also note that 1.20 certifications expire in early Jan, so you will want to recertify for 1.21 or higher soon

**Pull request merged**
