### PR TITLE
Conformance results for v1.22/TaiChu

### PR DESCRIPTION
**Pull request by whoisfisher**
### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [x] If this is a new entry, have you submitted a signed [participation form](https://github.com/cncf/k8s-conformance/tree/master/participation-form)?
- [x] Did you include the product/project logo in SVG, EPS or AI format?  
- [x] Does your logo clearly state the name of the product/project and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [ ] If your product/project is open source, did you include the `repo_url`?
- [x] Did you copy and paste the [installation and configuration instructions](https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions) into the README.md file in addition to linking to them?

### CODE REVIEW

**Comment by Riaankl** [comment]
@whoisfisher I noted that the CNCF-CI Bot is not checking your PR.
We looked into the logs and it return the following error:
```
error running checks on PR: failed to make a HEAD request to 
url 'https://www.rails.cn/xian/en-us/src/prointroduce/kmpp' from the field '1838' in PRODUCT.yaml in 
PR (Head \"[https://www.rails.cn/xian/en-us/src/prointroduce/kmpp\](https://www.rails.cn/xian/en-us/src/prointroduce/kmpp/)": 
x509: certificate signed by unknown authority)
```
Seem the certificates for the URLs in the PRODUCT.yaml cause an error in the Bot behaviour, which is not desireble.
We will look at fixing that shortly.
In the mean time would it be possible to look at the URL certificates?

**Comment by whoisfisher** [comment]
@Riaankl 
We have confirmed that our certificate issuing agency is GlobalSign. Is there any question ?
lQLPDhtD9kfubYLNAgbNAbewwY62cExJR4QCQAWvG8CsAA_439_518

**Comment by Riaankl** [comment]
@whoisfisher we would then have to look into it further.

**Comment by whoisfisher** [comment]
@Riaankl Hello, have you got any results?

**Comment by Riaankl** [comment]
> @Riaankl Hello, have you got any results?

Thank you for your patience, we resolved the issue.

**Comment by whoisfisher** [comment]
@Riaankl so could the pr be merged now?

**Comment by taylorwaggoner** [comment]
@whoisfisher have you submitted a signed [participation form](https://github.com/cncf/k8s-conformance/tree/master/participation-form)? Thanks!

**Comment by whoisfisher** [comment]
@taylorwaggoner Hello ,I have added participation form.

**Comment by taylorwaggoner** [comment]
@whoisfisher thanks! In your README, could you please add more details about how to install and configure your product? We are trying to make it easy for users to replicate your test results. Thanks!

**Comment by whoisfisher** [comment]
@taylorwaggoner Hello, could the pr be merged?

**Comment by taylorwaggoner** [comment]
You are now Certified Kubernetes
Your listing will be added to the Cloud Native landscape soon

**Pull request merged**
