### PR TITLE
Conformance results for v1.20/k0s v0.10.0

### PR DESCRIPTION
**Pull request by jnummelin**
Signed-off-by: Jussi Nummelin <jnummelin@mirantis.com>

### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [x] If this is a new entry, have you submitted a signed [participation form](https://github.com/cncf/k8s-conformance/tree/master/participation-form)?
* [x] Did you include the product/project logo in SVG, EPS or AI format?  
* [x] Does your logo clearly state the name of the product/project and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [x] If your product/project is open source, did you include the `repo_url`?
* [x] Did you copy and paste the [installation and configuration instructions](https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions) into the README.md file in addition to linking to them?

### CODE REVIEW

**Comment by jnummelin** [comment]
> The first test found to be mssing was [sig-scheduling] SchedulerPredicates [Serial] validates that there is no conflict between pods with same hostPort but different hostIP and protocol [LinuxOnly] [Conformance]

#1308 is seeing the same thing, although in their case the validation result has changed without them changing the test result data.

Feels like a bug in the bot validating the results 🤷

**Comment by taylorwaggoner** [comment]
Thanks for pointing that out @jnummelin  - we are looking into this and will get back to you!

**Comment by jnummelin** [comment]
@taylorwaggoner  thanks

**Comment by Riaankl** [comment]
@jnummelin I looked at the failure message and replicated it in another repo.

The error is valid and there is a miss-match between the conformance.yaml file in the K/K Master branch and the content of your junit file. This was caused by PR [#98299](https://github.com/kubernetes/kubernetes/pull/98299) changing the conformance.yaml file.

Your data contain the test `[sig-scheduling] SchedulerPredicates [Serial] validates that there is no conflict between pods with same hostPort but different hostIP and protocol [LinuxOnly] [Conformance]` but that was replaced by  `[sig-network] HostPort validates that there is no conflict between pods with same hostPort but different hostIP and protocol [LinuxOnly] [Conformance] ` in the PR mentioned.
Unfortunately, this will happen if the conformance.yaml get updated between the pulling of the data and the submission of the results.
You can resolve this by pulling the latest data and re-run your tests. 

Sorry, for the confusing error message. The message has a logic error, reporting the test that fell out and not the missing new test. (We are working on that)

**Comment by Riaankl** [comment]
@jnummelin It seems to be a bug.
We are trying to sort it out as soon as possible.

**Comment by hh** [comment]
I think we found the issue upstream.
It's related to a test that got moved and it's metadata wasn't fully updated.

We created a PR for this:

**Comment by jnummelin** [comment]
@hh thanks for the update

**Comment by Riaankl** [comment]
@jnummelin I believe we figured out the issue causing the failure of PR checks.
on 16 Jan, after the release for 1.20 was cut, two commits changed the 1.20 conformance.yaml file.
This cause a mismatch between what you get out of Sonobuoy and that the bot check against the v1.20 .yaml file.
A [PR](https://github.com/kubernetes/kubernetes/pull/99081/) was created to revert these commits, and that should stop the pain we are experiencing. 
We will discuss the topic at the next conformance meeting to see how the historical conformance.yaml file should be protected against unwanted change.
Once the PR merge I believe the bot will check are label your PR correctly.

**Comment by jnummelin** [comment]
@Riaankl thanks for addressing this, I now see all the proper labels in place.

**Pull request merged**
