### PR TITLE
Conformance results for v1.20/openshift-dedicated

### PR DESCRIPTION
**Pull request by jeremyeder**
### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [x] If this is a new entry, have you submitted a signed [participation form](https://github.com/cncf/k8s-conformance/tree/master/participation-form)?
* [x] Did you include the product/project logo in SVG, EPS or AI format?  
* [x] Does your logo clearly state the name of the product/project and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [x] If your product/project is open source, did you include the `repo_url`?
* [x] Did you copy and paste the [installation and configuration instructions](https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions) into the README.md file in addition to linking to them?

### CODE REVIEW

**Comment by jeremyeder** [comment]
@taylorwaggoner my last PR for 1.19 also hit some [validation issue](https://github.com/cncf/k8s-conformance/pull/1185#issuecomment-719586476) but was ultimately merged.  WDYT?

**Comment by jeremyeder** [comment]
@taylorwaggoner ping?

**Comment by jeremyeder** [comment]
@taylorwaggoner any update on this PR?

**Comment by amye** [comment]
@jeremyeder: Taylor's out on leave, I'm reviewing now. 

Looks like the last issue was similar but slightly different: 
"The first test found to be mssing was [sig-api-machinery] Watchers should observe add, update, and delete watch notifications on configmaps [Conformance]" 

@hh, your thoughts?

**Comment by amye** [comment]
Annd I just got @hh's out of office through April 6th, so standby.

**Comment by dims** [comment]
i can see the following in the [e2e.log](https://raw.githubusercontent.com/cncf/k8s-conformance/7397e3b53036ebeb07183ec0cfcb5913dd78eed9/v1.20/openshift-dedicated/e2e.log):
`{"msg":"PASSED [sig-api-machinery] AdmissionWebhook [Privileged:ClusterAdmin] listing mutating webhooks should work [Conformance]","total":-1,"completed":87,"skipped":1471,"failed":0}`

But is missing from the junit.xml ... I am inclined to sign this off with 👍🏾 we should request the openshift team to verify their tooling to see how they generate the junit xml file.

**Comment by amye** [comment]
Brilliant, I will add this to the list of reviews to complete. Thank you @dims!

**Comment by amye** [comment]
You are now Certified Kubernetes

**Comment by jeremyeder** [comment]
I somehow missed that this was merged.  Thank you both.  We will look into the report generation, it is weird that only one test didn't show up in the output.

**Pull request merged**
