### PR TITLE
Conformance results for v1.23/BoCloud-d

### PR DESCRIPTION
**Pull request by hwdef**
### Pre-submission checklist:

* [ ] If this is a new entry, have you submitted a signed [participation form](https://github.com/cncf/k8s-conformance/tree/master/participation-form)?
* [x] Did you include the product/project logo in SVG, EPS or AI format?  
* [x] Does your logo clearly state the name of the product/project and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [ ] If your product/project is open source, did you include the `repo_url`?
* [x] Did you copy and paste the [installation and configuration instructions](https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions) into the README.md file in addition to linking to them?

### CODE REVIEW

**Comment by hwdef** [comment]
kindly ping @taylorwaggoner 
And I'm having some confusion, our product “BoCloud” has obtained the k8s conformance certification of type ‘hosted’, We would like to apply for certification of type ‘Distribution’ for the same product again. We want to add logo to the `Distribution` categroy at  [kubernetes.io/partners/#conformance](https://kubernetes.io/partners/#conformance). What should we do? Do we need to send another email?
Thanks!

**Comment by taylorwaggoner** [comment]
@hwdef generally companies pick either Hosted or Distribution for the product, depending on which category fits their product best.  Which category do you prefer? thanks!

**Comment by hwdef** [comment]
I think we choose Distribution, thanks!

**Comment by hwdef** [comment]
@taylorwaggoner

**Comment by taylorwaggoner** [comment]
@hwdef ok great. Since your product is already certified for 1.23, all you would need to do is close this PR and submit a new one that updates your 1.23 product.yaml from hosted to distribution: https://github.com/cncf/k8s-conformance/blob/master/v1.23/bocloud/PRODUCT.yaml

**Pull request closed without merging**
