### PR TITLE
Conformance test results for v1.27/kubeclipper

### PR DESCRIPTION
**Pull request by x893675**
### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [x] If this is a new entry, have you submitted a signed [participation form](https://github.com/cncf/k8s-conformance/tree/master/participation-form)?
* [x] Did you include the product/project logo in SVG, EPS or AI format?  
* [x] Does your logo clearly state the name of the product/project and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [x] If your product/project is open source, did you include the `repo_url`?
* [x] Did you copy and paste the [installation and configuration instructions](https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions) into the README.md file in addition to linking to them?

For a full list of requirements, please refer to these sections of the docs: [_Contents of the PR_](https://github.com/cncf/k8s-conformance/blob/master/instructions.md#contents-of-the-pr), and [_Requirements_](https://github.com/cncf/k8s-conformance/blob/master/instructions.md#requirements).

### CODE REVIEW

**Comment by taylorwaggoner** [comment]
You are now Certified Kubernetes

**Comment by x893675** [comment]
Hi @taylorwaggoner 
can you  add kubeclipper  as a sandbox project to https://landscape.cncf.io ?

**Comment by taylorwaggoner** [comment]
Hi @x893675 - what landscape category does kubeclipper belong in? We can't keep it in the installer category because your company cancelled CNCF membership and lost K8s conformance certification. thanks

**Comment by x893675** [comment]
Hi @taylorwaggoner 
What can we do now to rejoin the installer category?

**Comment by taylorwaggoner** [comment]
@x893675 if your company were to re-join CNCF and LF as a member, we could add you back as an installer. If you do not re-join, you'll need to let me know which other landscape category your project fits under.

**Comment by x893675** [comment]
@taylorwaggoner  
KubeClipper has already entered the Sandbox, and it is now onboarding.  The project is focused on installer. and plans for continuous conformance. 
essentially similar to k3s

**Comment by taylorwaggoner** [comment]
Thanks, I'm adding it back under Installer, with CNCF as the company, like k3s (sandbox)

**Comment by taylorwaggoner** [comment]
@x893675 Please note that your conformance certification expires tomorrow May 15 at 11:59 PM PT. I've contacted contact@kubeclipper.io a couple times but have not heard back. If you do not submit a pull request for 1.28 or higher by the end of the day on 5/15, we will remove the listing on the landscape. Please let me know if there are questions. thanks!

**Comment by lixd** [comment]
@taylorwaggoner Sorry, didn't pay attention to the email, we will submit a new pr for 1.30 today

**Pull request merged**
