### PR TITLE
Conformance results for dce-4.0.2 on Oracle Linux Server 8.2 with Kubernetes:1.18.6

### PR DESCRIPTION
**Pull request by BUERCRAZY**
### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [ ] If this is a new entry, have you submitted a signed [participation form](https://github.com/cncf/k8s-conformance/tree/master/participation-form)?
* [x] Did you include the product/project logo in SVG, EPS or AI format?  
* [x] Does your logo clearly state the name of the product/project and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [ ] If your product/project is open source, did you include the `repo_url`?
* [x] Did you copy and paste the [installation and configuration instructions](https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions) into the README.md file in addition to linking to them?

### CODE REVIEW

**Comment by taylorwaggoner** [comment]
@BUERCRAZY DaoCloud Enterprise already has 1.18 conformance from #992.  Is this something different?

**Comment by BUERCRAZY** [comment]
> @BUERCRAZY DaoCloud Enterprise already has 1.18 conformance from #992. Is this something different?
Yes.  In  #992 the version of kubernetes is 1.18.0. This PR is for kubernetes 1.18.6.

**Comment by BUERCRAZY** [comment]
> @BUERCRAZY DaoCloud Enterprise already has 1.18 conformance from #992. Is this something different?

**Comment by taylorwaggoner** [comment]
@BUERCRAZY You don't have to recertify for the same version, since you already have the 1.18 certification.  Thanks!

**Comment by BUERCRAZY** [comment]
> @BUERCRAZY You don't have to recertify for the same version, since you already have the 1.18 certification. Thanks!

Thanks!
Sorry to bother you.
The current situation is that we need the 1.18 certification on the Oracle-Linux Server System. This is why I pull this request.
In addition, the version of Kubernetes, DaoCloud Enterprise and the OS in #992 are 1.18.0, 4.0.1, and CentOS 7.7, which are different in this PR. We run this conformance test of DaoCloud Enterprise 4.0.2 which is based on Kubernetes 1.18.6 on Oracle-Linux Server System.
Could we get this certification?

**Comment by daocloudplf** [comment]
because we have customer want get some evidence about Kubernetes 1.18.6 can support Oracle-Linux  ,so we submit this verification.wish you can help check and approve it ,very appreciate.

**Comment by taylorwaggoner** [comment]
Thanks, you are now Certified Kubernetes

**Pull request merged**
