### PR TITLE
Conformance results for v1.16/JD.com's JDOS Team

### PR DESCRIPTION
**Pull request by yangyefei-bj**
Conformance results for v1.16/JD.com's JDOS Team

### CODE REVIEW

**Comment by taylorwaggoner** [comment]
You are now Certified Kubernetes

**Comment by yangyefei-bj** [comment]
@taylorwaggoner Hi,Taylor,We want to change the product name from JD.com TIG Jingdong Datacenter OS to JD Datacenter OS (JDOS). Can you handle it for us? We also changed the product logo to a new one.(https://github.com/yangyefei-bj/jdos/blob/master/jd.com.svg) Can you update it together?

**Comment by taylorwaggoner** [comment]
@yangyefei-bj I can make that update for you.  Would you possibly prefer to use this logo instead?  We find that vertical logos often appear larger than horizontal. https://landscape.cncf.io/format=card-mode&organization=jd-com&selected=jd-com-member

**Comment by yangyefei-bj** [comment]
@taylorwaggoner We can use this logo you recommend, thanks.

**Comment by yangyefei-bj** [comment]
@taylorwaggoner I uploaded another logo image with a changed aspect ratio. Is this ok?https://github.com/yangyefei-bj/jdos/blob/master/jdos.svg

**Comment by yangyefei-bj** [comment]
@taylorwaggoner Hi, Taylor, Can you help me.

**Comment by taylorwaggoner** [comment]
@yangyefei-bj - Please submit a [new participation form](https://github.com/cncf/k8s-conformance/tree/master/participation-form) with JDOS as the product name.  Please also confirm that you approve using the [vertical logo](https://landscape.cncf.io/format=card-mode&selected=jd-com-member) that we have on file for JD.com's CNCF membership.  We prefer to use a consistent logo for all of a company's entries on the landscape.  Thanks!

**Comment by taylorwaggoner** [comment]
@yangyefei-bj , please let me know if you have any questions about my previous comment. thanks!

**Pull request merged**
