### PR TITLE
Conformance results for v1.20/ericsson-ccd

### PR DESCRIPTION
**Pull request by JanMkl**
### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [X] If this is a new entry, have you submitted a signed [participation form](https://github.com/cncf/k8s-conformance/tree/master/participation-form)?
* [ ] Did you include the product/project logo in SVG, EPS or AI format?  
* [X] Does your logo clearly state the name of the product/project and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [ ] If your product/project is open source, did you include the `repo_url`?
* [X] Did you copy and paste the [installation and configuration instructions](https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions) into the README.md file in addition to linking to them?

### CODE REVIEW

**Comment by JanMkl** [comment]
Renamed the product.yaml to PRODUCT.yaml

**Comment by ErinThacker** [comment]
Hi there, please edit this PR to reflect which version you're submitting for.
Thanks!

**Comment by JanMkl** [comment]
@ErinThacker The PR already was named based on v1.20 do you mean that there shouldn't be the product version in the PR name? Or maybe I misunderstood?

**Comment by ErinThacker** [comment]
@JanMkl - the version listed in the product YAML file is v1.17. I see later that v1.20 is built on v1.17, is that the reasoning behind the discrepancy?

**Comment by JanMkl** [comment]
@ErinThacker Do you mean the version field in PRODUCT.yaml:
`version: 2.17.0`
This is according to instructions the version of the Cloud Container Distribution (CCD) not K8s.
https://github.com/cncf/k8s-conformance/blob/master/instructions.md#productyaml says: 
`version | The version of the product being certified (not the version of Kubernetes it runs).`

**Comment by ErinThacker** [comment]
You are now Certified Kubernetes.

**Pull request merged**
