### PR TITLE
Conformance results for v1.23/replicated

### PR DESCRIPTION
**Pull request by OGtrilliams**
### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [x] If this is a new entry, have you submitted a signed [participation form](https://github.com/cncf/k8s-conformance/tree/master/participation-form)?
* [x] Did you include the product/project logo in SVG, EPS or AI format?  
* [x] Does your logo clearly state the name of the product/project and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [x] If your product/project is open source, did you include the `repo_url`?
* [x] Did you copy and paste the [installation and configuration instructions](https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions) into the README.md file in addition to linking to them?

### CODE REVIEW

**Comment by taylorwaggoner** [comment]
@OGtrilliams please resolve the conflicts, thanks!

**Comment by taylorwaggoner** [comment]
@OGtrilliams please take a look when you have a chance, thanks!

**Comment by JustinN-Replicated** [comment]
@taylorwaggoner will align the bullets to responses (first bullet to 1 etc): 

1.  I do not follow; is the v1.22 results from our previous submission and the contents of /replicated-1.23/v1.23/replicated the results for v1.23? Or are you saying that we had never submitted results for v1.22 either? 
2. This seems related to the above; my apologies for my confusion but could use a deeper explanation if at all possible (or confirmation that @OGtrilliams had attempted to submit for 2 versions at the same time)
3. I will adjust the image to this momentarily (looking to get a proper url from our team that meets your requirements): https://camo.githubusercontent.com/4fdafd9fc9e5f8e564d9697acf74f7e04dc180ef/68747470733a2f2f6b75726c2e73682f6b75726c5f6c6f676f4032782e706e67

**Comment by JustinN-Replicated** [comment]
@OGtrilliams I can't seem to edit this PR; can you add me on it?

**Comment by JustinN-Replicated** [comment]
No worries, thanks @OGtrilliams !

**Comment by JustinN-Replicated** [comment]
@OGtrilliams Just to ask actually, I can see that v1.22 looks like we were included/passed the cert. Were the changes to those files in this PR to align with Replicated branding? That is my best guess for the changes but it is unclear (if so, likely can just get rid of those files to pass the bot and just be more consistent with branding from 1.23 onwards). @taylorwaggoner is it safe to presume that we can not backport those naming/branding changes? If so that is OK - moving forward our intent will be to continue as we did [here](https://github.com/cncf/k8s-conformance/pull/1996)

**Comment by Riaankl** [comment]
@OGtrilliams @JustinN-Replicated 
Just to clarify, the CNCF-CI bot check the files as the PRs are submitted. 
One of the requiements of the conformance program is that every release end product must be submittied in it's own PR.
Therefore you must make a PR for `Conformance results for v1.23/replicated` and another for `Conformance results for v1.22/replicated` 
I noticed the 1.24 is in it's own PR and all checks passed.

**Comment by taylorwaggoner** [comment]
@JustinN-Replicated to resolve the issues, you'll want to remove the 1.22 results, since you already have a certification for that version.   What branding or name changes do you mean?

**Comment by JustinN-Replicated** [comment]
Thank you so much for the details @taylorwaggoner ! Will work to get the checks passing on this through today; I have deleted the mentioned files. As for the branding stuff, no worries on that at all -  was more of a change at our organization than anything else and I thought it may have been related but is not. Sorry about that confusion on my part.

**Comment by taylorwaggoner** [comment]
@JustinN-Replicated i think all you need to do here is update the logo URL to the one you have in #1996

**Comment by JustinN-Replicated** [comment]
> @JustinN-Replicated i think all you need to do here is update the logo URL to the one you have in #1996

Had intended to do that but had missed - sorry about that!

**Comment by taylorwaggoner** [comment]
You are now Certified Kubernetes

**Pull request merged**
