### PR TITLE
Conformance results for v1.8/heptio

### PR DESCRIPTION
**Pull request by timothysc**
vendor: Heptio
name: AWS-Quickstart
version: v1.8.2
website_url: https://aws.amazon.com/quickstart/architecture/heptio-kubernetes
documentation_url: https://github.com/heptio/aws-quickstart
product_logo_url: https://d1.awsstatic.com/partner-network/QuickStart/datasheets/heptio-kubernetes-qs.38d79785e9e107b624e911225e79066ad378e019.png

### CODE REVIEW

**Comment by kbarnard10** [comment]
+1

**Comment by timothysc** [comment]
@kbarnard10 where do we need to sign?

**Comment by kbarnard10** [comment]
@timothysc Easiest way is through this DocuSign link: https://na3.docusign.net/Member/PowerFormSigning.aspx?PowerFormId=ba08f93a-65ca-4c5d-8210-d5c858bb9208

**Comment by dankohn** [comment]
And link to PDF is here: https://github.com/cncf/k8s-conformance/blob/master/participation-form/Certified_Kubernetes_Form.md

**Pull request merged**
